{
 "title": "Kubernetes Dashboard",
 "description": "to monitor pod cpu, memory, I/O, RX/TX and cluster cpu, memory request/limit/real usage, RX/TX, Disk I/O ",
 "tags": [
  "kubernetes",
  "prometheus",
  "cadvisor"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster\"},pod)"
    }
   },
   {
    "name": "netface",
    "query": {
     "query": "container_network_transmit_bytes_total"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "loki", "label": "Loki datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Alerts Count - $cluster",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(fingerprint, labels_alertname, ruleUID) (rate({instance_id=\"793527\"} | json | current = `Alerting` | ruleTitle =~ `(Kube.*|CPUThrottlingHigh)` | labels_cluster =~ `$cluster` [$__auto]))"
    }
   ]
  },
  {
   "title": "Logs in My-Cluster",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({namespace=~\"$namespace\", cluster=\"my-cluster\"} | json | level = `INFO` [$__auto]))",
     "legendFormat": "INFO"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({namespace=~\"$namespace\", cluster=\"my-cluster\"} | json | level = `WARN` [$__auto]))",
     "legendFormat": "WARN"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({namespace=~\"$namespace\", cluster=\"my-cluster\"} | json | level = `ERROR` [$__auto]))",
     "legendFormat": "ERROR"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({namespace=~\"$namespace\", cluster=\"my-cluster\"} | json | level = `DEBUG` [$__auto]))",
     "legendFormat": "DEBUG"
    }
   ]
  },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\", job=\"integrations/node_exporter\",cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\",cluster=~\"$cluster\"}) / sum(kube_node_status_capacity{resource=\"cpu\",cluster=~\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\",cluster=~\"$cluster\"}) / sum(kube_node_status_capacity{resource=\"cpu\",cluster=~\"$cluster\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"integrations/node_exporter\",cluster=~\"$cluster\"} - node_memory_MemAvailable_bytes{job=\"integrations/node_exporter\",cluster=~\"$cluster\"}) / sum(node_memory_MemTotal_bytes{job=\"integrations/node_exporter\",cluster=~\"$cluster\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\",cluster=~\"$cluster\"}) / sum(machine_memory_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Nodes in My-Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"integrations/node_exporter\"})"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"integrations/node_exporter\", cluster=~\".+\"})"
    }
   ]
  },
  {
   "title": "Namespaces in My-Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_status_phase{phase=\"Active\"})"
    }
   ]
  },
  {
   "title": "Total Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_status_phase{cluster=~\".+\",phase=\"Active\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\", job=\"integrations/node_exporter\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\", cluster=~\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\", cluster=~\"$cluster\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\", cluster=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"integrations/node_exporter\", cluster=~\"$cluster\"} - node_memory_MemAvailable_bytes{job=\"integrations/node_exporter\", cluster=~\"$cluster\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\", cluster=~\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\", cluster=~\"$cluster\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_memory_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Running Pods in My-Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase='Running'})"
    }
   ]
  },
  {
   "title": "Total Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase='Running', cluster=~\".+\"})"
    }
   ]
  },
  {
   "title": "My-Cluster - Running Pods per namespace",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(cluster, namespace) (kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "{{cluster}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Failed pods",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"}) by (cluster,phase)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Pending pods",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"}) by (cluster,phase)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Global CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{job=\"integrations/node_exporter\",mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=~\".+\", job=\"integrations/node_exporter\"} - node_memory_MemAvailable_bytes{cluster=~\".+\", job=\"integrations/node_exporter\"}) / sum(node_memory_MemTotal_bytes{cluster=~\".+\", job=\"integrations/node_exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_memory_working_set_bytes{namespace=~\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(cluster, pod) (rate(container_network_receive_bytes_total{instance=~\".+\", interface=~\".+\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "received byte - {{cluster}} - {{pod}}"
    },
    {
     "expr": "sum by(cluster, pod) (rate(container_network_transmit_bytes_total{instance=~\".+\", interface=~\".+\", cluster=~\"$cluster\", deployment_environment=\"kansas-playon-prod\"}[$__rate_interval]))",
     "legendFormat": "transmit bytes - {{cluster}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(device) (rate(container_fs_reads_bytes_total{instance=~\".+\", cluster=~\"$cluster\", deployment_environment=~\".*-prod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(device) (rate(container_fs_writes_bytes_total{instance=~\".+\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Pod Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Network Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(interface) (rate(container_network_receive_bytes_total{interface=~\"$netface\",cluster=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod Read/Write Iops",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(pod) (rate(container_fs_writes_total{id=~\".+\", device=~\".+\", pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod CPU Limits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by(pod) (kube_pod_container_resource_limits{pod=~\".+\", resource=\"cpu\", unit=\"core\", cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod Memory Limits",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (kube_pod_container_resource_limits{pod=~\".+\", resource=\"memory\", unit=\"byte\", cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod CPU Request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by(pod) (kube_pod_container_resource_requests{pod=~\".+\", resource=\"cpu\", unit=\"core\", cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod Memory Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max( kube_pod_container_resource_requests{pod=~\".+\", resource=\"memory\", unit=\"byte\", cluster=~\"$cluster\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}