{
 "title": "Logs",
 "description": "Universal and flexible dashboard for logging",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", cluster=\"$cluster\"},pod)"
    }
   },
   { "name": "level", "label": "Log level", "query": "INFO, DEBUG, WARN, ERROR" }
  ]
 },
 "panels": [
  {
   "title": "Total Count: of $level",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"} | json | level=\"$level\")[$__interval]))"
    }
   ]
  },
  {
   "title": "\"$level\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({namespace=~\"$namespace\",cluster=~\"$cluster\",pod=~\"$pod\"} | json | level=\"$level\")[$__interval])) * 100 / sum(count_over_time(({namespace=~\"$namespace\",cluster=~\"$cluster\",pod=~\"$pod\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Logs level=$level",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"} | json | level=`$level` | __error__=``"
    }
   ]
  },
  {
   "title": "Matched word: \"$level\" historical",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=~\"$namespace\",cluster=~\"$cluster\",pod=~\"$pod\"} | json | level=\"$level\")[$__interval])) by (container)"
    }
   ]
  },
  {
   "title": "\"$level\" Rate per  Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(({namespace=~\"$namespace\",cluster=~\"$cluster\",pod=~\"$pod\"} | json | level=\"$level\")[30s])) by (pod)"
    }
   ]
  },
  {
   "title": "Matched word: \"$level\" donut",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=~\"$namespace\",cluster=~\"$cluster\",pod=~\"$pod\"} | json | level=\"$level\")[$__interval])) by (pod, level)"
    }
   ]
  }
 ]
}