{
 "title": "Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_TEMPO", "query": "tempo" },
   { "name": "DS_LOKI", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "# Welcome to the QuickPizza SRE Demo!\n\nThis dashboard includes an overview of the architecture, as well as some high level stats about the application.\nIt should serve as an entrypoint to view the health of the system at a quick glance.\n\nYou can try out the application at [quickpizza-demo.grafana.fun](https://quickpizza-demo.grafana.fun/)\n"
   },
   "targets": [
    {
     "filters": [
      { "id": "5269b1d8", "operator": "=", "scope": "span" }
     ],
     "limit": 20
    }
   ]
  },
  {
   "type": "nodeGraph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "filters": [
      { "id": "8de6ae50", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "serviceMapQuery": "{}"
    }
   ]
  },
  {
   "type": "table",
   "description": "This panel summarizes request duration and rates across all microservices. Check out the App Observability plugin for more details.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_spanmetrics_latency_bucket{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\"} [$__rate_interval])) by (job, le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\"} [$__rate_interval])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=\"do-nyc1-demo-infra\",namespace=\"quickpizza\",pod=~\"quickpizza-.*\"} !~ \"err|panic|ERR|warn|WARN|info|INFO\" [$__auto]))",
     "legendFormat": "No Level"
    },
    {
     "expr": "sum(count_over_time({cluster=\"do-nyc1-demo-infra\",namespace=\"quickpizza\",pod=~\"quickpizza-.*\"} |~ \"err|panic|ERR\" [$__auto]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(count_over_time({cluster=\"do-nyc1-demo-infra\",namespace=\"quickpizza\",pod=~\"quickpizza-.*\"} |~ \"warn|WARN\" [$__auto]))",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum(count_over_time({cluster=\"do-nyc1-demo-infra\",namespace=\"quickpizza\",pod=~\"quickpizza-.*\"} |~ \"info|INFO\" [$__auto]))",
     "legendFormat": "Info"
    }
   ]
  },
  {
   "title": "Deployment Health",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"quickpizza\"}/kube_deployment_spec_replicas{namespace=\"quickpizza\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 14 },
   "options": {
    "content": "# About _Deployment Health_\n\nThe panel on the left displays the Kubernetes deployment health.\n\nYellow blocks represent that some pods are not ready while a red block is caused by all pods failing."
   }
  },
  {
   "type": "logs",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{namespace=\"quickpizza\", pod=~\"quickpizza-(copy|catalog|recommendations|ws)-.*\"} | logfmt | line_format `{{.msg}} user={{.user}} traceID={{.traceID}}`"
    }
   ]
  },
  { "title": "⏱️ Request Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"frontend\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 23 },
   "options": {
    "content": "# About _Request Timings_\n\nThe _Heatmap_ to the left displays request timings and their frequency.\n\nIt can be read as follows:\n\n* The Y Axis shows the duration of the requests. Blocks found higher up, represent a longer request duration.\n* The color of the blocks represent the amount of requests in the respective range of timings. A lighter block contains more requests than a dark one.\n\nWith a higher request rate, the variance between response times will increase. Ideally, a clear line at the bottom should be visible. This means that most requests finished quickly."
   }
  },
  {
   "title": "Request Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}