{
 "title": "Performance Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_TEMPO", "query": "tempo" },
   { "name": "DS_LOKI", "query": "loki" },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(http_request_duration_seconds_bucket,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Frontend Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_request_duration_seconds_bucket{job=\"frontend\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95 "
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_request_duration_seconds_bucket{job=\"frontend\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90,sum(rate(http_request_duration_seconds_bucket{job=\"frontend\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{}[$__rate_interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Database QPS",
   "type": "stat",
   "description": "Queries Per Second",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname=~\".+\",job=~\".+\",cluster=~\".*\",instance=~\".+\"}[$__rate_interval])) + sum(irate(pg_stat_database_xact_rollback{datname=~\".+\",job=~\".+\",cluster=~\".*\",instance=~\".+\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Details for $component", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "component" },
  {
   "title": "Request rate by path",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$component\",path!~\"/_app.*\"}[$__rate_interval])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(http_request_duration_seconds_bucket{job=\"$component\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95 - $component"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_request_duration_seconds_bucket{job=\"$component\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99 - $component"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{job=\"$component\"}[$__rate_interval])) / sum(rate(http_request_duration_seconds_count{job=\"$component\"}[$__rate_interval]))",
     "legendFormat": "Avg - $component"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$component\",status!~\"(2..|0)\"}[$__rate_interval])) / sum(rate(http_requests_total{job=\"$component\"}[$__rate_interval]))",
     "legendFormat": "Error Rate"
    }
   ]
  }
 ]
}