{
 "title": "Operations DrillDown",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_count{deployment_environment=\"$env\"},job)"
    }
   },
   {
    "name": "span_name",
    "label": "Operation",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_count{job=\"$job\"},span_name)"
    }
   },
   { "name": "env", "label": "Environment", "query": "kansas-prod" }
  ]
 },
 "panels": [
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", span_name=\"$span_name\", deployment_environment=~\"$env\"} [$__rate_interval])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", span_name=\"$span_name\", deployment_environment=~\"$env\", status_code=\"STATUS_CODE_ERROR\"} [$__rate_interval])) by (job) OR sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", span_name=\"$span_name\", deployment_environment=~\"$env\"} [$__rate_interval])) by (job) * 0) / sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", span_name=\"$span_name\", deployment_environment=~\"$env\"} [$__rate_interval])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", span_name=\"$span_name\", deployment_environment=~\"$env\"} [$__rate_interval])) by (le,job))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "filters": [
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": []
      },
      {
       "id": "2d97b35e",
       "operator": "=",
       "scope": "resource",
       "tag": "deployment.environment",
       "value": [ "$env" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"$service\" && resource.service.namespace=\"$namespace\" && status=error}",
     "tableType": "traces"
    }
   ]
  }
 ]
}