{
 "title": "SLO Overview",
 "tags": [ "slo" ],
 "panels": [
  {
   "title": "Above Target (1 day)",
   "type": "stat",
   "description": "The number of SLIs that are meeting their SLO objective in the last 1d",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n\t\t(\n\t\t  sum by (grafana_slo_uuid) (sum_over_time((grafana_slo_success_rate_5m < 1e308)[1d:5m]))\n\t\t  / sum by (grafana_slo_uuid) (sum_over_time((grafana_slo_total_rate_5m < 1e308)[1d:5m]))\n\t\t  # combine with series that aren't producing grafana_slo_success_rate_5m and grafana_slo_total_rate_5m\n\t\t  or avg by (grafana_slo_uuid) (grafana_slo_sli_1d)\n\t\t)\n\t\t> on(grafana_slo_uuid) grafana_slo_objective\n\t  ) OR on() vector(0)\n\t  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Above Target (6 hour)",
   "type": "stat",
   "description": "The number of SLIs that are meeting their SLO objective in the last 6h",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n\t\t(\n\t\t  sum by (grafana_slo_uuid) (sum_over_time((grafana_slo_success_rate_5m < 1e308)[6h:5m]))\n\t\t  / sum by (grafana_slo_uuid) (sum_over_time((grafana_slo_total_rate_5m < 1e308)[6h:5m]))\n\t\t  # combine with series that aren't producing grafana_slo_success_rate_5m and grafana_slo_total_rate_5m\n\t\t  or avg by (grafana_slo_uuid) (grafana_slo_sli_6h)\n\t\t)\n\t\t> on(grafana_slo_uuid) grafana_slo_objective\n\t  ) OR on() vector(0)\n\t  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Above Target (1 hour)",
   "type": "stat",
   "description": "The number of SLIs that are meeting their SLO objective in the last 1h",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n\t\t(\n\t\t  sum by (grafana_slo_uuid) (sum_over_time((grafana_slo_success_rate_5m < 1e308)[1h:5m]))\n\t\t  / sum by (grafana_slo_uuid) (sum_over_time((grafana_slo_total_rate_5m < 1e308)[1h:5m]))\n\t\t  # combine with series that aren't producing grafana_slo_success_rate_5m and grafana_slo_total_rate_5m\n\t\t  or avg by (grafana_slo_uuid) (grafana_slo_sli_1h)\n\t\t)\n\t\t> on(grafana_slo_uuid) grafana_slo_objective\n\t  ) OR on() vector(0)\n\t  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLOs Defined",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(3)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SLOs Recording",
   "type": "stat",
   "description": "The number of SLOs that are recording values",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (grafana_slo_uuid)(grafana_slo_sli_5m)) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recorded SLI Series",
   "type": "stat",
   "description": "The total number of series created by SLO recording rules.",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"grafana_slo_.*\", grafana_slo_uuid!=\"\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "description": "SLO name with hyperlink to the SLO's dashboard",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": {
    "content": "#### [Data API Successful Requests](/d/cdlavnka6i6m8e)\n\nWatches the target=/api/data label and evaluates the percentage of successful requests. The target of this SLO is to have 80% of requests to /api/data be successful with 200 status code\n"
   }
  },
  {
   "title": "SLI (last 28d)",
   "type": "stat",
   "description": "Service level indicator's value over the last 28d",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# omit NaN by comparing to Infinity\nsum(sum_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"} < 1e308)[28d:5m]))\n/ sum(sum_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"} < 1e308)[28d:5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "stat",
   "description": "The unspent error budget over the last {0.8 28d} Window",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\t\t# omit NaN by comparing to Infinity\n\t\tsum(sum_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"} < 1e308)[28d:5m]))\n\t\t/ sum(sum_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"} < 1e308)[28d:5m]))\n\t\t- on() grafana_slo_objective{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"}\n\t)\n\t/ on () (1 - grafana_slo_objective{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "description": "Service level indicator",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(grafana_slo_sli_5m{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"}[$__interval:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "description": "SLO name with hyperlink to the SLO's dashboard",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": {
    "content": "#### [Service Availability](/d/cdlazm3mte70ge)\n\nSLI measures the number of successful requests to each service. The target is to have 99% of requests successful\n"
   }
  },
  {
   "title": "SLI (last 28d)",
   "type": "stat",
   "description": "Service level indicator's value over the last 28d",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# omit NaN by comparing to Infinity\nsum(sum_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"ozjcibubx7l7bqedfthmg\"} < 1e308)[28d:5m]))\n/ sum(sum_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"ozjcibubx7l7bqedfthmg\"} < 1e308)[28d:5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "stat",
   "description": "The unspent error budget over the last {0.8 28d} Window",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\t\t# omit NaN by comparing to Infinity\n\t\tsum(sum_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"ozjcibubx7l7bqedfthmg\"} < 1e308)[28d:5m]))\n\t\t/ sum(sum_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"ozjcibubx7l7bqedfthmg\"} < 1e308)[28d:5m]))\n\t\t- on() grafana_slo_objective{grafana_slo_uuid=\"ozjcibubx7l7bqedfthmg\"}\n\t)\n\t/ on () (1 - grafana_slo_objective{grafana_slo_uuid=\"ozjcibubx7l7bqedfthmg\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "description": "Service level indicator",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(avg_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"ozjcibubx7l7bqedfthmg\"} < 1e308)[$__interval:]))\n/ sum(avg_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"ozjcibubx7l7bqedfthmg\"} < 1e308)[$__interval:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "description": "SLO name with hyperlink to the SLO's dashboard",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "options": {
    "content": "#### [Service Latency SLO](/d/edlayp6cdx79cd)\n\nLatency SLO grouped by service. The SLI is a percentage of requests with latency under 1 second. If 100% SLI then all requests are under 1 second. Target is to maintain 95% requests under 1 second across all services\n"
   }
  },
  {
   "title": "SLI (last 28d)",
   "type": "stat",
   "description": "Service level indicator's value over the last 28d",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# omit NaN by comparing to Infinity\nsum(sum_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\"} < 1e308)[28d:5m]))\n/ sum(sum_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\"} < 1e308)[28d:5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "stat",
   "description": "The unspent error budget over the last {0.95 28d} Window",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\t\t# omit NaN by comparing to Infinity\n\t\tsum(sum_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\"} < 1e308)[28d:5m]))\n\t\t/ sum(sum_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\"} < 1e308)[28d:5m]))\n\t\t- on() grafana_slo_objective{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\"}\n\t)\n\t/ on () (1 - grafana_slo_objective{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "description": "Service level indicator",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(avg_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\"} < 1e308)[$__interval:]))\n/ sum(avg_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\"} < 1e308)[$__interval:]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}