{
 "title": "Docker Logs",
 "tags": [ "docker-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus Data Source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki Data Source", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(machine_scrape_error, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(machine_scrape_error{job=~\"$job\"}, instance)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_last_seen{job=~\"$job\", instance=~\"$instance\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Integration Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs",
   "type": "stat",
   "description": "Shows if logs are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"integrations/docker\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Latest logs received",
   "type": "stat",
   "description": "Shows the timestamp of the latest logs received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"integrations/docker\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "stat",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 0, "w": 0, "x": 0, "y": 5 } },
  {
   "title": "Total Log Lines",
   "type": "stat",
   "description": "Total number of log lines including errors and warnings.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\", container=~\"$container\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "description": "Total number of log lines of level: warning.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\", container=~\"$container\"} |= \"Warning\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Total number of log lines of level: error.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\", container=~\"$container\"} |= \"Error\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "stat",
   "description": "Percentage of log lines with level: Error out of total log lines.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum( count_over_time({job=~\"$job\", instance=~\"$instance\", container=~\"$container\"} |= \"Error\" [$__interval]) ) / sum( count_over_time({job=~\"$job\", instance=~\"$instance\", container=~\"$container\"} [$__interval]) )"
    }
   ]
  },
  {
   "title": "Bytes Used",
   "type": "stat",
   "description": "Total number of bytes for log lines including errors and warnings.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({job=~\"$job\", instance=~\"$instance\", container=~\"$container\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Historical Logs / Warnings / Errors",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\", container=~\"$container\"}[$__interval]))"
    },
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\", container=~\"$container\"} |= \"Warning\" [$__interval]))"
    },
    {
     "expr": "sum(count_over_time({job=~\"$job\", instance=~\"$instance\", container=~\"$container\"} |= \"Error\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 0, "w": 0, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "{job=~\"$job\", instance=~\"$instance\", container=~\"$container\"} |= \"Error\""
      }
     ]
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "row",
   "gridPos": { "h": 0, "w": 0, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Warnings",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "{job=~\"$job\", instance=~\"$instance\", container=~\"$container\"} |= \"Warning\""
      }
     ]
    }
   ]
  },
  {
   "title": "Complete Log File",
   "type": "row",
   "gridPos": { "h": 0, "w": 0, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Full Log File",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "{job=~\"$job\", instance=~\"$instance\", container=~\"$container\"}"
      }
     ]
    }
   ]
  }
 ]
}