{
 "title": "AWS VPN",
 "description": "Dashboards for AWS VPN metrics.",
 "tags": [ "aws-cloud-provider" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(aws_natgateway_packets_drop_count_sum, scrape_job)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(aws_vpn_tunnel_state_maximum{scrape_job=~\"$job\"}, region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Please see [Monitoring VPN tunnels using Amazon CloudWatch](https://docs.aws.amazon.com/vpn/latest/s2svpn/monitoring-cloudwatch-vpn.html) for details on how to setup and filter metrics used in this dashboard.\n\nFor more information, please see the [AWS Virtual Private Network Documentation](https://docs.aws.amazon.com/vpn/) "
   }
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "VPN Tunnel State",
   "type": "timeseries",
   "description": "The state of the tunnels. For static VPNs, 0 indicates DOWN and 1 indicates UP. Values between 0 and 1 indicate at least one tunnel is not UP.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(name) (aws_vpn_tunnel_state_maximum{region=~\"$region\", name!=\"global\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total Amount of Data In",
   "type": "timeseries",
   "description": "The total number of kilobytes received on the AWS side of the connection through the VPN tunnel from a gateway (after decryption). Maximum bandwidth per VPN tunnel is 1.25 GBPS.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(aws_vpn_tunnel_data_in_sum{dimension_VpnId!=\"\"}[5m]) / 1e6",
     "legendFormat": "{{ dimension_VpnId }}"
    }
   ]
  },
  {
   "title": "Total Amount of Data Out",
   "type": "timeseries",
   "description": "The total megabytes sent from the AWS side of the connection through the VPN tunnel to the customer gateway (before encryption).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(aws_vpn_tunnel_data_out_sum{dimension_VpnId!=\"\"}[5m]) / 1e6",
     "legendFormat": "{{ dimension_VpnId }}"
    }
   ]
  }
 ]
}