{
 "title": "AWS NAT Gateways",
 "description": "Visualize real-time metrics for your CloudWatch NAT Gateways",
 "tags": [ "aws-cloud-provider" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(aws_natgateway_packets_drop_count_sum, scrape_job)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(aws_natgateway_packets_drop_count_sum{scrape_job=~\"$job\"}, region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Please see [Monitor NAT gateways with Amazon CloudWatch](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway-cloudwatch.html) for details on how to setup and filter metrics used in this dashboard."
   }
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Dropped Packets",
   "type": "timeseries",
   "description": "The number of packets dropped by the NAT gateway.\n\nA value greater than zero might indicate an ongoing transient issue with the NAT gateway.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_natgateway_packets_drop_count_sum{scrape_job=~\"$job\", region=~\"$region\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Port Allocation Errors",
   "type": "timeseries",
   "description": "The number of times the NAT gateway could not allocate a source port.\n\nA value greater than zero indicates that too many concurrent connections are open through the NAT gateway.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_natgateway_error_port_allocation_sum{scrape_job=~\"$job\", region=~\"$region\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Idle Timeout Count",
   "type": "timeseries",
   "description": "The number of connections that transitioned from the active state to the idle state. An active connection transitions to idle if it was not closed gracefully and there was no activity for the last 350 seconds.\n\nA value greater than zero indicates that there are connections that have been moved to an idle state. If the value for IdleTimeoutCount increases, it might indicate that clients behind the NAT gateway are re-using stale connections.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_natgateway_idle_timeout_count_sum{scrape_job=~\"$job\", region=~\"$region\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "description": "The total number of concurrent active TCP connections through the NAT gateway.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_natgateway_active_connection_count_maximum{scrape_job=~\"$job\", region=~\"$region\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Established Connections",
   "type": "timeseries",
   "description": "The number of connections established through the NAT gateway.\n\nIf the value for ConnectionEstablishedCount is less than the value for ConnectionAttemptCount, this indicates that clients behind the NAT gateway attempted to establish new connections for which there was no response.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_natgateway_connection_established_count_sum{scrape_job=~\"$job\", region=~\"$region\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Attempted Connections",
   "type": "timeseries",
   "description": "The number of connection attempts made through the NAT gateway.\n\nIf the value for ConnectionEstablishedCount is less than the value for ConnectionAttemptCount, this indicates that clients behind the NAT gateway attempted to establish new connections for which there was no response.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_natgateway_connection_attempt_count_sum{scrape_job=~\"$job\", region=~\"$region\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  { "title": "Bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Bytes Out To Destination",
   "type": "timeseries",
   "description": "The number of bytes sent out through the NAT gateway to the destination.\n\nA value greater than zero indicates that there is traffic going to the internet from clients that are behind the NAT gateway. If the value for BytesOutToDestination is less than the value for BytesInFromSource, there might be data loss during NAT gateway processing.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_natgateway_bytes_out_to_destination_sum{scrape_job=~\"$job\", region=~\"$region\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Bytes Out To Source",
   "type": "timeseries",
   "description": "The number of bytes sent through the NAT gateway to the clients in your VPC.\n\nA value greater than zero indicates that there is traffic coming from the internet to clients that are behind the NAT gateway. If the value for BytesOutToSource is less than the value for BytesInFromDestination, there might be data loss during NAT gateway processing, or traffic being actively blocked by the NAT gateway.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "aws_natgateway_bytes_out_to_source_sum{scrape_job=~\"$job\", region=~\"$region\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Bytes In From Source",
   "type": "timeseries",
   "description": "The number of bytes received by the NAT gateway from clients in your VPC.\n\nIf the value for BytesOutToDestination is less than the value for BytesInFromSource, there might be data loss during NAT gateway processing.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "aws_natgateway_bytes_in_from_source_sum{scrape_job=~\"$job\", region=~\"$region\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Bytes In From Destination",
   "type": "timeseries",
   "description": "The number of bytes received by the NAT gateway from the destination.\n\nIf the value for BytesOutToSource is less than the value for BytesInFromDestination, there might be data loss during NAT gateway processing, or traffic being actively blocked by the NAT gateway.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "aws_natgateway_bytes_in_from_destination_sum{scrape_job=~\"$job\", region=~\"$region\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Packets Out To Destination",
   "type": "timeseries",
   "description": "The number of packets sent out through the NAT gateway to the destination.\n\nA value greater than zero indicates that there is traffic going to the internet from clients that are behind the NAT gateway. If the value for PacketsOutToDestination is less than the value for PacketsInFromSource, there might be data loss during NAT gateway processing.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_natgateway_packets_out_to_destination_sum{scrape_job=~\"$job\", region=~\"$region\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Packets Out To Source",
   "type": "timeseries",
   "description": "The number of packets sent through the NAT gateway to the clients in your VPC.\n\nA value greater than zero indicates that there is traffic coming from the internet to clients that are behind the NAT gateway. If the value for PacketsOutToSource is less than the value for PacketsInFromDestination, there might be data loss during NAT gateway processing, or traffic being actively blocked by the NAT gateway.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_natgateway_packets_out_to_source_sum{scrape_job=~\"$job\", region=~\"$region\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Packets In From Source",
   "type": "timeseries",
   "description": "The number of packets received by the NAT gateway from clients in your VPC.\n\nIf the value for PacketsOutToDestination is less than the value for PacketsInFromSource, there might be data loss during NAT gateway processing.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_natgateway_packets_in_from_source_sum{scrape_job=~\"$job\", region=~\"$region\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Packets In From Destination",
   "type": "timeseries",
   "description": "The number of packets received by the NAT gateway from the destination.\n\nIf the value for PacketsOutToSource is less than the value for PacketsInFromDestination, there might be data loss during NAT gateway processing, or traffic being actively blocked by the NAT gateway.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_natgateway_packets_in_from_destination_sum{scrape_job=~\"$job\", region=~\"$region\"}",
     "legendFormat": "{{region}}"
    }
   ]
  }
 ]
}