{
 "title": "AWS API Gateway",
 "description": "Visualize AWS API Gateway metrics",
 "tags": [ "aws-cloud-provider" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(aws_apigateway_count_sum,scrape_job)"
    }
   },
   {
    "name": "account_id",
    "label": "Account ID",
    "query": {
     "query": "label_values(aws_apigateway_count_sum{job=~\"$job\"},account_id)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(aws_apigateway_count_sum{job=~\"$job\", account_id=~\"$account_id\"},region)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(aws_apigateway_count_sum{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\"},dimension_ApiId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Count",
   "type": "timeseries",
   "description": "The total number of API requests made to the API Gateway instance/s.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_apigateway_count_sum{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_ApiId=~\"$instance\"}) by (dimension_ApiId)",
     "legendFormat": "Count Sum"
    }
   ]
  },
  {
   "title": "Latency / IntegrationLatency",
   "type": "timeseries",
   "description": "Latency and integration latency values for the API Gateway instance/s.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(aws_apigateway_latency_average{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_ApiId=~\"$instance\"})",
     "legendFormat": "Latency Avg"
    },
    {
     "expr": "avg(aws_apigateway_integration_latency_average{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_ApiId=~\"$instance\"})",
     "legendFormat": "Integration Latency Avg"
    }
   ]
  },
  {
   "title": "4XXError / 5XXError",
   "type": "timeseries",
   "description": "The total number of 4XX and 5XX errors for the API Gateway instance/s.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Total Error Rate",
     "expr": "sum(aws_apigateway_4xx_sum{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_ApiId=~\"$instance\"})",
     "legendFormat": "4XX Error Sum"
    },
    {
     "expr": "sum(aws_apigateway_5xx_sum{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_ApiId=~\"$instance\"})",
     "legendFormat": "5XX Error Sum"
    },
    { "expression": "($e4xx+$e5xx)*100/$count", "type": "math" }
   ]
  }
 ]
}