{
 "title": "AWS SQS",
 "description": "Visualize AWS SQS metrics",
 "tags": [ "aws-cloud-provider" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(aws_sqs_info,scrape_job)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(aws_sqs_number_of_messages_received_average{scrape_job=~\"$job\"},region)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(aws_sqs_number_of_messages_received_average{scrape_job=~\"$job\", region=~\"$region\"},dimension_QueueName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Showing metrics only for AWS resources that have tags assigned to them. For more information, see [Amazon CloudWatch Metrics for Amazon SQS](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-available-cloudwatch-metrics.html)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "aws_sqs_number_of_messages_deleted_average{scrape_job=~\"$job\", region=~\"$region\", dimension_QueueName=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "NumberOfMessagesDeleted_Average - {{dimension_QueueName}}",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "aws_sqs_number_of_messages_received_average{scrape_job=~\"$job\", region=~\"$region\", dimension_QueueName=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "NumberOfMessagesReceived_Average - {{dimension_QueueName}}",
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "aws_sqs_number_of_messages_sent_average{scrape_job=~\"$job\", region=~\"$region\", dimension_QueueName=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "NumberOfMessagesSent_Average - {{dimension_QueueName}}",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ApproximateAgeOfOldestMessage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "aws_sqs_approximate_age_of_oldest_message_average{scrape_job=~\"$job\", region=~\"$region\", dimension_QueueName=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "ApproximateAgeOfOdestMessage_Average - {{dimension_QueueName}}",
     "metricName": "ApproximateAgeOfOldestMessage",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ApproximateNumberOfMessages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_visible_average{scrape_job=~\"$job\", region=~\"$region\", dimension_QueueName=~\"$instance\"}",
     "legendFormat": "ApproximateNumberOfMessagesVisible_Average - {{dimension_QueueName}}"
    },
    {
     "expr": "aws_sqs_approximate_number_of_messages_not_visible_average{scrape_job=~\"$job\", region=~\"$region\", dimension_QueueName=~\"$instance\"}",
     "legendFormat": "ApproximateNumberOfMessagesNotVisible_Average - {{dimension_QueueName}}"
    },
    {
     "expr": "aws_sqs_approximate_number_of_messages_delayed_average{scrape_job=~\"$job\", region=~\"$region\", dimension_QueueName=~\"$instance\"}",
     "legendFormat": "ApproximateNumberOfMessagesDelayed_Average - {{dimension_QueueName}}"
    }
   ]
  },
  {
   "title": "NumberOfEmptyReceives",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "aws_sqs_number_of_empty_receives_average{scrape_job=~\"$job\", region=~\"$region\", dimension_QueueName=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "NumberOfEmptyReceives_Average - {{dimension_QueueName}}",
     "metricName": "NumberOfEmptyReceives",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "SentMessageSize",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "QueueName": "$queue" },
     "expr": "aws_sqs_sent_message_size_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_QueueName=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "SentMessageSize_Sum - {{dimension_QueueName}}",
     "metricName": "SentMessageSize",
     "namespace": "AWS/SQS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}