{
 "title": "AWS ELB Classic Load Balancer",
 "description": "Visualize AWS ELB Classic Load Balancer metrics",
 "tags": [ "aws-cloud-provider" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(aws_elb_info,scrape_job)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(aws_elb_request_count_sum{scrape_job=~\"$job\"},region)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(aws_elb_request_count_sum{scrape_job=~\"$job\", region=~\"$region\"},dimension_LoadBalancerName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Showing metrics only for AWS resources that have tags assigned to them. For more information, see [Amazon CloudWatch Metrics for Amazon ELB](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-cloudwatch-metrics.html#load-balancer-metric-dimensions-clb)."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "RequestCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "expr": "aws_elb_request_count_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancerName=~\"$instance\", dimension_AvailabilityZone=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "RequestCount_Sum - {{dimension_LoadBalancerName}}",
     "metricName": "RequestCount",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "expr": "aws_elb_latency_average{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancerName=~\"$instance\", dimension_AvailabilityZone=\"\"}",
     "legendFormat": "Latency_Average - {{dimension_LoadBalancerName}}"
    }
   ]
  },
  {
   "title": "HTTPCode_Backend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "expr": "aws_elb_httpcode_backend_2_xx_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancerName=~\"$instance\", dimension_AvailabilityZone=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "HTTPCodeBackend2XX_Sum - {{dimension_LoadBalancerName}}",
     "metricName": "HTTPCode_Backend_5XX",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "expr": "aws_elb_httpcode_backend_3_xx_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancerName=~\"$instance\", dimension_AvailabilityZone=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "HTTPCodeBackend3XX_Sum - {{dimension_LoadBalancerName}}",
     "metricName": "HTTPCode_Backend_5XX",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "expr": "aws_elb_httpcode_backend_4_xx_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancerName=~\"$instance\", dimension_AvailabilityZone=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "HTTPCodeBackend4XX_Sum - {{dimension_LoadBalancerName}}",
     "metricName": "HTTPCode_Backend_5XX",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "expr": "aws_elb_httpcode_backend_5_xx_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancerName=~\"$instance\", dimension_AvailabilityZone=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "HTTPCodeBackend5XX_Sum - {{dimension_LoadBalancerName}}",
     "metricName": "HTTPCode_Backend_5XX",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTPCode_ELB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "expr": "aws_elb_httpcode_elb_4_xx_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancerName=~\"$instance\", dimension_AvailabilityZone=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "HTTPCode_ELB_4XX_Sum - {{dimension_LoadBalancer}}",
     "metricName": "HTTPCode_Backend_5XX",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "expr": "aws_elb_httpcode_elb_5_xx_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancerName=~\"$instance\", dimension_AvailabilityZone=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "HTTPCode_ELB_5XX_Sum - {{dimension_LoadBalancer}}",
     "metricName": "HTTPCode_Backend_5XX",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "SpilloverCount / SurgeQueueLength",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "expr": "aws_elb_surge_queue_length_maximum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancerName=~\"$instance\", dimension_AvailabilityZone=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "SurgeQueueLength_Maximum - {{dimension_LoadBalancerName}}",
     "metricName": "SurgeQueueLength",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "expr": "aws_elb_spillover_count_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancerName=~\"$instance\", dimension_AvailabilityZone=\"\"}",
     "legendFormat": "SpilloverCount_Sum- {{dimension_LoadBalancerName}}"
    }
   ]
  },
  {
   "title": "HostCount / BackendConnectionErrors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "expr": "aws_elb_healthy_host_count_average{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancerName=~\"$instance\", dimension_AvailabilityZone=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "HealthyHostCount_Average - {{dimension_LoadBalancerName}}",
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "expr": "aws_elb_un_healthy_host_count_average{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancerName=~\"$instance\", dimension_AvailabilityZone=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "UnHealthyHostCount_Average - {{dimension_LoadBalancerName}}",
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancerName": "$loadbalancername" },
     "expr": "aws_elb_backend_connection_errors_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancerName=~\"$instance\", dimension_AvailabilityZone=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "BackendConnectionsErrors_Sum - {{dimension_LoadBalancerName}}",
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}