{
 "title": "AWS S3",
 "description": "Visualize Amazon S3 metrics",
 "tags": [ "aws-cloud-provider" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(aws_s3_info, scrape_job)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(aws_s3_number_of_objects_average, region)"
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": "label_values(aws_s3_number_of_objects_average, dimension_BucketName)"
   },
   {
    "name": "filter_id",
    "label": "FilterId",
    "query": "label_values(aws_s3_all_requests_sum{dimension_BucketName=~\"$bucket\"}, dimension_FilterId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24 },
   "content": "Showing metrics only for AWS resources that have tags assigned to them. For more information, see [Amazon CloudWatch Metrics for Amazon S3](https://docs.aws.amazon.com/AmazonS3/latest/userguide/metrics-dimensions.html).\n"
  },
  {
   "title": "Total number of objects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(aws_s3_number_of_objects_average{scrape_job=~\"$job\"}[1d]) > 0)"
    }
   ]
  },
  {
   "title": "Total buckets size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(aws_s3_bucket_size_bytes_average{scrape_job=~\"$job\"}[1d]) > 0)"
    }
   ]
  },
  {
   "title": "Number of objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "last_over_time(aws_s3_number_of_objects_average{scrape_job=~\"$job\", region=~\"$region\", dimension_BucketName=~\"$bucket\"}[1d])",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "Bucket size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "last_over_time(aws_s3_bucket_size_bytes_average{scrape_job=~\"$job\", region=~\"$region\", dimension_BucketName=~\"$bucket\"}[1d])",
     "legendFormat": "{{dimension_BucketName}}"
    }
   ]
  },
  {
   "title": "Request metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Info",
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
     "content": "Enable [Requests metrics](https://docs.aws.amazon.com/AmazonS3/latest/userguide/cloudwatch-monitoring.html) from the AWS console and create a Filter to make sure your requests metrics are reported.\n"
    },
    {
     "title": "Request latency (p95)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(aws_s3_total_request_latency_p95{scrape_job=~\"$job\", region=~\"$region\", dimension_BucketName=~\"$bucket\", dimension_FilterId=~\"$filter_id\"}[2h]) * 1e3",
       "legendFormat": "{{dimension_BucketName}}"
      }
     ]
    },
    {
     "title": "Errors count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_s3_4xx_errors_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_BucketName=~\"$bucket\", dimension_FilterId=~\"$filter_id\"}",
       "legendFormat": "{{dimension_BucketName}}"
      }
     ]
    }
   ]
  }
 ]
}