{
 "title": "AWS Network Loadbalancer",
 "description": "Visualize AWS Network Loadbalancer metrics",
 "tags": [ "aws-cloud-provider" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(aws_networkelb_active_flow_count_sum,scrape_job)"
    }
   },
   {
    "name": "account_id",
    "label": "Account ID",
    "query": {
     "query": "label_values(aws_networkelb_active_flow_count_sum{job=~\"$job\"},account_id)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(aws_networkelb_active_flow_count_sum{job=~\"$job\", account_id=~\"$account_id\"},region)"
    }
   },
   {
    "name": "loadbalancer",
    "label": "Instance",
    "query": {
     "query": "label_values(aws_networkelb_active_flow_count_sum{job=~\"$job\", region=~\"$region\"}, dimension_LoadBalancer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total LoadBalancers",
   "type": "stat",
   "description": "Total count of LoadBalancers.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group({__name__=~\"aws_networkelb_.+\", job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"}) by (account_id, region, dimension_LoadBalancer))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LoadBalancers by Account and Region",
   "type": "table",
   "description": "Count of LoadBalancers by account and region.",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "group({__name__=~\"aws_networkelb_.+\", job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"}) by (account_id, region, dimension_LoadBalancer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthy / Unhealthy Hosts Count",
   "type": "timeseries",
   "description": "Sum of healthy and unhealthy hosts.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_healthy_host_count_sum{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"})",
     "legendFormat": "Healthy Count"
    },
    {
     "expr": "sum(aws_networkelb_un_healthy_host_count_sum{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"})",
     "legendFormat": "Unhealthy Count"
    }
   ]
  },
  {
   "title": "Net/Active Flow Count",
   "type": "timeseries",
   "description": "New and active flows count.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_active_flow_count_sum{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"})",
     "legendFormat": "ActiveFlowCount Sum"
    },
    {
     "expr": "sum(aws_networkelb_new_flow_count_average{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"})",
     "legendFormat": "NewFlowCount Avg"
    }
   ]
  },
  {
   "title": "Net/Active TLS Flow Count",
   "type": "timeseries",
   "description": "New and active TLS flows count.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_active_flow_count_tls_sum{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"})",
     "legendFormat": "ActiveFlowCount TLS Sum"
    },
    {
     "expr": "sum(aws_networkelb_new_flow_count_tls_average{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"})",
     "legendFormat": "NewFlowCount TLS Avg"
    }
   ]
  },
  {
   "title": "ConsumedLCUs",
   "type": "timeseries",
   "description": "Amount of consumed LCUs.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(aws_networkelb_consumed_lcus_average{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"})",
     "legendFormat": "ConsumedLCUs Average"
    },
    {
     "expr": "sum(aws_networkelb_consumed_lcus_sum{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"})",
     "legendFormat": "ConsumedLCUs Sum"
    }
   ]
  },
  {
   "title": "ProcessedBytes",
   "type": "timeseries",
   "description": "Total processed bytes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_processed_bytes_sum{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"})",
     "legendFormat": "ProcessedBytes Sum"
    },
    {
     "expr": "avg(aws_networkelb_processed_bytes_average{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"})",
     "legendFormat": "ProcessedBytes Average"
    }
   ]
  },
  {
   "title": "TLS Negotiation Errors",
   "type": "timeseries",
   "description": "Errors in TLS flows negotiation.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_target_tlsnegotiation_error_count_sum{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"})",
     "legendFormat": "Target Sum"
    },
    {
     "expr": "sum(aws_networkelb_client_tlsnegotiation_error_count_sum{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"})",
     "legendFormat": "Client Sum"
    }
   ]
  },
  {
   "title": "TCP",
   "type": "timeseries",
   "description": "TCP connection resets counts.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_tcp_client_reset_count_sum{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"})",
     "legendFormat": "Client Resets"
    },
    {
     "expr": "sum(aws_networkelb_tcp_target_reset_count_sum{job=~\"$job\", account_id=~\"$account_id\", region=~\"$region\", dimension_LoadBalancer=~\"$loadbalancer\"})",
     "legendFormat": "Target Resets"
    }
   ]
  }
 ]
}