{
 "title": "Billing/Usage",
 "tags": [
  "billing",
  "grafanacloud"
 ],
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "org_slug",
    "label": "Org",
    "query": "label_values(grafanacloud_org_info, org_slug)"
   },
   {
    "name": "org_id",
    "label": "Org ID",
    "query": "label_values(grafanacloud_org_info{org_slug=\"$org_slug\"}, org_id)"
   },
   {
    "name": "metrics_id",
    "label": "Metrics Id",
    "query": "label_values(grafanacloud_instance_info{org_id=~\"$org_id\"}, id)"
   },
   {
    "name": "logs_id",
    "label": "Logs Id",
    "query": "label_values(grafanacloud_logs_instance_info{org_id=~\"$org_id\"}, id)"
   },
   {
    "name": "traces_id",
    "label": "Traces Id",
    "query": "label_values(grafanacloud_traces_instance_info{org_id=~\"$org_id\"}, id)"
   },
   {
    "name": "grafana_id",
    "label": "Grafana Id",
    "query": "label_values(grafanacloud_grafana_instance_info{org_id=~\"$org_id\"}, id)"
   },
   {
    "name": "profiles_id",
    "label": "Profiles Id",
    "query": "label_values(grafanacloud_profiles_instance_info{org_id=~\"$org_id\"}, id)"
   },
   {
    "name": "eval_time",
    "query": "query_result(vector(time()) > vector(1710979200) or vector(1710979200))"
   },
   {
    "name": "is_customer_of_grafana",
    "query": "query_result(count ({__name__=\"grafanacloud_org_total_overage\", org_id=\"$org_id\"} @ $eval_time ) or vector(0))"
   },
   {
    "name": "is_customer_of_partner",
    "query": "query_result(1-$is_customer_of_grafana)"
   }
  ]
 },
 "panels": [
  { "title": "Billable Usage Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(avg without(monetary) (grafanacloud_org_total_overage{org_id=\"$org_id\"}))- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Current Billable Usage Cost"
    },
    {
     "expr": "(grafanacloud_org_spend_commit_credit_total{org_id=\"$org_id\"} > 0)- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Spend Commit Credit Total"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_bill_credit_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Fraction of total credit used this month"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_balance_remaining_credit_total_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Credit remaining as fraction of total credit @ month-start"
    },
    {
     "expr": "(grafanacloud_org_spend_commit_balance_total{org_id=\"$org_id\"} > 0)- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Spend Commit Balance @ month-start"
    },
    {
     "expr": "grafanacloud_org_contract_start_date{org_id=\"$org_id\"} * 1000",
     "legendFormat": "Contract Start Date"
    },
    {
     "expr": "grafanacloud_org_contract_end_date{org_id=\"$org_id\"} * 1000",
     "legendFormat": "Contract End Date"
    }
   ]
  },
  {
   "title": "Current Billable Usage Cost by Product",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(monetary) (grafanacloud_org_metrics_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0 > 0",
     "legendFormat": "Metrics"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_metrics_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0 > 0",
     "legendFormat": "Metrics fraction"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_graphite_metrics_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0 > 0",
     "legendFormat": "Graphite Metrics"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_graphite_metrics_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0 > 0",
     "legendFormat": "Graphite Metrics fraction"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_logs_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0 > 0",
     "legendFormat": "Logs"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_logs_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0 > 0",
     "legendFormat": "Logs fraction"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_logs_retention_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0 > 0",
     "legendFormat": "Logs Retention"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_logs_retention_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0 > 0",
     "legendFormat": "Logs Retention fraction"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_traces_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0 > 0",
     "legendFormat": "Traces"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_traces_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0 > 0",
     "legendFormat": "Traces fraction"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_grafana_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0 > 0",
     "legendFormat": "Grafana Users"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_grafana_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0 > 0",
     "legendFormat": "Grafana Users fraction"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_irm_users_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0 > 0",
     "legendFormat": "IRM Users"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_irm_users_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0 > 0",
     "legendFormat": "IRM Users fraction"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_k6_virtual_user_hours_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0 > 0",
     "legendFormat": "VUh (k6)"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_k6_virtual_user_hours_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0 > 0",
     "legendFormat": "VUh (k6) fraction"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_profiles_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0 > 0",
     "legendFormat": "Profiles"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_profiles_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0 > 0",
     "legendFormat": "Profiles fraction"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_grafana_plugin_users_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0 > 0",
     "legendFormat": "Enterprise Plugin"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_grafana_plugin_users_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0 > 0",
     "legendFormat": "Enterprise Plugin fraction"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_sm_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0 > 0",
     "legendFormat": "Synthetic Monitoring"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_sm_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0 > 0",
     "legendFormat": "Synthetic Monitoring fraction"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_fe_o11y_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0 > 0",
     "legendFormat": "Frontend Observability"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_fe_o11y_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0 > 0",
     "legendFormat": "Frontend Observability fraction"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "## About Billable Usage\n\nThe **billable usage cost** panels display the currently accrued monthly costs for usage of your billable services.\n\n- Metrics ingestion cost is calculated and billed using the 95th percentile of your active series and their samples, called data points, per minute (DPM).\n- Logs and traces costs are calculated and billed according to total monthly ingestion in bytes.\n- Grafana users cost is calculated and billed according to the number of <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/#billing-for-active-users\" target=\"_blank\">active monthly users</a>, with additional per user costs for IRM (and Enterprise plugin for Pro tiers)\n- Load testing (k6) is billed according to <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/k6-billing/\" target=\"_blank\">Virtual User hours (VUh)</a>\n- Synthetic Monitoring is billed according to total monthly <a href=\"https://grafana.com/docs/grafana-cloud/cost-management-and-billing/understand-your-invoice/synthetic-monitoring-invoice/\">test executions</a>.\n\n<a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/#reconcile-invoices\" target=\"_blank\">Reconcile Invoices with this Dashboard</a>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 11 },
   "options": {
    "content": "<div>\n  <a href=\"https://grafana.com/profile/org/invoices\" target=\"_blank\"/>\n    <h1 style=\"\n        background: linear-gradient(120deg, rgb(211, 210, 5), rgb(249, 187, 17));\n        text-align: center;\n        font-size: 1.5em;\n        padding: 0.3em;\n        color: rgb(32, 34, 38);\n    \">\n      View Invoices\n    </h1>\n  </a>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 11 },
   "options": {
    "content": "<div>\n  <a href=\"https://grafana.com/docs/grafana-cloud/account-management/billing-and-usage/#common-billing-questions\" target=\"_blank\"/>\n    <h1 style=\"\n        background: linear-gradient(120deg, rgb(211, 210, 5), rgb(249, 187, 17));\n        text-align: center;\n        font-size: 1.5em;\n        padding: 0.3em;\n        color: rgb(32, 34, 38);\n    \">\n      Billing FAQ\n    </h1>\n  </a>\n</div>\n"
   }
  },
  {
   "title": "Total amount by month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(\n    (\n        sum(grafanacloud_org_spend_commit_balance_total{org_id=\"$org_id\"})\n        - (9999999999 * $is_customer_of_partner) >= 0\n    )\n    and day_of_month() == 11 and hour() == 0\n) > 0\n",
     "legendFormat": "Spend Commit Balance @ month-start"
    },
    {
     "expr": "(\n    (\n        sum(grafanacloud_org_balance_remaining_credit_total_fraction{org_id=\"$org_id\"})\n        - (2 * $is_customer_of_grafana) >= 0\n    )\n    and day_of_month() == 11 and hour() == 0\n)\n",
     "legendFormat": "Credit remaining as fraction of total credit @ month-start"
    },
    {
     "expr": "(\n    (\n        sum(avg without(monetary) (grafanacloud_org_total_overage{org_id=\"$org_id\"}))\n        - (9999999999 * $is_customer_of_partner) >= 0\n    )\n    and day_of_month() == 1 and hour() == 0\n)\n",
     "legendFormat": "Billable Usage Cost"
    },
    {
     "expr": "(\n    (\n        sum(avg without(monetary) (grafanacloud_org_bill_credit_fraction{org_id=\"$org_id\"}))\n        - (2 * $is_customer_of_grafana) >= 0\n    )\n    and day_of_month() == 1 and hour() == 0\n)\n",
     "legendFormat": "Fraction of total credit used"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg without(monetary) (grafanacloud_org_metrics_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Current Metrics Usage Cost"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_metrics_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Current fraction of cost due to metrics"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_billable_series{org_id=\"$org_id\"}",
     "legendFormat": "Current Billable Metrics Series"
    }
   ]
  },
  {
   "title": "Total Billable Metrics Series",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_billable_series{org_id=\"$org_id\"}",
     "legendFormat": "Billable Series"
    },
    {
     "expr": "grafanacloud_org_metrics_included_series{org_id=\"$org_id\"}",
     "legendFormat": "Included Series"
    },
    {
     "expr": "max(grafanacloud_instance_billable_usage{org_id=\"$org_id\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_metrics_billable_series{org_id=\"$org_id\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_metrics_overage{org_id=\"$org_id\"}) * on (id) group_left(name) topk by(id) (1, grafanacloud_instance_info{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Additional Usage Amount - {{ name }}"
    },
    {
     "expr": "max(grafanacloud_instance_billable_usage{org_id=\"$org_id\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_metrics_billable_series{org_id=\"$org_id\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_metrics_bill_fraction{org_id=\"$org_id\"}) * on (id) group_left(name) topk by(id) (1, grafanacloud_instance_info{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction - {{ name }}"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_metrics_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_metrics_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 15 },
   "options": {
    "content": "## About Billable Metrics Series\n\nThis panel displays the 95th percentile of your active series and samples, or data points, per minute (DPM) for this month so far.\nYou can dig deeper into your daily ingestion rates, totals, and more in the **Metrics Ingestion Details** row directly below this panel.\n\nFor more information on cardinality and metrics usage, you can:\n\n- Learn to <a href=\"https://grafana.com/docs/grafana-cloud/metrics-control-usage/control-prometheus-metrics-usage/\" target=\"_blank\">Control Your Metrics Usage</a>\n- <a href=\"/d/cardinality-management\" target=\"_blank\">Locate your highest cardinality metrics</a> from your Cardinality Dashboards\n- <a href=\"/a/grafana-adaptive-metrics-app\" target=\"_blank\">Get started with our new Adaptive Metrics cost optimization tool</a>.\n"
   }
  },
  {
   "title": "Metrics Ingestion Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Active Series",
     "type": "timeseries",
     "description": "Shows:\n\n- Total active-series per managed Prometheus metrics service (GrafanaCloud Stack).\n- Active-series ingested in the Datadog format\n- Active-series ingested in the Influx format\n- Active-series per installed integration (with default job-name in Agent config)\n- Active-series generated by Asserts\n",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(grafanacloud_instance_active_series{id=~\"$metrics_id\"}) by (id) * on (id) group_left(name) topk by(id) (1, grafanacloud_instance_info{id=~\"$metrics_id\"})",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "max(grafanacloud_instance_active_datadog_series{id=~\"$metrics_id\"} > 0) by (id) * on (id) group_left(name) topk by(id) (1, grafanacloud_instance_info{id=~\"$metrics_id\"})",
       "legendFormat": "{{ name }}: Datadog format"
      },
      {
       "expr": "max(grafanacloud_instance_active_influx_series{id=~\"$metrics_id\"} > 0) by (id) * on (id) group_left(name) topk by(id) (1, grafanacloud_instance_info{id=~\"$metrics_id\"})",
       "legendFormat": "{{ name }}: Influx format"
      },
      {
       "expr": "max(grafanacloud_instance_active_integration_series{id=~\"$metrics_id\"}) by (id, integration) * on (id) group_left(name) topk by(id) (1, grafanacloud_instance_info{id=~\"$metrics_id\"})",
       "legendFormat": "{{name}}: {{integration}} intg."
      },
      {
       "expr": "max(grafanacloud_instance_active_asserts_series{id=~\"$metrics_id\"} > 0) by (id) * on (id) group_left(name) topk by(id) (1, grafanacloud_instance_info{id=~\"$metrics_id\"})",
       "legendFormat": "{{name}}: Asserts active series"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "options": {
      "content": "## About Metrics Active Series\n\nAn active series is a time series that receives new data points or samples. If you stop writing new datapoints to a time series, shortly afterwards it is no longer considered active. Learn more about <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/active-series-and-dpm/#active-series\" target=\"_blank\">Active Series</a>.\n\nYour Metrics Active Series panel graphs the total number of active series ingested to Grafana Cloud per push (scrape_interval) at a certain point in time. We recommend <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/optimize-scrape-interval/\" target=\"_blank\">setting that scrape_interval</a> to a resolution of once per minute (60s) to keep ingestion costs down. If you are sending series more frequently than once per minute, you will see this reflected in the rate of Data Points per Minute (DPM) in the two panel rows below.\n\n"
     }
    },
    {
     "title": "Highest Metrics DPM Stacks (top 3 stacks)",
     "type": "gauge",
     "description": "Shows up to 3 of your stacks, ordered by those with the greatest average DPM per active-series.\n\nThis value calculated at the current instant. ie. `now()`",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sort_desc(\n  max by(id, name) (\n    60 * grafanacloud_instance_samples_per_second{id=~\"$metrics_id\"}\n    / grafanacloud_instance_active_series{id=~\"$metrics_id\"}\n\n    * on(id) group_left(name) topk by (id) (1, grafanacloud_instance_info{id=~\"$metrics_id\"})\n  )\n)\n"
      },
      {
       "expr": "scalar(grafanacloud_org_metrics_included_dpm_per_series{org_id=\"$org_id\"})"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
     "options": {
      "content": "## About High DPM\n\nYour Highest Metrics DPM Stacks panel displays your top (or only) metrics ingestion instances and their current DPM (Data Points per Minute). Your plan has an included DPM rate, displayed numerically in green on the gauge panel. If you are sending metrics series at a rate per minute above that number (displayed center), you will see it metered in red. See the graph panel below for the active series ingestion per minute, over time.\n\nTo learn more about how this affects your billing, see: <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/active-series-and-dpm/\" target=\"_blank\">Active Series and DPM</a>. To control or change your DPM, check out: <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/changing-scrape-interval/\" target=\"_blank\">Changing your metrics scrape interval</a>.\n\n"
     }
    },
    {
     "title": "Metrics Active Series Ingestion Rate per Minute (DPM)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(grafanacloud_instance_samples_per_second{id=~\"$metrics_id\"} * 60) by (id) * on(id) group_left(name) topk by (id) (1, grafanacloud_instance_info{id=~\"$metrics_id\"})",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Discarded Metric Samples",
     "type": "timeseries",
     "description": "To learn more about these errors and their potential causes, refer to [Monitor Prometheus for ingest errors](https://grafana.com/docs/grafana-cloud/data-configuration/metrics/metrics-prometheus/errors-monitoring/).",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "si:/s" } },
     "targets": [
      {
       "expr": "sum(max(grafanacloud_instance_samples_discarded_per_second{id=~\"$metrics_id\"}) by (id, reason)) by (id, reason) * on(id) group_left(name) topk by (id) (1, grafanacloud_instance_info{id=~\"$metrics_id\"})",
       "legendFormat": "{{ name }} - {{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics Instance Usage Group Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active series per usage group",
     "type": "timeseries",
     "description": "The panel displays active series broken down by user-defined usage groups, and the number of active series not assigned to any group. This can be used for internal back-charging. Read the [documentation](https://grafana.com/docs/grafana-cloud/cost-management-and-billing/analyze-costs/metrics-costs/define-usage-groups/) to learn more about this feature.\n\nPlease contact support to get this set up.\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(grafanacloud_instance_active_usage_group_series{id=~\"$metrics_id\"}) by (id, group) * on (id) group_left(name) topk by(id) (1, grafanacloud_instance_info{id=~\"$metrics_id\"})",
       "legendFormat": "{{name}}: group {{group}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Graphite Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "avg without(monetary) (grafanacloud_org_graphite_metrics_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
       "legendFormat": "Current Graphite Metrics Cost"
      },
      {
       "expr": "avg without(monetary) (grafanacloud_org_graphite_metrics_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
       "legendFormat": "Current fraction of cost due to Graphite Metrics"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafanacloud_org_graphite_metrics_billable_series{org_id=\"$org_id\"}",
       "legendFormat": "Current Graphite Metrics Usage"
      }
     ]
    },
    {
     "title": "Total Billable Graphite Metrics Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 18, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafanacloud_org_graphite_metrics_billable_series{org_id=\"$org_id\"}",
       "legendFormat": "Billable Usage"
      },
      {
       "expr": "avg without(monetary) (grafanacloud_org_graphite_metrics_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
       "legendFormat": "Additional Usage Amount"
      },
      {
       "expr": "avg without(monetary) (grafanacloud_org_graphite_metrics_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
       "legendFormat": "Cost fraction"
      },
      {
       "expr": "grafanacloud_org_graphite_metrics_included_series{org_id=\"$org_id\"}",
       "legendFormat": "Included Graphite Series"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg without(monetary) (grafanacloud_org_logs_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Current Logs Usage Cost"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_logs_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Current fraction of cost due to Logs"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "grafanacloud_org_logs_usage{org_id=\"$org_id\"}",
     "legendFormat": "Current Billable Logs Usage"
    }
   ]
  },
  {
   "title": "Total Billable Logs Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "grafanacloud_org_logs_usage{org_id=\"$org_id\"}",
     "legendFormat": "Billable Usage"
    },
    {
     "expr": "grafanacloud_org_logs_included_usage{org_id=\"$org_id\"}",
     "legendFormat": "Included Usage"
    },
    {
     "expr": "max(grafanacloud_logs_instance_usage{org_id=\"$org_id\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage{org_id=\"$org_id\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_logs_overage{org_id=\"$org_id\"}) * on (id) group_left(name) topk by (id) (1, grafanacloud_logs_instance_info{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Total Additional Usage Amount - {{ name }}"
    },
    {
     "expr": "max(grafanacloud_logs_instance_query_overage{org_id=\"$org_id\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage{org_id=\"$org_id\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_logs_overage{org_id=\"$org_id\"}) * on (id) group_left(name) topk by (id) (1, grafanacloud_logs_instance_info{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Query Additional Usage Amount - {{ name }}"
    },
    {
     "expr": "max(grafanacloud_logs_instance_usage{org_id=\"$org_id\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage{org_id=\"$org_id\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_logs_bill_fraction{org_id=\"$org_id\"})* on (id) group_left(name) topk by (id) (1, grafanacloud_logs_instance_info{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction - {{ name }}"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_logs_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_logs_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 35 },
   "options": {
    "content": "## About Billable Logs\n\nYour **total billable logs usage** is calculated using the total number of ingested bytes generated by your logs for the entire month.\nYou may generate additional billable logs for log retention periods above 30 days, or logs query usage above 100x of ingested logs volume.\nYou can dig deeper into your daily ingestion rates, totals, and more in the **Logs Ingestion Details** row directly below this panel.\n\nFor more information on logs usage, see:\n\n- <a href=\"https://grafana.com/docs/grafana-cloud/cost-management-and-billing/understand-your-invoice/logs-invoice/\" target=\"_blank\">Understanding your Grafana Cloud Logs Invoice</a>\n- <a href=\"https://grafana.com/docs/grafana-cloud/cost-management-and-billing/analyze-costs/logs-costs/analyze-logs-costs-grafana-explore/\" target=\"_blank\">Analyze and Understand your Logs usage</a>\n"
   }
  },
  {
   "title": "Logs Ingestion and Query Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs Ingestion Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_logs_instance_bytes_received_per_second{id=~\"$logs_id\"}) by (id) * on(id) group_left(name) topk by (id) (1, grafanacloud_logs_instance_info{id=~\"$logs_id\"})",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Total Ingested Logs by day",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(sum_over_time((grafanacloud_logs_instance_bytes_received_per_second{id=~\"$logs_id\"} offset -1d * 60)[1d:1m])) by (id) * on(id) group_left(name) topk by (id) (1, grafanacloud_logs_instance_info{id=~\"$logs_id\"}) or vector(0)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Total Queried Logs by day",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(sum_over_time((grafanacloud_logs_instance_query_bytes:rate5m{id=~\"$logs_id\"} offset -1d * 60)[1d:1m])) by (id) * on(id) group_left(name) topk by (id) (1, grafanacloud_logs_instance_info{id=~\"$logs_id\"}) or vector(0)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Discarded Log Samples",
     "type": "timeseries",
     "description": "To learn more about these errors and dig into potential causes check out our Loki article on [Troubleshoot Cloud Logs write issues](https://grafana.com/docs/grafana-cloud/send-data/logs/troubleshoot/)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "si:/s" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_logs_instance_samples_discarded_per_second{id=~\"$logs_id\"}) by (id, reason) * on(id) group_left(name) topk by (id) (1, grafanacloud_logs_instance_info{id=~\"$logs_id\"})",
       "legendFormat": "{{ name }} - {{reason}}"
      }
     ]
    },
    {
     "title": "Logs Query Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_logs_instance_query_bytes:rate5m{id=~\"$logs_id\"}) by (id) * on(id) group_left(name) topk by (id) (1, grafanacloud_logs_instance_info{id=~\"$logs_id\"})",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Query Usage Ratio",
     "type": "bargauge",
     "description": "Shows the ratio of queried to ingested bytes over the selected time period on each of your stacks.",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "sort_desc(\n  sum_over_time(\n    sum by (id) (\n      grafanacloud_logs_instance_query_bytes:rate5m{id=~\"$logs_id\"}\n    ) [$__range:1m]\n  ) /\n  sum_over_time(\n    sum by (id) (\n      grafanacloud_logs_instance_billable_bytes_received_per_second{id=~\"$logs_id\"}\n    ) [$__range:1m]\n  )\n) * on(id) group_left(name) topk by (id) (1, grafanacloud_logs_instance_info{id=~\"$logs_id\"})\n",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "grafanacloud_org_logs_included_query_to_ingest_ratio{org_id=\"$org_id\"}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 73 },
     "options": {
      "content": "\"Query Usage Ratio\" shows the ratio of queried to ingested bytes on each of your stacks.\nIf this ratio exceeds the \"Query Fair Usage Ratio\" configured for your plan, you will incur additional charges.\n\n\nLearn more: <a href=\"https://grafana.com/docs/grafana-cloud/account-management/billing-and-usage/logs-billing/#fair-use-policy-for-gbs-queried\" target=\"_blank\">Fair use policy for GBs queried</a>\n"
     }
    },
    {
     "title": "Query Fair Use Ratio",
     "type": "stat",
     "description": "The query fair usage ratio configured for your current plan",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 77 },
     "targets": [
      {
       "expr": "grafanacloud_org_logs_included_query_to_ingest_ratio{org_id=\"$org_id\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs Retention Usage (Add-on)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "avg without(monetary) (grafanacloud_org_logs_retention_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
       "legendFormat": "Current Logs Retention Usage Cost"
      },
      {
       "expr": "avg without(monetary) (grafanacloud_org_logs_retention_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
       "legendFormat": "Current fraction of cost due to Logs Retention Usage"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "grafanacloud_org_logs_retention_usage{org_id=\"$org_id\"}",
       "legendFormat": "Current Billable Logs Retention Usage"
      }
     ]
    },
    {
     "title": "Total Billable Logs Retention Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 18, "x": 6, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "targets": [
      {
       "expr": "grafanacloud_org_logs_retention_usage{org_id=\"$org_id\"}",
       "legendFormat": "Billable Usage"
      },
      {
       "expr": "avg without(monetary) (grafanacloud_org_logs_retention_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
       "legendFormat": "Additional Usage Amount"
      },
      {
       "expr": "avg without(monetary) (grafanacloud_org_logs_retention_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
       "legendFormat": "Cost fraction"
      },
      {
       "expr": "grafanacloud_org_logs_retention_included_usage{org_id=\"$org_id\"}",
       "legendFormat": "Included Usage"
      },
      {
       "expr": "max(grafanacloud_logs_instance_retention_usage{org_id=\"$org_id\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_retention_usage{org_id=\"$org_id\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_logs_retention_overage{org_id=\"$org_id\"}) * on (id) group_left(name) topk by (id) (1, grafanacloud_logs_instance_info{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
       "legendFormat": "Additional Usage Amount - {{ name }}"
      },
      {
       "expr": "max(grafanacloud_logs_instance_retention_usage{org_id=\"$org_id\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_retention_usage{org_id=\"$org_id\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_logs_retention_bill_fraction{org_id=\"$org_id\"}) * on (id) group_left(name) topk by (id) (1, grafanacloud_logs_instance_info{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
       "legendFormat": "Cost fraction - {{ name }}"
      }
     ]
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg without(monetary) (grafanacloud_org_traces_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Current Traces Usage Cost"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_traces_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Current fraction of cost due to Traces"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "grafanacloud_org_traces_usage{org_id=\"$org_id\"}",
     "legendFormat": "Current Billable Traces Usage"
    }
   ]
  },
  {
   "title": "Total Billable Traces Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "grafanacloud_org_traces_usage{org_id=\"$org_id\"}",
     "legendFormat": "Billable Usage"
    },
    {
     "expr": "grafanacloud_org_traces_included_usage{org_id=\"$org_id\"}",
     "legendFormat": "Included Usage"
    },
    {
     "expr": "max(grafanacloud_traces_instance_usage{org_id=\"$org_id\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_traces_usage{org_id=\"$org_id\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_traces_overage{org_id=\"$org_id\"}) * on (id) group_left(name) topk by (id) (1, grafanacloud_traces_instance_info{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Additional Usage Amount - {{ name }}"
    },
    {
     "expr": "max(grafanacloud_traces_instance_usage{org_id=\"$org_id\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_traces_usage{org_id=\"$org_id\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_traces_bill_fraction{org_id=\"$org_id\"}) * on (id) group_left(name) topk by (id) (1, grafanacloud_traces_instance_info{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction - {{ name }}"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_traces_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_traces_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 55 },
   "options": {
    "content": "## About Billable Traces\n\nYour **total billable traces usage** is calculated using the total number of ingested bytes generated by your traces this month.\n\nYou can dig deeper into your daily ingestion rates, totals, and more by expanding the **Traces Ingestion Details** row directly below this panel.\n\nFor a guide on traces usage management: <a href=\"https://grafana.com/docs/grafana-cloud/cost-management-and-billing/reduce-costs/traces-costs/\" target=\"_blank\">Reduce Grafana Cloud Traces cost</a>.\n"
   }
  },
  {
   "title": "Traces Ingestion Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traces Ingestion Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_traces_instance_bytes_received_per_second{id=~\"$traces_id\"}) by (id) * on(id) group_left(name) topk by (id) (1, grafanacloud_traces_instance_info{id=~\"$traces_id\"})",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Total Ingested Traces by day",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(sum_over_time((grafanacloud_traces_instance_bytes_received_per_second{id=~\"$traces_id\"} offset -1d * 60)[1d:1m])) by (id) * on(id) group_left(name) topk by (id) (1, grafanacloud_traces_instance_info{id=~\"$traces_id\"}) or vector(0)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Discarded Spans",
     "type": "timeseries",
     "description": "To learn more about why spans were discarded, refer to the [Discarded Spans](https://grafana.com/docs/grafana-cloud/cost-management-and-billing/understand-your-invoice/usage-limits/#discarded-spans-panel-in-the-billing-dashboard) metric definitions.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "si:/s" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_traces_instance_discarded_spans_total:rate5m{id=~\"$traces_id\"}) by (id, reason) * on(id) group_left(name) topk by (id) (1, grafanacloud_traces_instance_info{id=~\"$traces_id\"})",
       "legendFormat": "{{ name }} - {{reason}}"
      }
     ]
    }
   ]
  },
  { "title": "Grafana Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg without(monetary) (grafanacloud_org_grafana_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Current Grafana Users Cost"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_grafana_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Current fraction of cost due to Grafana Users"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_grafana_billable_users{org_id=\"$org_id\"}",
     "legendFormat": "Total Unique Users"
    },
    {
     "expr": "grafanacloud_org_billable_users_grafana{org_id=\"$org_id\"} and grafanacloud_org_billable_users_oncall{org_id=\"$org_id\"} > 0",
     "legendFormat": "Grafana Users"
    },
    {
     "expr": "grafanacloud_org_billable_users_oncall{org_id=\"$org_id\"} > 0",
     "legendFormat": "OnCall Users"
    }
   ]
  },
  {
   "title": "Total Billable Grafana Users Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_grafana_billable_users{org_id=\"$org_id\"}",
     "legendFormat": "Billable Users"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_grafana_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_grafana_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction"
    },
    {
     "expr": "grafanacloud_org_grafana_included_users{org_id=\"$org_id\"}",
     "legendFormat": "Included Users"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 88 },
   "options": {
    "content": "## About Billable Users\n\nYour **total billable grafana users** is determined by all <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/#billing-for-active-users\" target=\"_blank\">monthly active Grafana users</a> and their associated costs. Active users are only billed once per month across all your stacks.\n\nYou can dig deeper in the **Grafana Users Usage Details** row directly below this panel.\nFor additional per user costs generated from an Enterprise plugin add-on, expand the **Enterprise Plugin Add-On** row.\n"
   }
  },
  {
   "title": "Grafana Users Usage Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Grafana Users (last 30 days)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum(grafanacloud_grafana_instance_active_user_count{id=~\"$grafana_id\"}) by (id) * on(id) group_left(name) topk by (id) (1, grafanacloud_grafana_instance_info{id=~\"$grafana_id\"})) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Enterprise Plugin Usage (Add-on)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "avg without(monetary) (grafanacloud_org_grafana_plugin_users_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
       "legendFormat": "Current Additional Enterprise Plugin Cost"
      },
      {
       "expr": "avg without(monetary) (grafanacloud_org_grafana_plugin_users_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
       "legendFormat": "Current fraction of cost due to Additional Enterprise Plugin"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafanacloud_org_grafana_plugin_users{org_id=\"$org_id\"}",
       "legendFormat": "Current Billable Enterprise Plugin Users"
      }
     ]
    },
    {
     "title": "Billable Enterprise Plugin Users",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 6, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafanacloud_org_grafana_plugin_users{org_id=\"$org_id\"}",
       "legendFormat": "Billable Users"
      },
      {
       "expr": "avg without(monetary) (grafanacloud_org_grafana_plugin_users_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
       "legendFormat": "Additional Usage Amount"
      },
      {
       "expr": "avg without(monetary) (grafanacloud_org_grafana_plugin_users_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
       "legendFormat": "Cost fraction"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 113 },
     "options": {
      "content": "## About Enterprise Plugins\n\nUnder the Pro monthly subscription plan it is possible to add a single (1) Grafana Enterprise Plugin for use across your account. Once added, this comes at an additional cost of <a href=\"https://grafana.com/docs/grafana-cloud/billing-and-usage/#billing-for-active-users\" target=\"_blank\">$25 per Grafana active user</a>.\n\nIf you've added an Enterprise plugin, your Billable Enterprise Plugin Users panels displays your total number of Grafana active users and the additional aggregated cost at $25/user, this month so far.\n"
     }
    }
   ]
  },
  {
   "title": "Incident Response & Management (IRM) Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg without(monetary) (grafanacloud_org_irm_users_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Current IRM Users Usage Cost"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_irm_users_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Current fraction of cost due to IRM Users Usage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_irm_users{org_id=\"$org_id\"}",
     "legendFormat": "Current Billable IRM Users"
    }
   ]
  },
  {
   "title": "Total Billable IRM Users",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_irm_users{org_id=\"$org_id\"}",
     "legendFormat": "Billable Users"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_irm_users_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Additional User Amount"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_irm_users_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction"
    },
    {
     "expr": "grafanacloud_org_irm_included_users{org_id=\"$org_id\"}",
     "legendFormat": "Included Users"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 126 },
   "options": {
    "content": "## About IRM Users\n\nYour Total Billable IRM Users panel reflects all active users of IRM services this month. A user is <a href=\"https://grafana.com/docs/grafana-cloud/account-management/billing-and-usage/irm-billing/\" target=\"_blank\">considered active</a> if they are included in OnCall schedules or escalation chains, or if they perform any of the actions below:\n- Changed status of alert group or OnCall configuration\n- Got paged or paged someone\n- Created, declared, edited, updated, or deleted an Incident\n"
   }
  },
  {
   "title": "IRM Users Usage Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Grafana IRM Users per stack (last 30 days)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum(grafanacloud_irm_active_user_count{id=~\"$grafana_id\"}) by (id) * on(id) group_left(name) topk by (id) (1, grafanacloud_grafana_instance_info{id=~\"$grafana_id\"})) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 131 },
     "options": {
      "content": "## About Active IRM Users per Stack\n\nThis panel displays the total number of <a href=\"https://grafana.com/docs/grafana-cloud/account-management/billing-and-usage/irm-billing/\" target=\"_blank\">active</a>\nusers of IRM services per stack over the last 30 days.\nNote that an active IRM user in two or more stacks is counted only once for billing purposes.\n\n"
     }
    }
   ]
  },
  {
   "title": "Kubernetes Monitoring Host Hours Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg without(monetary) (grafanacloud_org_infra_o11y_host_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Current Kubernetes Monitoring Host Cost"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_infra_o11y_host_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Current fraction of cost due to Kubernetes Monitoring Hosts"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_infra_o11y_billable_host_hours{org_id=\"$org_id\"}",
     "legendFormat": "Current Kubernetes Monitoring Host Hours"
    }
   ]
  },
  {
   "title": "Total Billable Kubernetes Monitoring Host Hours",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_infra_o11y_billable_host_hours{org_id=\"$org_id\"}",
     "legendFormat": "Billable Host Hours"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_infra_o11y_host_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_infra_o11y_host_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction"
    },
    {
     "expr": "grafanacloud_org_infra_o11y_included_host_hours{org_id=\"$org_id\"}",
     "legendFormat": "Included Host Hours"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 148 },
   "options": {
    "content": "## About Kubernetes Monitoring Host Hours\nYour Kubernetes Monitoring Host Usage is calculated from the total number of host hours this month.\n\n* <a href=\"https://grafana.com/docs/grafana-cloud/cost-management-and-billing/understand-your-invoice/kubernetes-monitoring-invoice/\" target=\"_blank\">Understand your Grafana Cloud Kubernetes Monitoring invoice</a>\n"
   }
  },
  {
   "title": "Kubernetes Monitoring Container Hours Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg without(monetary) (grafanacloud_org_infra_o11y_container_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Current Kubernetes Monitoring Container Cost"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_infra_o11y_container_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Current fraction of cost due to Kubernetes Monitoring Container"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_infra_o11y_billable_container_hours{org_id=\"$org_id\"}",
     "legendFormat": "Current Kubernetes Monitoring Container Hours"
    }
   ]
  },
  {
   "title": "Total Billable Kubernetes Monitoring Container Hours",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_infra_o11y_billable_container_hours{org_id=\"$org_id\"}",
     "legendFormat": "Billable Container Hours"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_infra_o11y_container_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_infra_o11y_container_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction"
    },
    {
     "expr": "grafanacloud_org_infra_o11y_included_container_hours{org_id=\"$org_id\"}",
     "legendFormat": "Included Container Hours"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 168 },
   "options": {
    "content": "## About Kubernetes Monitoring Container Hours Usage\nYour Kubernetes Monitoring Container Usage is calculated from the total number of container hours this month.\n\n* <a href=\"https://grafana.com/docs/grafana-cloud/cost-management-and-billing/understand-your-invoice/kubernetes-monitoring-invoice/\" target=\"_blank\">Understand your Grafana Cloud Kubernetes Monitoring invoice</a>\n"
   }
  },
  { "title": "k6 Virtual User Hours (VUh)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 175 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg without(monetary) (grafanacloud_org_k6_virtual_user_hours_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Current VUh Usage Cost"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_k6_virtual_user_hours_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Current fraction of cost due to VUh Usage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "VUh" } },
   "targets": [
    {
     "expr": "grafanacloud_org_k6_virtual_user_hours_usage{org_id=\"$org_id\"}",
     "legendFormat": "Current Billable VUh Usage"
    }
   ]
  },
  {
   "title": "Total Billable Virtual User Hours (VUh)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "VUh" } },
   "targets": [
    {
     "expr": "grafanacloud_org_k6_virtual_user_hours_usage{org_id=\"$org_id\"}",
     "legendFormat": "Billable Usage"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_k6_virtual_user_hours_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_k6_virtual_user_hours_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction"
    },
    {
     "expr": "grafanacloud_org_k6_virtual_user_hours_included_usage{org_id=\"$org_id\"}",
     "legendFormat": "Included Usage"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 180 },
   "options": {
    "content": "## About k6 Virtual User Hours\n\nYour Total k6 Billable Usage is based on Virtual User hours (VUh) used during your load tests. The Pro and Advanced plans include 1000 VUh/month with 30 day data retention for your test results.\n\nYou can dig deeper into the kind of k6 usage generating billable VUh in the k6 Virtual User Hours (VUh) Details row directly below this panel.\n\nFor information on how we calculate VUh, and the differences between Protocol VU and Browser VU, please visit our <a href=\"https://grafana.com/docs/grafana-cloud/k6/get-started/vu-hours/\" target=\"_blank\">documentation</a>.\n"
   }
  },
  {
   "title": "k6 Virtual User Hours (VUh) Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 193 },
   "collapsed": true,
   "panels": [
    {
     "title": "k6 Virtual User Hours (VUh) usage by stacks and type",
     "type": "timeseries",
     "description": "This panel displays VUh broken down to stacks, type protocol and browser.\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "VUh" } },
     "targets": [
      {
       "expr": "max(grafanacloud_k6_stack_virtual_user_hours_usage{org_id=\"$org_id\"}) by (id,vuh_type) *  on(id) group_left(slug) topk by(id)(1, grafanacloud_grafana_instance_info{org_id=\"$org_id\"})",
       "legendFormat": "Additional Usage Amount - {{ slug }}:{{ vuh_type}}"
      }
     ]
    }
   ]
  },
  { "title": "Profiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg without(monetary) (grafanacloud_org_profiles_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Current Profiles Usage Cost"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_profiles_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Current fraction of cost due to Profiles Usage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 218 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "grafanacloud_org_profiles_usage{org_id=\"$org_id\"}",
     "legendFormat": "Current Billable Profiles Usage"
    }
   ]
  },
  {
   "title": "Total Billable Profiles Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "grafanacloud_org_profiles_usage{org_id=\"$org_id\"}",
     "legendFormat": "Billable Usage"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_profiles_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_profiles_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction"
    },
    {
     "expr": "grafanacloud_org_profiles_included_usage{org_id=\"$org_id\"}",
     "legendFormat": "Included Usage"
    },
    {
     "expr": "max(grafanacloud_profiles_instance_usage{org_id=\"$org_id\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_profiles_usage{org_id=\"$org_id\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_profiles_overage{org_id=\"$org_id\"}) * on (id) group_left(name) topk by(id)(1, grafanacloud_profiles_instance_info{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Additional Usage Amount - {{ name }}"
    },
    {
     "expr": "max(grafanacloud_profiles_instance_usage{org_id=\"$org_id\"}) by (id) / ignoring(id) group_left() max(grafanacloud_org_profiles_usage{org_id=\"$org_id\"}) by (id) * ignoring(id,org_id,cluster) group_left() avg without(monetary) (grafanacloud_org_profiles_bill_fraction{org_id=\"$org_id\"})  * on (id) group_left(name) topk by(id)(1, grafanacloud_profiles_instance_info{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction - {{ name }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 213 },
   "options": {
    "content": "## About Billable Profiles\n\nYour Total Billable Profiles Usage is calculated on the total number\nof ingested bytes generated by your profiles this month. Usage of\nGrafana Cloud Profiles is subject to <a\nhref=\"https://www.grafana.com/pricing\" target=\"_blank\">Grafana Cloud\nPricing</a> for Profiles.\n\n* <a href=\"https://grafana.com/docs/grafana-cloud/monitor-applications/profiles/\" target=\"_blank\">About Grafana Cloud Continuous Profiling</a>\n* <a href=\"https://grafana.com/blog/2023/08/09/grafana-cloud-profiles-for-continuous-profiling/\" target=\"_blank\">Blog: Unify your Observability signals with Grafana Cloud Profiles</a>\n\nYou can dig deeper into your daily ingestion rates, totals, and more in the **Profiles Ingestion Details** row directly below this panel.\n"
   }
  },
  {
   "title": "Profile Ingestion Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 218 },
   "collapsed": true,
   "panels": [
    {
     "title": "Profiles Ingestion Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 223 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_profiles_instance_bytes_received_per_second{id=~\"$profiles_id\"}) by (id) * on(id) group_left(name) topk by(id)(1, grafanacloud_profiles_instance_info{id=~\"$profiles_id\"})",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Total Ingested Profiles by day",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 239 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(sum_over_time((grafanacloud_profiles_instance_bytes_received_per_second{id=~\"$profiles_id\"}  offset -1d * 60)[1d:1m])) by (id) * on(id) group_left(name) topk by(id)(1, grafanacloud_profiles_instance_info{id=~\"$profiles_id\"}) or vector(0)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Discarded Profiles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 247 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_profiles_instance_discarded_bytes_per_second{id=~\"$profiles_id\"}) by (id, reason) * on(id) group_left(name) topk by(id)(1, grafanacloud_profiles_instance_info{id=~\"$profiles_id\"})",
       "legendFormat": "{{ name }} - {{reason}}"
      }
     ]
    },
    {
     "title": "Profiles Estimated Ingestion Rate by usage group",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 255 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_profiles_instance_usage_group_estimated_billable_bytes_received_per_second{id=~\"$profiles_id\"}) by (id, usage_group) * on(id) group_left(name) topk by(id)(1, grafanacloud_profiles_instance_info{id=~\"$profiles_id\"})",
       "legendFormat": "{{ name }} - {{ usage_group }}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 255 },
     "options": {
      "content": "## About Usage Groups\n\nUsage groups provide a mechanism to break down billable usage by\ndifferent attributes (for example, by application). The values provided\nby this panel are not exact down to the byte, nor are billable bytes\ncalculated from this data, rather these values are best-effort\nestimates.\n\nUsage groups are not self serve. To configure your usage groups,\nplease contact Grafana Labs Support.\n"
     }
    }
   ]
  },
  { "title": "Frontend Observability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 230 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 238 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg without(monetary) (grafanacloud_org_fe_o11y_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Current Frontend Observability Cost"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_fe_o11y_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Current fraction of cost due to Frontend Observability"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 243 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_fe_o11y_billable_sessions{org_id=\"$org_id\"}",
     "legendFormat": "Current Frontend Observability Sessions"
    }
   ]
  },
  {
   "title": "Total Billable Frontend Observability Sessions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 238 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_fe_o11y_billable_sessions{org_id=\"$org_id\"}",
     "legendFormat": "Billable Sessions"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_fe_o11y_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_fe_o11y_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction"
    },
    {
     "expr": "grafanacloud_org_fe_o11y_included_sessions{org_id=\"$org_id\"}",
     "legendFormat": "Included Sessions"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 238 },
   "options": {
    "content": "## About Frontend Observability\n\nYour Frontend Observability Usage is calculated from the total number of ingested sessions this month.\n\nYou can dig deeper into your daily ingestion rates, totals, and more in the **Frontend Observability Details** tab in the **Usage Drilldown** section at the bottom of this view.\n"
   }
  },
  {
   "title": "Frontend Observability Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 248 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sessions Ingestion Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 250 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(grafanacloud_frontend_observability_instance_sessions_per_second{org_id=\"$org_id\"}) by (id, appName)",
       "legendFormat": "{{ appName }}"
      }
     ]
    },
    {
     "title": "Total Sessions Ingested by day",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 266 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum_over_time((grafanacloud_frontend_observability_instance_sessions_per_second{org_id=\"$org_id\"} * 60)[1d:1m])) by (id, appName) or vector(0)",
       "legendFormat": "{{ appName }}"
      }
     ]
    }
   ]
  },
  { "title": "Application Observability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 258 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 264 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg without(monetary) (grafanacloud_org_app_o11y_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Current Application Observability Cost"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_app_o11y_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Current fraction of cost due to Application Observability"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 269 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_app_o11y_billable_host_hours{org_id=\"$org_id\"}",
     "legendFormat": "Current Application Observability Host Hours"
    }
   ]
  },
  {
   "title": "Total Billable Application Observability Host Hours",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 264 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_app_o11y_billable_host_hours{org_id=\"$org_id\"}",
     "legendFormat": "Billable Host Hours"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_app_o11y_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_app_o11y_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction"
    },
    {
     "expr": "grafanacloud_org_app_o11y_included_host_hours{org_id=\"$org_id\"}",
     "legendFormat": "Included Host Hours"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 264 },
   "options": {
    "content": "## About Application Observability\n\nYour Application Observability Usage is calculated from the total number of host hours this month.\n\n"
   }
  },
  { "title": "Synthetics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 270 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 278 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg without(monetary) (grafanacloud_org_sm_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Current Synthetics Cost"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_sm_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Current fraction of cost due to Synthetics"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 283 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_sm_billable_check_executions{org_id=\"$org_id\"}",
     "legendFormat": "Current Synthetics Test Executions"
    }
   ]
  },
  {
   "title": "Total Billable Synthetics Test Executions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 278 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_sm_billable_check_executions{org_id=\"$org_id\"}",
     "legendFormat": "Billable Usage"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_sm_overage{org_id=\"$org_id\"})- (9999999999 * $is_customer_of_partner) >= 0",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "avg without(monetary) (grafanacloud_org_sm_bill_fraction{org_id=\"$org_id\"})- (2 * $is_customer_of_grafana) >= 0",
     "legendFormat": "Cost fraction"
    },
    {
     "expr": "grafanacloud_org_sm_included_check_executions{org_id=\"$org_id\"}",
     "legendFormat": "Included Test Executions"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 278 },
   "options": {
    "content": "## About Synthetics\nYour Synthetics Usage is calculated from the total number of test executions this month.\n"
   }
  },
  {
   "title": "Synthetic Monitoring Usage Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 290 },
   "collapsed": true,
   "panels": [
    {
     "title": "Synthetics Test Execution Rate (executions/second)",
     "type": "timeseries",
     "description": "Shows the 1 hour average rate of tests executed per second by check class\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "exec/s" } },
     "targets": [
      {
       "expr": "sum(\n  label_replace(\n    label_replace(\n      avg_over_time(grafanacloud_sm_billable_check_executions_per_second{org_id=\"$org_id\"}[1h]),\n      \"class\", \"protocol\", \"check_class\", \"(protocol|scripted)\"\n    ), \"class\", \"browser\", \"check_class\", \"browser\"\n  )\n) by(class)\n",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Synthetics Test Executions per day by check class",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 298 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  label_replace(\n    label_replace(\n      sum_over_time((grafanacloud_sm_billable_check_executions_per_second{org_id=\"$org_id\"} offset -1d * 60 )[1d:1m]),\n      \"class\", \"protocol\", \"check_class\", \"(protocol|scripted)\"\n    ), \"class\", \"browser\", \"check_class\", \"browser\"\n  )\n) by(class)\n",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Synthetics Test Executions per day by stack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 306 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  sum_over_time(\n    (grafanacloud_sm_billable_check_executions_per_second{org_id=\"$org_id\"} offset -1d * 60 )[1d:1m])\n  ) by (id) * on(id) group_left(name) topk by (id) (1,grafanacloud_grafana_instance_info{id=~\"$grafana_id\"})\n",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 368 },
   "options": {
    "content": "<div style=\"vertical-align: top; border: 0px;\"\"><p style=\"text-align: center; font-size: 115%; padding: 0px; margin: 0px;\"><b>Looking for the drilldown of your Usage Details? We moved these further up. You can find them directly below their corresponding Product Usage panels. They are collapsed by default and available to expand, just as before.</b></p></div>"
   }
  }
 ]
}