{
 "title": "Ingestion Rate Usage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metricInstance",
    "label": "Metric Instance",
    "query": {
     "query": "query_result(grafanacloud_instance_info and on (id) grafanacloud_instance_metrics_limits)"
    }
   },
   {
    "name": "logInstance",
    "label": "Log Instance",
    "query": {
     "query": "query_result(grafanacloud_logs_instance_info and on (id) grafanacloud_logs_instance_limits)"
    }
   },
   {
    "name": "traceInstance",
    "label": "Trace Instance",
    "query": {
     "query": "query_result(grafanacloud_traces_instance_info and on (id) grafanacloud_traces_instance_limits)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$metricInstance Metric Ingestion Rate Limit",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafanacloud_instance_metrics_limits{limit_name=\"ingestion_rate\", id=\"$metricInstance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "grafanacloud_instance_samples_per_second{id=\"$metricInstance\"}",
     "legendFormat": "Current Rate"
    },
    {
     "expr": "grafanacloud_instance_metrics_limits{limit_name=\"ingestion_rate\", id=\"$metricInstance\"}",
     "legendFormat": "Ingestion Limit"
    }
   ]
  },
  {
   "title": "$logInstance Log Ingestion Rate Limit",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafanacloud_logs_instance_limits{limit_name=\"ingestion_rate_mb\", id=\"$logInstance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "grafanacloud_logs_instance_bytes_received_per_second{id=\"$logInstance\"} / 1048576",
     "legendFormat": "Current Rate"
    },
    {
     "expr": "grafanacloud_logs_instance_limits{limit_name=\"ingestion_rate_mb\", id=\"$logInstance\"}",
     "legendFormat": "Ingestion Limit"
    }
   ]
  },
  {
   "title": "$traceInstance Trace Ingestion Rate Limit",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafanacloud_traces_instance_limits{limit_name=\"ingestion_rate_limit_bytes\", id=\"$traceInstance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "grafanacloud_traces_instance_bytes_received_per_second{id=\"$traceInstance\"}",
     "legendFormat": "Current Rate"
    },
    {
     "expr": "grafanacloud_traces_instance_limits{limit_name=\"ingestion_rate_limit_bytes\", id=\"$traceInstance\"}",
     "legendFormat": "Ingestion Limit"
    }
   ]
  }
 ]
}