{
 "title": "Usage Insights - 3 - Query Errors",
 "description": "A dashboard for visualizing and analyzing query errors.",
 "tags": [ "grafanacloud" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "search", "label": "Search" },
   {
    "name": "category",
    "label": "Error Category",
    "query": "other,invalid query,query too large,server error,authN/authZ,timeout,too many requests,query cancelled,missing resource"
   }
  ]
 },
 "panels": [
  {
   "title": "How to use this dashboard",
   "type": "text",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "**About:** This dashboard exists to help you find and understand errors occuring during data requests. \n\n**Search:** The search box above looks at the entire log line, and supports [some regex](https://grafana.com/docs/loki/latest/logql/log_queries/#log-stream-selector).\nTry searching for things like username, data source, or HTTP status code.\n\n**Categories:** The categories here are derived from common errors seen in various data sources. Use 'Explore' from the panel menu to see how we've achieved this. Save a copy of this dashboard so you can make edits and add your own categories.\n\n**Diving in:** The logs panel to the right is similar to what you'll find on the explore page. Click on the \"Explore Logs\" link if you'd like to interact with them there. Note that the category label won't be available in Explore.\n"
   }
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "{instance_type=\"grafana\"} |= \"eventName=data-request\" |~ \"error=\\\".+\\\"\" |~ \"$search\"\n    # pop out error into error field and only look at those lines\n    | regexp `error=\"(?P<rawError>.+)\"`\n    \n    # trim trimmy trim\n    | label_format errorStr=`{{ regexReplaceAll \"^ | $\" .rawError \"\" }}`\n    | label_format errorStr=`{{ regexReplaceAll \"[ ]+\" .errorStr \" \" }}`\n    \n    # todo: maybe not so many labels\n    # backslashes and newlines make regex hurt even more\n    | label_format error=`{{ replace \"\\\\n\" \" \" .errorStr | lower }}`\n    | label_format error=`{{ regexReplaceAll \"[\\\\\\\\]\" .error \"\" }}`\n    | label_format error=`{{ regexReplaceAll \"^ | $\" .error \"\" }}`   \n    \n    # scrub URIs and TCP addresses\n    | label_format error=`{{ regexReplaceAll \"\\\"http[s|]://.+\\\"\" .error \"URI\"}}` \n    | label_format error=`{{ regexReplaceAll \"tcp .+:\" .error \"TCP\" }}`\n    \n    # categorize\n    | label_format errorClass=`{{ \"other\" }}`\n    \n    # timeouts\n    | label_format errorClass=`{{ if contains \"timeout\" .error }}{{\"timeout\"}}{{else}}{{.errorClass}}{{end}}`\n    \n    # invalid query\n    | label_format errorClass=`{{ if contains \"invalidquery\" .error }}{{\"invalid query\"}}{{else}}{{.errorClass}}{{end}}`\n    | label_format errorClass=`{{ if contains \"parse error\" .error }}{{\"invalid query\"}}{{else}}{{.errorClass}}{{end}}`\n    | label_format errorClass=`{{ if contains \"unsupported protocol scheme\" .error }}{{\"invalid query\"}}{{else}}{{.errorClass}}{{end}}`\n\n    # errors from aggregated metrics\n    | label_format errorClass=`{{ if contains \"execution: can't query aggregated metric\" .error }}{{\"aggregation\"}}{{else}}{{.errorClass}}{{end}}`\n    \n    # too much data requested by query\n    | label_format errorClass=`{{ if contains \"maximum of series\" .error }}{{\"query too large\"}}{{else}}{{.errorClass}}{{end}}`\n    | label_format errorClass=`{{ if contains \"too many samples\" .error }}{{\"query too large\"}}{{else}}{{.errorClass}}{{end}}`\n    | label_format errorClass=`{{ if contains \"number of chunks\" .error }}{{\"query too large\"}}{{else}}{{.errorClass}}{{end}}`\n    | label_format errorClass=`{{ if contains \"exceeds max-points-per-req-hard limit\" .error }}{{\"query too large\"}}{{else}}{{.errorClass}}{{end}}`\n    | label_format errorClass=`{{ if contains \"query time range exceeds the limit\" .error }}{{\"query too large\"}}{{else}}{{.errorClass}}{{end}}`\n    \n    # too many requests\n    | label_format errorClass=`{{ if contains \"too many outstanding requests\" .error }}{{\"too many requests\"}}{{else}}{{.errorClass}}{{end}}`\n    \n    # server errors\n    | label_format errorClass=`{{ if contains \"server error\" .error }}{{\"server error\"}}{{else}}{{.errorClass}}{{end}}`\n    | label_format errorClass=`{{ if contains \"500\" .error }}{{\"server error\"}}{{else}}{{.errorClass}}{{end}}`\n    | label_format errorClass=`{{ if contains \"502\" .error }}{{\"server error\"}}{{else}}{{.errorClass}}{{end}}`\n    | label_format errorClass=`{{ if contains \"503\" .error }}{{\"server error\"}}{{else}}{{.errorClass}}{{end}}`\n    \n    # missing data\n    | label_format errorClass=`{{ if contains \"404\" .error }}{{\"missing resource\"}}{{else}}{{.errorClass}}{{end}}`\n    | label_format errorClass=`{{ if contains \"not found\" .error }}{{\"missing resource\"}}{{else}}{{.errorClass}}{{end}}`\n    | label_format errorClass=`{{ if contains \"no such host\" .error }}{{\"missing resource\"}}{{else}}{{.errorClass}}{{end}}`\n    \n    # authN/authZ\n    | label_format errorClass=`{{ if contains \"401\" .error }}{{\"authN/authZ\"}}{{else}}{{.errorClass}}{{end}}`\n    | label_format errorClass=`{{ if contains \"403\" .error }}{{\"authN/authZ\"}}{{else}}{{.errorClass}}{{end}}`\n    | label_format errorClass=`{{ if contains \"unauthorized\" .error }}{{\"authN/authZ\"}}{{else}}{{.errorClass}}{{end}}`\n    | label_format errorClass=`{{ if contains \"access denied\" .error }}{{\"authN/authZ\"}}{{else}}{{.errorClass}}{{end}}`\n    \n    # aborted requests\n    | label_format errorClass=`{{ if contains \"query error: -1 request was aborted\" .error }}{{\"query cancelled\"}}{{else}}{{.errorClass}}{{end}}`\n    \n    # logfmt the line so this panel is rich\n    | logfmt\n    | label_format level=\"err\"\n    \n    # scrub the line now\n    | line_format `category=\"{{.errorClass}}\", message=\"{{.errorStr}}\"`\n    \n    # since this query is huge and we don't want to be doing it multiple times, this allows for some convenience in the time series categories panel\n    | label_format hour=`{{.t | substr 0 14}}00`    \n    \n    # finally, filter\n    | errorClass=~\"$category\"",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Log Lines per Error Category",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Error Categories per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 6, "y": 11 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Error Messages",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 11 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "topk(10, sum by (username) (count_over_time({instance_type=\"grafana\"} |= \"data-request\" |~ `error=\".+\"` |~ \"$search\" | regexp `username=(?P<username>[^ ]+ )` [$__range])))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Dashboards",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "topk(20, sum by (dashboardName, folderName) (\n    count_over_time({instance_type=\"grafana\"} \n        |= \"data-request\" |~ `error=\".+\"` |~ \"$search\" != \"dashboardId=0\"\n        | regexp `folderName=(?P<folderName>.+) dashboardName=(?P<dashboardName>.+) dashboardId=`\n        | label_format dashboardName=`{{replace \"\\\"\" \"\" .dashboardName}}`\n        | label_format folderName=`{{replace \"\\\"\" \"\" .folderName}}`\n[$__range])))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Data Sources",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "topk(10, sum by (name, id) (\n    count_over_time({instance_type=\"grafana\"} \n        |= \"data-request\" |~ `error=\".+\"` |~ \"$search\" !=\"-- Mixed --\" != \"-- Grafana --\"\n        | regexp `datasourceName=(?P<name>.+) datasourceId=(?P<id>.+) datasourceType=(?P<type>.+)`\n        | label_format name=`{{replace \"\\\"\" \"\" .name}}`\n[$__range])))",
     "legendFormat": "{{username}}"
    }
   ]
  }
 ]
}