{
 "title": "Usage Insights - 6 - Loki Query Fair Usage Drilldown",
 "description": "This dashboard exists to help identify queries that are heavy hitters relative to your Query Fair Usage Ratio.",
 "tags": [ "grafanacloud" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "usageInsightsDS", "label": "Usage Insights Logs", "query": "loki" },
   { "name": "metricsUsageDatasource", "label": "Usage (metrics) Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {}
   },
   {
    "name": "orgID",
    "label": "orgID",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "query bytes breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\" | source!~\"grafana-alert|grafana-lokiexplore-app\"| dashboard_id=\"\" | unwrap bytes(total_bytes) [$__range]))",
     "legendFormat": "explore/other"
    },
    {
     "expr": "sum(sum_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source!=\"grafana-alert\"| dashboard_id!=\"\" | unwrap bytes(total_bytes)[$__range]))",
     "legendFormat": "dashboards"
    },
    {
     "expr": "sum(sum_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source=\"grafana-alert\" | unwrap bytes(total_bytes)[$__range]))",
     "legendFormat": "grafana-alerts"
    },
    {
     "expr": "sum(sum_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source=\"grafana-lokiexplore-app\" | unwrap bytes(total_bytes)[$__range]))"
    }
   ]
  },
  {
   "title": "query types count",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source=\"\"| dashboard_id=\"\" [$__range]))",
     "legendFormat": "explore/other"
    },
    {
     "expr": "sum(count_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source!=\"grafana-alert\"| dashboard_id!=\"\"[$__range]))",
     "legendFormat": "dashboards"
    },
    {
     "expr": "sum(count_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source=\"grafana-alert\"[$__range]))",
     "legendFormat": "grafana-alerts"
    },
    {
     "expr": "sum(count_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source=\"grafana-lokiexplore-app\"[$__range]))",
     "legendFormat": "grafana-alerts"
    }
   ]
  },
  {
   "title": "bytes by source",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source=\"\"| dashboard_id!=\"\"  | unwrap bytes(total_bytes)[$__range]))",
     "legendFormat": "dashboards"
    },
    {
     "expr": "sum(sum_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source=\"grafana-alert\" | unwrap bytes(total_bytes)[$__range]))",
     "legendFormat": "grafana-alert"
    },
    {
     "expr": "sum(sum_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source!~\"grafana-alert|grafana-lokiexplore-app\"| dashboard_id=\"\"  | unwrap bytes(total_bytes)[$__range]))",
     "legendFormat": "explore/other"
    },
    {
     "expr": "sum(sum_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source=\"grafana-lokiexplore-app\"  | unwrap bytes(total_bytes)[$__range]))",
     "legendFormat": "explore/other"
    }
   ]
  },
  {
   "title": "Top Users",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "topk(20, sum by (grafana_username) (sum_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\" | grafana_username!=\"\"  | unwrap bytes(total_bytes)[$__range])))"
    }
   ]
  },
  {
   "title": "Bytes by Loki Instance",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "expr": "sum by (user) (sum_over_time({org_id=\"$orgID\"} |= \"request timings\" | logfmt | user=~\"$instance\"| path=~\"/loki/api/v1/.*\" | unwrap bytes(total_bytes)[$__range]))",
     "legendFormat": "{{$user}}"
    },
    {
     "expr": "sum by (user, name) (label_replace(grafanacloud_logs_instance_info{org_id=~\"$orgID\",id=~\"$instance\"}, \"user\", \"$1\", \"id\", \"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "explore/other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Explore/Other Queries",
   "type": "table",
   "description": "This panel shows queries executed via the default Explore page and queries executed from non-Grafana frontend sources, such as logcli.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "topk(20, sum by (query_hash, query, panel_id, grafana_username, user) (sum_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source=\"\"| dashboard_id=\"\"  | unwrap bytes(total_bytes)[$__range])))"
    },
    {
     "expr": "topk(10000,\n    sum by (query_hash) (\n        count_over_time(\n            {org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source!=\"grafana-alert\"| dashboard_id=\"\" | total_bytes > 1MB\n            [$__range]\n        )\n    ) > 0\n)"
    },
    {
     "expr": "60\n/\n(\n    topk(10000,\n        sum by (query_hash) (\n            count_over_time(\n                {org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source!=\"grafana-alert\"| dashboard_id=\"\" | total_bytes > 1MB\n                [$__range]\n            )\n        ) > 0\n    )\n    /\n    ($__range_s/60)\n)"
    }
   ]
  },
  { "title": "dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Dashboard Queries",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "topk(20, sum by (query_hash, query, dashboard_id, dashboard_title, panel_title, panel_id, grafana_username, user) (sum_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt | user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source!=\"grafana-alert\"| dashboard_id!=\"\"  | unwrap bytes(total_bytes)[$__range])))"
    },
    {
     "expr": "topk(10000,\n    sum by (query_hash) (\n        count_over_time(\n            {org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source!=\"grafana-alert\"| dashboard_id!=\"\"\n                | total_bytes > 1MB\n            [$__range]\n        )\n    ) > 0\n)"
    },
    {
     "expr": "60\n/\n(\n    topk(10000,\n        sum by (query_hash) (\n            count_over_time(\n                {org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source!=\"grafana-alert\"| dashboard_id!=\"\"\n                    | total_bytes > 1MB\n                [$__range]\n            )\n        ) > 0\n    )\n    /\n    ($__range_s/60)\n)"
    }
   ]
  },
  { "title": "grafana alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Grafana Alerts",
   "type": "table",
   "description": "If *some* rulers in this table do not show rule_folder and rule_name values then they are likely Grafana Recorded Queries and not Grafana Managed Alerts",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "topk(20, sum by (query_hash, query, rule_name, rule_folder, user) (sum_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source=\"grafana-alert\"| unwrap bytes(total_bytes)[$__range])))"
    },
    {
     "expr": "topk(10000,\n    sum by (query_hash) (\n        count_over_time(\n            {org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source=\"grafana-alert\" | total_bytes > 1MB\n            [$__range]\n        )\n    ) > 0\n)"
    },
    {
     "expr": "60\n/\n(\n    topk(10000,\n        sum by (query_hash) (\n            count_over_time(\n                {org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source=\"grafana-alert\" | total_bytes > 1MB\n                [$__range]\n            )\n        ) > 0\n    )\n    /\n    ($__range_s/60)\n)"
    }
   ]
  },
  { "title": "Explore Logs App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Explore Logs Queries",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "topk(20, sum by (query_hash, query, panel_id, grafana_username, user) (sum_over_time({org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\"| source=\"grafana-lokiexplore-app\" | unwrap bytes(total_bytes)[$__range])))"
    },
    {
     "expr": "topk(10000,\n    sum by (query_hash) (\n        count_over_time(\n            {org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\" |source=\"grafana-lokiexplore-app\"| dashboard_id=\"\" | total_bytes > 1MB\n            [$__range]\n        )\n    ) > 0\n)"
    },
    {
     "expr": "60\n/\n(\n    topk(10000,\n        sum by (query_hash) (\n            count_over_time(\n                {org_id=\"$orgID\"} |= \"request timings\" |logfmt| user=~\"$instance\" | path=~\"/loki/api/v1/.*\" | source=\"grafana-lokiexplore-app\"| dashboard_id=\"\" | total_bytes > 1MB\n                [$__range]\n            )\n        ) > 0\n    )\n    /\n    ($__range_s/60)\n)"
    }
   ]
  }
 ]
}