{
 "title": "BAM Overview Option 1 - 24 Hours",
 "tags": [ "BAM_Overview" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "Early Performance Testing : ept, SIT 1 : sit1, SIT 2 : sit2, Development 1 : dev1, Development 2 : dev2"
   }
  ]
 },
 "panels": [
  { "title": "Clearing and Settlement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BAM6-W1-Aggregate No. of Transaction Volume by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_cs_k8s\" \"kubernetes.container_name\"=\"rtr-cs-service-settlement-engine-tr-wo-res-${env}\" message=\"*loggerName=ca.payments.rtr.cs.lib.settlement.engine.common.services.SyncWithAsyncWriterService*\" message=\"*POST/settlement-engine/transfer-wo-reserve*\" message=\"*\\\"isoMessageId\\\":\\\"camt.006.001.08\\\"*\"\n| eval log_without_backslashes = replace(_raw, \"\\\\\\\\\", \"\")\n| rex field=log_without_backslashes \"\\\"rtgs\\\":\\\"(?<rtgs>[^\\\"]+)\\\"\"\n| timechart span=15m count by rtgs\n| addtotals",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "BAM6-W2- Rejected Transactions Reasons",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_cs_k8s\" \n\"kubernetes.container_name\"=\"rtr-cs-service-settlement-engine-tr-wo-res-${env}\" \nmessage=\"*loggerName=ca.payments.rtr.cs.lib.settlement.engine.common.services.SyncWithAsyncWriterService*\" \nmessage=\"*POST/settlement-engine/transfer-wo-reserve*\" \nmessage=\"*\\\"isoMessageId\\\":\\\"camt.050.001.05\\\"*\"\n| eval log_without_backslashes = replace(_raw, \"\\\\\\\\\", \"\")\n| rex field=log_without_backslashes \"eventDateTime=(?<eventDateTime>\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{9})\"\n| rex field=log_without_backslashes \"\\\"end_to_end_identification\\\":\\\"(?<eteID>[^\\\"]+)\\\"\"\n| rex field=log_without_backslashes \"\\\"uetr\\\":\\\"(?<uetr>[^\\\"]+)\\\"\"\n| rex field=log_without_backslashes \"\\\"debtor\\\":\\\"(?<debtor>[^\\\"]+)\\\"\"\n| rex field=log_without_backslashes \"\\\"creditor\\\":\\\"(?<creditor>[^\\\"]+)\\\"\"\n| table eventDateTime, eteID, uetr, debtor, creditor",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    },
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_cs_k8s\" \"kubernetes.container_name\"=\"rtr-cs-service-settlement-engine-tr-wo-res-${env}\" message=\"*loggerName=ca.payments.rtr.cs.lib.settlement.engine.common.services.SyncWithAsyncWriterService*\" message=\"*POST/settlement-engine/transfer-wo-reserve*\" message=\"*\\\"isoMessageId\\\":\\\"camt.006.001.08\\\"*\"\n| eval log_without_backslashes = replace(_raw, \"\\\\\\\\\", \"\")\n| rex field=log_without_backslashes \"eventDateTime=(?<eventDateTime>\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{9})\"\n| rex field=log_without_backslashes \"\\\"rtgs\\\":\\\"(?<rtgs>[^\\\"]+)\\\"\"\n| rex field=log_without_backslashes \"\\\"end_to_end_identification\\\":\\\"(?<eteID>[^\\\"]+)\\\"\"\n| rex field=log_without_backslashes \"\\\"reason\\\":{\\\"proprietary\\\":\\\"(?<rejectionReason>[^\\\"]+)\\\"\"\n| rex field=log_without_backslashes \"eventDetails\\\":\\\"{\\\"return_transaction\\\":{.*?\\\"to\\\":{\\\"organisation_identification\\\":{\\\"identification\\\":{\\\"organisation_identification\\\":{\\\"other\\\":{\\\"identification\\\":\\\"(?<to_identification>[A-Z0-9]{4})\\\"\"\n| rex field=log_without_backslashes \"eventDetails\\\":\\\"{\\\"return_transaction\\\":{.*?\\\"from\\\":{\\\"organisation_identification\\\":{\\\"identification\\\":{\\\"organisation_identification\\\":{\\\"other\\\":{\\\"identification\\\":\\\"(?<from_identification>[A-Z0-9]{6})\\\"\"\n| table eventDateTime, rtgs, eteID, to_identification, from_identification, rejectionReason",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "BAM6-W3-Transaction Volume Sent by Participant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_cs_k8s\" \n\"kubernetes.container_name\"=\"rtr-cs-service-settlement-engine-tr-wo-res-${env}\" \nmessage=\"*loggerName=ca.payments.rtr.cs.lib.settlement.engine.common.services.SyncWithAsyncWriterService*\" \nmessage=\"*POST/settlement-engine/transfer-wo-reserve*\" \nmessage=\"*\\\"isoMessageId\\\":\\\"camt.050.001.05\\\"*\"\n| eval log_without_backslashes = replace(_raw, \"\\\\\\\\\", \"\")\n| rex field=log_without_backslashes \"\\\"debtor\\\":\\\"(?<debtor>[^\\\"]+)\\\"\"\n| rex field=log_without_backslashes \"\\\"creditor\\\":\\\"(?<creditor>[^\\\"]+)\\\"\"\n| timechart span=15m count by debtor",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "BAM6-W4-Transaction Volume Received by Participant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_cs_k8s\" \n\"kubernetes.container_name\"=\"rtr-cs-service-settlement-engine-tr-wo-res-${env}\" \nmessage=\"*loggerName=ca.payments.rtr.cs.lib.settlement.engine.common.services.SyncWithAsyncWriterService*\" \nmessage=\"*POST/settlement-engine/transfer-wo-reserve*\" \nmessage=\"*\\\"isoMessageId\\\":\\\"camt.050.001.05\\\"*\"\n| eval log_without_backslashes = replace(_raw, \"\\\\\\\\\", \"\")\n| rex field=log_without_backslashes \"\\\"debtor\\\":\\\"(?<debtor>[^\\\"]+)\\\"\"\n| rex field=log_without_backslashes \"\\\"creditor\\\":\\\"(?<creditor>[^\\\"]+)\\\"\"\n| timechart span=15m count by creditor",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "BAM6-W5-Transaction Volume Sent by Exchange",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_cs_k8s\" \"kubernetes.container_name\"=\"rtr-cs-service-settlement-engine-tr-wo-res-${env}\" message=\"*loggerName=ca.payments.rtr.cs.lib.settlement.engine.common.services.SyncWithAsyncWriterService*\" message=\"*POST/settlement-engine/transfer-wo-reserve*\" message=\"*\\\"isoMessageId\\\":\\\"camt.006.001.08\\\"*\"\n| eval log_without_backslashes = replace(_raw, \"\\\\\\\\\", \"\")\n| rex field=log_without_backslashes \"eventDetails\\\":\\\"{\\\"return_transaction\\\":{.*?\\\"to\\\":{\\\"organisation_identification\\\":{\\\"identification\\\":{\\\"organisation_identification\\\":{\\\"other\\\":{\\\"identification\\\":\\\"(?<to_identification>[A-Z0-9]{4})\\\"\"\n| rex field=log_without_backslashes \"eventDetails\\\":\\\"{\\\"return_transaction\\\":{.*?\\\"from\\\":{\\\"organisation_identification\\\":{\\\"identification\\\":{\\\"organisation_identification\\\":{\\\"other\\\":{\\\"identification\\\":\\\"(?<from_identification>[A-Z0-9]{6})\\\"\"\n| timechart span=15m count by to_identification",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  { "title": "Exchange", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "BAM1-W1-Aggregate No. of Transaction Volume by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_exch_k8s\" \"kubernetes.container_name\"=\"rtr-credit-transfer-api-${env}\" (message=\"*pacs.008*\" OR message=\"*pacs.002*\" OR message=\"*head.001*\") message=\"*Settlement Commit Advice pacs.002 sent to DA*\"\n| timechart span=15m count",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    },
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_dev1_exch_k8s\" \"kubernetes.container_name\"=\"rtr-credit-transfer-api-dev1\" (message=\"*pacs.008*\" OR message=\"*pacs.002*\" OR message=\"*head.001*\")\n| rex field=message \"\\\"error_code\\\":\\\"(?<error_code>[^\\\"]+)\\\"\"\n| rex field=message \"\\\"uetr\\\":\\\"(?<uetr>[^\\\"]+)\\\"\"\n| rex field=message \"\\\"clearing_system_reference\\\":\\\"(?<clearing_system_reference>[^\\\"]+)\\\"\"\n| where clearing_system_reference=\"${traceabilityID}\"\n| where error_code!=\"NA\"\n| timechart span=15m distinct_count(uetr)",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "BAM1-W2-Transaction Volume Sent by Participant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_exch_k8s\" \"kubernetes.container_name\"=\"rtr-credit-transfer-api-${env}\" (message=\"*pacs.008*\" OR message=\"*pacs.002*\" OR message=\"*head.001*\") message=\"*Settlement Commit Advice pacs.002 sent to DA*\"\n| rex field=message \"\\\"api_provider\\\":\\\"(?<creditor>[^\\\"]+)\\\"\"\n| rex field=message \"\\\"api_consumer\\\":\\\"(?<debitor>[^\\\"]+)\\\"\"\n| timechart span=15m count by creditor",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "BAM1-W3-Transaction Volume Received by Participant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_exch_k8s\" \"kubernetes.container_name\"=\"rtr-credit-transfer-api-${env}\" (message=\"*pacs.008*\" OR message=\"*pacs.002*\" OR message=\"*head.001*\") message=\"*Settlement Commit Advice pacs.002 sent to DA*\"\n| rex field=message \"\\\"api_provider\\\":\\\"(?<creditor>[^\\\"]+)\\\"\"\n| rex field=message \"\\\"api_consumer\\\":\\\"(?<debitor>[^\\\"]+)\\\"\"\n| timechart span=15m count by debitor",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "BAM1-W4-Transaction Volume Sent by CSP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_exch_k8s\" \"kubernetes.container_name\"=\"rtr-credit-transfer-api-${env}\" (message=\"*pacs.008*\" OR message=\"*pacs.002*\" OR message=\"*head.001*\") message=\"*Settlement Commit Advice pacs.002 sent to DA*\"\n| rex field=message \"\\\"api_provider\\\":\\\"(?<creditor>[^\\\"]+)\\\"\"\n| rex field=message \"\\\"api_consumer\\\":\\\"(?<debitor>[^\\\"]+)\\\"\"\n| timechart span=15m count by creditor",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  }
 ]
}