{
 "title": "BAM Overview Option 1 - 1 Hour",
 "tags": [ "BAM_Overview" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "Early Performance Testing : ept, SIT 1 : sit1, SIT 2 : sit2, Development 1 : dev1, Development 2 : dev2"
   }
  ]
 },
 "panels": [
  { "title": "Clearing and Settlement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BAM7-W1 -Payments Per Second by Sending Participant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_cs_k8s\" \n\"kubernetes.container_name\"=\"rtr-cs-service-settlement-engine-tr-wo-res-${env}\" \nmessage=\"*loggerName=ca.payments.rtr.cs.lib.settlement.engine.common.services.SyncWithAsyncWriterService*\" \nmessage=\"*POST/settlement-engine/transfer-wo-reserve*\" \nmessage=\"*\\\"isoMessageId\\\":\\\"camt.050.001.05\\\"*\"\n| eval log_without_backslashes = replace(_raw, \"\\\\\\\\\", \"\")\n| rex field=log_without_backslashes \"\\\"debtor\\\":\\\"(?<debtor>[^\\\"]+)\\\"\"\n| rex field=log_without_backslashes \"\\\"creditor\\\":\\\"(?<creditor>[^\\\"]+)\\\"\"\n| timechart span=1m count by debtor\n| addtotals",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "BAM7-W2-Payments Per Second by Sending Exchange",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_cs_k8s\" \"kubernetes.container_name\"=\"rtr-cs-service-settlement-engine-tr-wo-res-${env}\" message=\"*loggerName=ca.payments.rtr.cs.lib.settlement.engine.common.services.SyncWithAsyncWriterService*\" message=\"*POST/settlement-engine/transfer-wo-reserve*\" message=\"*\\\"isoMessageId\\\":\\\"camt.006.001.08\\\"*\"\n| eval log_without_backslashes = replace(_raw, \"\\\\\\\\\", \"\")\n| rex field=log_without_backslashes \"eventDetails\\\":\\\"{\\\"return_transaction\\\":{.*?\\\"to\\\":{\\\"organisation_identification\\\":{\\\"identification\\\":{\\\"organisation_identification\\\":{\\\"other\\\":{\\\"identification\\\":\\\"(?<to_identification>[A-Z0-9]{4})\\\"\"\n| rex field=log_without_backslashes \"eventDetails\\\":\\\"{\\\"return_transaction\\\":{.*?\\\"from\\\":{\\\"organisation_identification\\\":{\\\"identification\\\":{\\\"organisation_identification\\\":{\\\"other\\\":{\\\"identification\\\":\\\"(?<from_identification>[A-Z0-9]{6})\\\"\"\n| timechart span=1m count by to_identification\n| addtotals",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  { "title": "Exchange", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "BAM3-W1-Heartbeat Failure Percentage: Sent from Exchange ",
   "type": "stat",
   "description": "Green: 0% - 5%\n\nYellow: 5% - 10%\n\nRed: 10% - 100%",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_exch_k8s\" kubernetes.container_name=\"rtr-heartbeat-outbound-api-${env}\" level=info message=\"*.interac.rtr.heartbeat.service.MetricLoggingService*\"\n| rex field=_raw \"ca.interac.rtr.heartbeat.service.MetricLoggingService - (?<status>.*?) \"\n| rex field=_raw \"participant=(?<participant>\\w+)\"\n| stats count by status, participant",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "BAM3-W2-Heartbeat Failure Percentage: Received by Exchange ",
   "type": "stat",
   "description": "Green: 0% - 5%\n\nYellow: 5% - 10%\n\nRed: 10% - 100%",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_exch_k8s\" kubernetes.container_name=\"rtr-heartbeat-inbound-api-${env}\" level=info message=\"*.interac.rtr.heartbeat.service.MetricLoggingService*\"\n| rex field=_raw \"ca.interac.rtr.heartbeat.service.MetricLoggingService - (?<status>.*?) \"\n| rex field=_raw \"participant=(?<participant>\\w+)\"\n| stats count by status, participant",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "BAM2-W1-Payments Per Second by Sending Participant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_exch_k8s\" \"kubernetes.container_name\"=\"rtr-credit-transfer-api-${env}\" (message=\"*pacs.008*\" OR message=\"*pacs.002*\" OR message=\"*head.001*\") message=\"*Settlement Commit Advice pacs.002 sent to DA*\"\n| rex field=message \"\\\"api_provider\\\":\\\"(?<creditor>[^\\\"]+)\\\"\"\n| rex field=message \"\\\"api_consumer\\\":\\\"(?<debitor>[^\\\"]+)\\\"\"\n| timechart span=1m count by creditor",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "BAM2-W2-Payments Per Second by CSP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"index_${env}_exch_k8s\" \"kubernetes.container_name\"=\"rtr-credit-transfer-api-${env}\" (message=\"*pacs.008*\" OR message=\"*pacs.002*\" OR message=\"*head.001*\") message=\"*Settlement Commit Advice pacs.002 sent to DA*\"\n| rex field=message \"\\\"api_provider\\\":\\\"(?<creditor>[^\\\"]+)\\\"\"\n| rex field=message \"\\\"api_consumer\\\":\\\"(?<debitor>[^\\\"]+)\\\"\"\n| timechart span=1m count by creditor",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  }
 ]
}