{
 "title": "AWS EBS",
 "description": "Visualize Amazon EBS metrics",
 "tags": [ "cloudwatch-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(aws_ebs_info, scrape_job)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(aws_ebs_volume_idle_time_average, region)"
   },
   {
    "name": "volume",
    "label": "Volume",
    "query": "label_values(aws_ebs_volume_idle_time_average{scrape_job=~\"$job\", region=~\"$region\"}, dimension_VolumeId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24 },
   "content": "Showing metrics only for AWS resources that have tags assigned to them. For more information, see [Amazon CloudWatch Metrics for Amazon EBS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using_cloudwatch_ebs.html).\n"
  },
  {
   "title": "Volume read bandwidth (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "aws_ebs_volume_read_bytes_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_VolumeId=~\"$volume\"}",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Volume write bandwidth (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "aws_ebs_volume_write_bytes_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_VolumeId=~\"$volume\"}",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Volume read throughput (operations)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "aws_ebs_volume_read_ops_average{scrape_job=~\"$job\", region=~\"$region\", dimension_VolumeId=~\"$volume\"}",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Volume write throughput (operations)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "aws_ebs_volume_write_ops_average{scrape_job=~\"$job\", region=~\"$region\", dimension_VolumeId=~\"$volume\"}",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Volume idle time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ebs_volume_idle_time_average{scrape_job=~\"$job\", region=~\"$region\", dimension_VolumeId=~\"$volume\"}",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Volume total read time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ebs_volume_total_read_time_average{scrape_job=~\"$job\", region=~\"$region\", dimension_VolumeId=~\"$volume\"}",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Volume total write time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ebs_volume_total_write_time_average{scrape_job=~\"$job\", region=~\"$region\", dimension_VolumeId=~\"$volume\"}",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Volume queue length (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_ebs_volume_queue_length_average{scrape_job=~\"$job\", region=~\"$region\", dimension_VolumeId=~\"$volume\"}",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Volume throughput percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ebs_volume_throughput_percentage_average{scrape_job=~\"$job\", region=~\"$region\", dimension_VolumeId=~\"$volume\"}",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Burst balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_ebs_burst_balance_average{scrape_job=~\"$job\", region=~\"$region\", dimension_VolumeId=~\"$volume\"}",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  },
  {
   "title": "Volume consumed r/w operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_ebs_volume_consumed_read_write_ops_average{scrape_job=~\"$job\", region=~\"$region\", dimension_VolumeId=~\"$volume\"}",
     "legendFormat": "{{dimension_VolumeId}}"
    }
   ]
  }
 ]
}