{
 "title": "AWS Billing",
 "description": "Visualize estimated AWS charges per AWS resource (EC2, S3, ...)",
 "tags": [ "cloudwatch-integration" ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(aws_billing_estimated_charges_average,scrape_job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Showing estimated charges for AWS resources. For more information, see [Monitor estimated charges with Cloudwatch](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/monitor_estimated_charges_with_cloudwatch.html) for more info."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Estimated Monthly Charge (to date)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_billing_estimated_charges_average{scrape_job=~\"$job\", dimension_Currency=\"USD\", dimension_ServiceName=\"\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total number of active services",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count_over_time(aws_billing_estimated_charges_average{scrape_job=~\"$job\", dimension_Currency=\"USD\", dimension_ServiceName!=\"\"}[30d]) > 0)",
     "legendFormat": "{{dimension_ServiceName}}"
    }
   ]
  },
  {
   "title": "Estimated daily charges",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "Currency": "USD" },
     "expr": "rate(aws_billing_estimated_charges_average{scrape_job=~\"$job\", dimension_Currency=\"USD\", dimension_ServiceName=\"\"}[24h]) * 86400 > 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "id": "m1",
     "item": { "filter": "" },
     "legendFormat": "Total estimated daily charge",
     "metricName": "EstimatedCharges",
     "namespace": "AWS/Billing",
     "options": {
      "showDisabledItems": false
     },
     "period": "86400",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Estimated charges",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "Total",
     "application": { "filter": "" },
     "dimensions": { "Currency": "USD" },
     "expr": "aws_billing_estimated_charges_average{scrape_job=~\"$job\", dimension_Currency=\"USD\", dimension_ServiceName!=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "Total",
     "legendFormat": "{{dimension_ServiceName}}",
     "metricName": "EstimatedCharges",
     "namespace": "AWS/Billing",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "expr": "aws_billing_estimated_charges_average{scrape_job=~\"$job\", dimension_Currency=\"USD\", dimension_ServiceName=\"\"}",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}