{
 "title": "AWS ELB Application Load Balancer",
 "description": "Visualize AWS ELB Application Load Balancer metrics",
 "tags": [ "cloudwatch-integration" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(aws_applicationelb_info,scrape_job)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(aws_applicationelb_request_count_sum{scrape_job=~\"$job\"},region)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(aws_applicationelb_request_count_sum{scrape_job=~\"$job\", region=~\"$region\"},dimension_LoadBalancer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Showing metrics only for AWS resources that have tags assigned to them. For more information, see [Amazon CloudWatch Metrics for Amazon Application Load Balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "RequestCount / TargetResponseTime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_request_count_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "RequestCount_Sum - {{dimension_LoadBalancer}}",
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_target_response_time_average{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "TargetResponseTime_Average - {{dimension_LoadBalancer}}",
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "HTTPCode_Target",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_applicationelb_httpcode_target_2_xx_count_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "legendFormat": "HTTPCode_Target_2XX_Count_Sum - {{dimension_LoadBalancer}}"
    },
    {
     "expr": "aws_applicationelb_httpcode_target_3_xx_count_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "legendFormat": "HTTPCode_Target_3XX_Count_Sum - {{dimension_LoadBalancer}}"
    },
    {
     "expr": "aws_applicationelb_httpcode_target_4_xx_count_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "legendFormat": "HTTPCode_Target_4XX_Count_Sum - {{dimension_LoadBalancer}}"
    },
    {
     "expr": "aws_applicationelb_httpcode_target_5_xx_count_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "legendFormat": "HTTPCode_Target_5XX_Count_Sum - {{dimension_LoadBalancer}}"
    }
   ]
  },
  {
   "title": "HTTPCode_ELB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_httpcode_elb_3_xx_count_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "HTTPCode_ELB_3XX_Count_Sum - {{dimension_LoadBalancer}}",
     "metricName": "HTTPCode_ELB_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_httpcode_elb_4_xx_count_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "HTTPCode_ELB_4XX_Count_Sum - {{dimension_LoadBalancer}}",
     "metricName": "HTTPCode_ELB_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_httpcode_elb_5_xx_count_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "HTTPCode_ELB_5XX_Count_Sum - {{dimension_LoadBalancer}}",
     "metricName": "HTTPCode_ELB_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ConnectionCount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_applicationelb_active_connection_count_average{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "legendFormat": "ActiveConnectionCount_Average - {{dimension_LoadBalancer}}"
    },
    {
     "expr": "aws_applicationelb_new_connection_count_average{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "legendFormat": "NewConnectionCount_Average - {{dimension_LoadBalancer}}"
    },
    {
     "expr": "aws_applicationelb_rejected_connection_count_average{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "legendFormat": "RejectedConnectionCount_Average - {{dimension_LoadBalancer}}"
    },
    {
     "expr": "aws_applicationelb_target_connection_error_count_average{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "legendFormat": "TargetRejectedErrorCount_Average - {{dimension_LoadBalancer}}"
    }
   ]
  },
  {
   "title": "ConsumedLCUs / ProcessedBytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_consumed_lcus_average{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "ConsumedLCUs_Average - {{dimension_LoadBalancer}}",
     "metricName": "ProcessedBytes",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_processed_bytes_average{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "ProcessedBytes_Average - {{dimension_LoadBalancer}}",
     "metricName": "ConsumedLCUs",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "TLSNegotiationErrorCount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_target_tlsnegotiation_error_count_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "TargetTLSNegotiationErrorCount_Sum - {{dimension_LoadBalancer}}",
     "metricName": "TargetTLSNegotiationErrorCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_client_tlsnegotiation_error_count_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "ClientTLSNegotiationErrorCount_Sum - {{dimension_LoadBalancer}}",
     "metricName": "ClientTLSNegotiationErrorCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "IPv6",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_ipv6_request_count_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "IPv6RequestCount_Sum - {{dimension_LoadBalancer}}",
     "metricName": "IPv6RequestCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_ipv6_processed_bytes_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "IPv6ProcessedBytes_Sum - {{dimension_LoadBalancer}}",
     "metricName": "IPv6ProcessedBytes",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "RuleEvaluations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_rule_evaluations_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "RuleEvaluations_Sum - {{dimension_LoadBalancer}}",
     "metricName": "RuleEvaluations",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Auth",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_elbauth_success_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "ELBAuthSucces_Sum - {{dimension_LoadBalancer}}",
     "metricName": "ELBAuthError",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_elbauth_failure_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "ELBAuthFailure_Sum - {{dimension_LoadBalancer}}",
     "metricName": "ELBAuthError",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_elbauth_error_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "ELBAuthError_Sum - {{dimension_LoadBalancer}}",
     "metricName": "ELBAuthError",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_elbauth_refresh_token_success_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "ELBAuthRefreshTokenSuccess_Sum - {{dimension_LoadBalancer}}",
     "metricName": "ELBAuthError",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_elbauth_user_claims_size_exceeded_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "ELBAuthUserClaimsSizeExceeded_Sum - {{dimension_LoadBalancer}}",
     "metricName": "ELBAuthError",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "expr": "aws_applicationelb_elbauth_latency_average{scrape_job=~\"$job\", region=~\"$region\", dimension_LoadBalancer=~\"$instance\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=\"\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "ELBAuthLatency_Average - {{dimension_LoadBalancer}}",
     "metricName": "ELBAuthError",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}