{
 "title": "AWS RDS",
 "description": "Visualize Amazon RDS metrics",
 "tags": [ "cloudwatch-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(aws_rds_info, scrape_job)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(aws_rds_database_connections_sum, region)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(aws_rds_database_connections_sum{scrape_job=~\"$job\", region=~\"$region\"}, dimension_DBInstanceIdentifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 24 },
   "content": "Showing metrics only for AWS resources that have tags assigned to them. For more information, see [Amazon CloudWatch Metrics for Amazon RDS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/monitoring-cloudwatch.html).\n"
  },
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_maximum{scrape_job=~\"$job\", region=~\"$region\", dimension_DBInstanceIdentifier=~\"$instance\"}",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Database connections count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_database_connections_sum{scrape_job=~\"$job\", region=~\"$region\", dimension_DBInstanceIdentifier=~\"$instance\"}",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Free storage space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_average{scrape_job=~\"$job\", region=~\"$region\", dimension_DBInstanceIdentifier=~\"$instance\"}",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Freeable memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_average{scrape_job=~\"$job\", region=~\"$region\", dimension_DBInstanceIdentifier=~\"$instance\"}",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Disk read throughput (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "aws_rds_read_throughput_average{scrape_job=~\"$job\", region=~\"$region\", dimension_DBInstanceIdentifier=~\"$instance\"}",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Disk write throughput (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "aws_rds_write_throughput_average{scrape_job=~\"$job\", region=~\"$region\", dimension_DBInstanceIdentifier=~\"$instance\"}",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Disk read IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "aws_rds_read_iops_average{scrape_job=~\"$job\", region=~\"$region\", dimension_DBInstanceIdentifier=~\"$instance\"}",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Disk write IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "aws_rds_write_iops_average{scrape_job=~\"$job\", region=~\"$region\", dimension_DBInstanceIdentifier=~\"$instance\"}",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Disk read latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "aws_rds_read_latency_maximum{scrape_job=~\"$job\", region=~\"$region\", dimension_DBInstanceIdentifier=~\"$instance\"}",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Disk write latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "aws_rds_write_latency_maximum{scrape_job=~\"$job\", region=~\"$region\", dimension_DBInstanceIdentifier=~\"$instance\"}",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  }
 ]
}