{
 "title": "AWS SES",
 "description": "Visualize AWS SES metrics",
 "tags": [ "cloudwatch-integration" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(aws_ses_info,scrape_job)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(aws_ses_send_average,region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Showing metrics only for AWS resources that have tags assigned to them. For more information, see [Amazon CloudWatch Metrics for Amazon SES](https://docs.aws.amazon.com/ses/latest/dg/event-publishing-retrieving-cloudwatch.html).\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Send / Delivery",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "aws_ses_send_average{scrape_job=~\"$job\", region=~\"$region\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Send_Average",
     "metricName": "Send",
     "namespace": "AWS/SES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "expr": "aws_ses_delivery_average{scrape_job=~\"$job\", region=~\"$region\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Delivery_Average",
     "metricName": "Delivery",
     "namespace": "AWS/SES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Bounce / Reject",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "aws_ses_bounce_average{scrape_job=~\"$job\", region=~\"$region\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Bounce_Average",
     "metricName": "Bounce",
     "namespace": "AWS/SES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "expr": "aws_ses_reject_average{scrape_job=~\"$job\", region=~\"$region\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Reject_Average",
     "metricName": "Reject",
     "namespace": "AWS/SES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Complaint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "aws_ses_complaint_average{scrape_job=~\"$job\", region=~\"$region\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Complaint_Average",
     "metricName": "Complaint",
     "namespace": "AWS/SES",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}