{
 "title": "Overview [Celsius]",
 "description": "Weather dashboard with units in °C",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_LOKI", "query": "loki" },
   { "name": "location", "label": "Location", "query": "label_values(location)" },
   { "name": "forecast_day", "label": "Forecast Days", "query": "label_values(forecast_day)" }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(weather_temp_c{job=\"weather-service\", location=~\"$location\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feels Like Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(weather_feelslike_temp_c{job=\"weather-service\", location=~\"$location\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(weather_temp_c{job=\"weather-service\", location=~\"$location\"}) by (location)",
     "legendFormat": "Actual Temperature - {{ location }}"
    },
    {
     "expr": "avg(weather_feelslike_temp_c{job=\"weather-service\",location=~\"$location\"}) by (location)",
     "legendFormat": "Perceived Temperature - {{ location }}"
    },
    {
     "expr": "avg(weather_forecast_temp_c{job=\"weather-service\", location=~\"$location\", forecast_day=\"0\"}) by (location)",
     "legendFormat": "Predicted Temperature - {{ location }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "avg(weather_humidity{job=\"weather-service\", location=~\"$location\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "avg(weather_humidity{job=\"weather-service\", location=~\"$location\"}) by (location)",
     "legendFormat": "Actual Humidity - {{ location }}"
    },
    {
     "expr": "avg(weather_forecast_humidity{job=\"weather-service\", location=~\"$location\", forecast_day=\"0\"}) by (location)",
     "legendFormat": "Predicted Humidity - {{ location }}"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "avg(weather_location_info{job=\"weather-service\", location=~\"$location\"}) by (location,lat,lon)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg(weather_uv_index{job=\"weather-service\",location=~\"$location\"}) by (location)",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(weather_uv_index{job=\"weather-service\",location=~\"$location\"}) by (location)",
     "legendFormat": "Actual UV Index - {{ location }}"
    },
    {
     "expr": "avg(weather_forecast_uv_index{job=\"weather-service\", location=~\"$location\"}) by (location)",
     "legendFormat": "Predicted UV Index - {{ location }}"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "avg(weather_wind_speed{job=\"weather-service\",location=~\"$location\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "{namespace=\"weather-service\"} |= \"wind_dir\" |~ \"$location\" | logfmt"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "avg(weather_wind_speed{job=\"weather-service\",location=~\"$location\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "avg(weather_precip_mm{job=\"weather-service\",location=~\"$location\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(weather_precip_mm{job=\"weather-service\",location=~\"$location\"}) by (location)",
     "legendFormat": "Actual Precipitation - {{ location }}"
    },
    {
     "expr": "avg(weather_forecast_precip_mm{job=\"weather-service\", location=~\"$location\", forecast_day=\"0\"}) by (location)",
     "legendFormat": "Predicted Precipitation - {{ location }}"
    }
   ]
  },
  {
   "title": "Condition",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{namespace=\"weather-service\"} |= \"Current Condition\" | logfmt | location=~\"$location\""
    }
   ]
  },
  {
   "title": "Forecast for today + $forecast_day days",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "forecast_day"
  },
  {
   "title": "Forecast Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(weather_forecast_temp_c{job=\"weather-service\", location=~\"$location\", forecast_day=~\"$forecast_day\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forecast Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(weather_forecast_temp_c{job=\"weather-service\", location=~\"$location\", forecast_day=~\"$forecast_day\"}) by (location)",
     "legendFormat": "Forecast Temperature - {{ location }}"
    },
    {
     "expr": "avg(weather_forecast_max_temp_c{job=\"weather-service\", location=~\"$location\", forecast_day=~\"$forecast_day\"}) by (location)",
     "legendFormat": "Forecast Max Temperature - {{ location }}"
    },
    {
     "expr": "avg(weather_forecast_min_temp_c{job=\"weather-service\", location=~\"$location\", forecast_day=~\"$forecast_day\"}) by (location)",
     "legendFormat": "Forecast Min Temperature - {{ location }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "avg(weather_forecast_humidity{job=\"weather-service\", location=~\"$location\", forecast_day=~\"$forecast_day\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "avg(weather_forecast_precip_mm{job=\"weather-service\", location=~\"$location\", forecast_day=~\"$forecast_day\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "avg(weather_forecast_uv_index{job=\"weather-service\", location=~\"$location\", forecast_day=~\"$forecast_day\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Condition and Astro Timings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{namespace=\"weather-service\"} |= \"Forecast Condition\" | logfmt | location=~\"$location\" | forecast_day=\"$forecast_day\""
    }
   ]
  }
 ]
}