{
 "title": "L2/3 Operations",
 "tags": [ "Drilldown" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "Move Money,Signon,SSO,,Accounts,OTVC,Preferences,Database,Profiles"
   },
   { "name": "transaction_id", "label": "Transaction ID" },
   { "name": "card_number", "label": "Card Number" },
   { "name": "splunk_search", "label": "Splunk Search" }
  ]
 },
 "panels": [
  { "title": "Incidents and Changes ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incidents",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "displayValue": "all",
     "fields": [
      {
       "aggregates": [],
       "name": "number"
      },
      {
       "aggregates": [],
       "name": "opened_at"
      },
      {
       "aggregates": [],
       "name": "priority"
      },
      {
       "aggregates": [],
       "name": "severity"
      },
      {
       "aggregates": [],
       "name": "category"
      },
      {
       "aggregates": [],
       "name": "cmdb_ci.name"
      },
      {
       "aggregates": [],
       "name": "short_description"
      }
     ],
     "filters": [
      { "conjunction": "and" }
     ],
     "limit": 25,
     "sort": [
      { "field": "opened_at", "order": "desc" },
      {}
     ],
     "table": "incident",
     "timeField": "ignore_time"
    }
   ]
  },
  {
   "title": "Change Records",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "displayValue": "all",
     "fields": [
      {
       "aggregates": [],
       "name": "number"
      },
      {
       "aggregates": [],
       "name": "work_end"
      },
      {
       "aggregates": [],
       "name": "category"
      },
      {
       "aggregates": [],
       "name": "state"
      },
      {
       "aggregates": [],
       "name": "cmdb_ci.name"
      },
      {
       "aggregates": [],
       "name": "short_description"
      }
     ],
     "filters": [
      { "conjunction": "and" }
     ],
     "limit": 25,
     "sort": [
      { "field": "number", "order": "desc" },
      {}
     ],
     "table": "change_request",
     "timeField": "ignore_time"
    }
   ]
  },
  { "title": "KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Client Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response Time (Dynatrace)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gateway Error Rate (Splunk)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service Level Availability (Dynatrce) ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Response Error Rate (Splunk)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
   "targets": [
    {},
    {},
    {},
    {},
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {},
    {},
    {},
    {},
    {}
   ]
  },
  {
   "title": "Status Codes from Splunk  (Pie charts)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Splunk Error Code Breakdown",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Status Code",
        "type": "number",
        "values": [
         500,
         400,
         401
        ]
       },
       {
        "config": {},
        "name": "Count",
        "type": "number",
        "values": [
         245,
         100,
         10
        ]
       }
      ],
      "meta": {}
     }
    }
   ]
  },
  {
   "title": "Splunk Module Request Response Index",
   "type": "piechart",
   "description": "Custom Codes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "customstatus",
        "type": "number",
        "values": [
         123,
         345,
         567
        ]
       },
       {
        "config": {},
        "name": "Count",
        "type": "number",
        "values": [
         35,
         28,
         145
        ]
       }
      ],
      "meta": {}
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "customstatus",
        "type": "number",
        "values": [
         123,
         345,
         567
        ]
       },
       {
        "config": {},
        "name": "message",
        "type": "string",
        "values": [
         "Request Successful",
         "Fraud Activity Error",
         "User Submitted Incorrect OTVC"
        ]
       }
      ],
      "meta": {},
      "name": "Custom Codes Table"
     }
    }
   ]
  },
  {
   "title": "Platform KPIs (Db response, JVM, F5,..etc)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "F5 Response Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {}
     ]
    },
    {
     "title": "Database Response Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {}
     ]
    },
    {
     "title": "JVM Heap Utilization %",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {}
     ]
    },
    {
     "title": "JVM Heap Usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Splunk Logs (audit file, request/response. gateway)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "title": "ebnk_audit",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "{job=\"kube-monitoring/alloy\"} |= ``"
    }
   ]
  },
  {
   "title": "ebnk_gateway",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "{job=\"IGM Citrix Cloud Status Page\"} |= ``"
    }
   ]
  },
  {
   "title": "ebnk_module_request_response",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{job=\"weather-service/weather-service\"} |= ``"
    }
   ]
  }
 ]
}