{
 "title": "Grafana Alert Management",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": "kansas-prod" }
  ]
 },
 "panels": [
  {
   "title": "Alert Rule Deployment Status",
   "type": "stat",
   "description": "Percentage of active vs paused alerts",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafanacloud_grafana_instance_alerting_rule_group_rules{id=\"793527\", state=~\"active|paused\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Alert Rule Deployment Status",
   "type": "stat",
   "description": "Percentage of active vs paused alerts",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafanacloud_grafana_instance_alerting_rule_group_rules{id=\"793527\", state=~\"active|paused\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Grafana Managed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Current Firing Alert Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({instance_id=\"793527\", folderUID=\"ddokt1hspkhs0d\"} | json | current = `Alerting` [$__auto]))",
     "legendFormat": "{{labels_alertname}}"
    }
   ]
  },
  {
   "title": "Current Pending Alert Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({instance_id=\"793527\", folderUID=\"ddokt1hspkhs0d\"} | json | current = `Pending` [$__auto]))",
     "legendFormat": "{{labels_alertname}}"
    }
   ]
  },
  {
   "title": "Current NoData Alert Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({instance_id=\"793527\", folderUID=\"ddokt1hspkhs0d\"} | json | current = `NoData` [$__auto]))",
     "legendFormat": "{{labels_alertname}}"
    }
   ]
  },
  {
   "title": "Current Error Alert Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({instance_id=\"793527\", folderUID=\"ddokt1hspkhs0d\"} | json | current = `Error` [$__auto]))",
     "legendFormat": "{{labels_alertname}}"
    }
   ]
  },
  {
   "title": "Alerts Instances Fired During Selected Timeframe",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(labels_alertname) (rate({instance_id=\"793527\", folderUID=\"ddokt1hspkhs0d\"} | json | current = `Alerting` [$__auto]))",
     "legendFormat": "{{labels_alertname}}"
    }
   ]
  },
  {
   "title": "Alert Instances By State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({instance_id=\"793527\", folderUID=\"ddokt1hspkhs0d\"} | json | current = `Alerting` [$__auto]))",
     "legendFormat": "Alerting"
    },
    {
     "direction": "backward",
     "expr": "count(rate({instance_id=\"793527\", folderUID=\"ddokt1hspkhs0d\"} | json | current = `Pending` [$__auto]))",
     "legendFormat": "Pending"
    },
    {
     "direction": "backward",
     "expr": "count(rate({instance_id=\"793527\", folderUID=\"ddokt1hspkhs0d\"} | json | current = `Error` [$__auto]))",
     "legendFormat": "Error"
    },
    {
     "direction": "backward",
     "expr": "count(rate({instance_id=\"793527\", folderUID=\"ddokt1hspkhs0d\"} | json | current = `NoData` [$__auto]))",
     "legendFormat": "NoData"
    },
    {
     "direction": "backward",
     "expr": "count(rate({instance_id=\"793527\", folderUID=\"ddokt1hspkhs0d\"} | json | current = `Normal` [$__auto]))",
     "legendFormat": "Normal"
    }
   ]
  }
 ]
}