{
 "title": "Level 3",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "splunkSearch", "label": "Splunk Search" }
  ]
 },
 "panels": [
  {
   "title": "Splunk # of Requests by Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "(index=* OR index=_*) (sourcetype=\"Demo Logging App\")  | rename status AS RootObject.status | fields \"RootObject.status\" | stats dedup_splitvals=t count AS \"Count\"  by RootObject.status | sort limit=0 RootObject.status | fields - _span  | rename RootObject.status AS status  | fillnull \"Count\" | fields status, \"Count\"",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "Dynatrace # of Requests by Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "active": "metric",
     "metric": {
      "aggregations": [
       {
        "name": "value",
        "params": []
       }
      ],
      "alias": "200",
      "cleanSelector": "",
      "displayName": "Number of calls without  any errors",
      "filters": {
       "conjunction": "AND",
       "filters": []
      },
      "name": "builtin:service.errors.total.successCount",
      "selector": "",
      "transformations": [
       {
        "name": "names",
        "params": []
       }
      ],
      "zones": []
     },
     "mode": "builder",
     "version": "3.11.3"
    },
    {
     "active": "metric",
     "metric": {
      "aggregations": [
       {
        "name": "value",
        "params": []
       }
      ],
      "alias": "4xx",
      "cleanSelector": "",
      "displayName": "Number of HTTP 4xx errors",
      "filters": {
       "conjunction": "AND",
       "filters": []
      },
      "name": "builtin:service.errors.fourxx.count",
      "selector": "",
      "transformations": [
       {
        "name": "names",
        "params": []
       }
      ],
      "zones": []
     },
     "mode": "builder",
     "version": "3.11.3"
    },
    {
     "active": "metric",
     "metric": {
      "aggregations": [
       {
        "name": "value",
        "params": []
       }
      ],
      "alias": "5xx",
      "cleanSelector": "",
      "displayName": "Number of HTTP 5xx errors",
      "filters": {
       "conjunction": "AND",
       "filters": []
      },
      "name": "builtin:service.errors.fivexx.count",
      "selector": "",
      "transformations": [
       {
        "name": "names",
        "params": []
       }
      ],
      "zones": []
     },
     "mode": "builder",
     "version": "3.11.3"
    }
   ]
  },
  {
   "title": "Dynatrace Open Problems",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "active": "problem",
     "metric": {
      "aggregations": [],
      "alias": "",
      "cleanSelector": "",
      "displayName": "",
      "filters": {
       "conjunction": "AND",
       "filters": []
      },
      "name": "Select...",
      "selector": "",
      "transformations": [
       {
        "name": "names",
        "params": []
       }
      ],
      "zones": []
     },
     "mode": "builder",
     "problem": {
      "expandDetails": false,
      "impact": "",
      "severity": "",
      "status": "OPEN",
      "tags": []
     },
     "version": "3.11.3"
    }
   ]
  },
  {
   "title": "Dynatrace Problems",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "active": "problem",
     "metric": {
      "aggregations": [],
      "alias": "",
      "cleanSelector": "",
      "displayName": "",
      "filters": {
       "conjunction": "AND",
       "filters": []
      },
      "name": "Select...",
      "selector": "",
      "transformations": [
       {
        "name": "names",
        "params": []
       }
      ],
      "zones": []
     },
     "mode": "builder",
     "problem": {
      "expandDetails": true,
      "impact": "",
      "severity": "",
      "status": "",
      "tags": []
     },
     "version": "3.11.3"
    }
   ]
  },
  {
   "title": "Index #1",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=* $splunkSearch",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "Index #2",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "sourcetype=\"Demo Logging App\" $splunkSearch",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "Index #3",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "$splunkSearch",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  }
 ]
}