{
 "title": "Data API Successful Requests qdofmxzsvh9xh9adq2baf",
 "tags": [ "slo" ],
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 0 },
   "options": {
    "content": "# Data API Successful Requests SLO\nWatches the target=/api/data label and evaluates the percentage of successful requests. The target of this SLO is to have 80% of requests to /api/data be successful with 200 status code"
   }
  },
  {
   "title": "Time Window",
   "type": "stat",
   "description": "The time window over which the service level objective is being measured over",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(vector(1), \"time_period\", \"28d\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "stat",
   "description": "The SLO's Objective value. Always between 0 and 100%",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(0.8)", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\", grafana_slo_severity=\"critical\"}) OR on() vector(0)",
     "legendFormat": "Critical alert"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "description": "Service level indicator",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(grafana_slo_sli_5m{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"}[$__interval:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "((sum(rate(app_frontend_requests{status=\"200\",target=\"/api/data\"}[$__rate_interval] offset 2m)) or 0 * sum(rate(app_frontend_requests{target=\"/api/data\"}[$__rate_interval] offset 2m))) / sum(rate(app_frontend_requests{target=\"/api/data\"}[$__rate_interval] offset 2m))) AND timestamp(sum(rate(app_frontend_requests{target=\"/api/data\"}[$__rate_interval] offset 2m))) < 1715357796",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI (last 28d)",
   "type": "stat",
   "description": "Service level indicator's value over the last 28d",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# omit NaN by comparing to Infinity\nsum(sum_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"} < 1e308)[28d:5m]))\n/ sum(sum_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"} < 1e308)[28d:5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\", grafana_slo_severity=\"warning\"}) OR on() vector(0)",
     "legendFormat": "Warning alert"
    }
   ]
  },
  { "title": "Burn Rate Alerts", "type": "alertlist", "description": "All active alerts for this SLO", "gridPos": { "h": 10, "w": 5, "x": 0, "y": 8 } },
  {
   "title": "Error Budget Trend",
   "type": "timeseries",
   "description": "If error budget is decreasing over time, it means that your service is spending its error budget faster than it's earning it back.\n\nIf error budget is increasing over time, you're not spending too much of your error budget.",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n\t\t# omit NaN by comparing to Infinity\n\t\tsum(sum_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"} < 1e308)[28d:5m]))\n\t\t/ sum(sum_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"} < 1e308)[28d:5m]))\n\t\t- on() grafana_slo_objective{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"}\n\t)\n\t/ on () (1 - grafana_slo_objective{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Error Budget",
   "type": "stat",
   "description": "The unspent error budget over the last {0.8 28d} Window",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\t\t# omit NaN by comparing to Infinity\n\t\tsum(sum_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"} < 1e308)[28d:5m]))\n\t\t/ sum(sum_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"} < 1e308)[28d:5m]))\n\t\t- on() grafana_slo_objective{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"}\n\t)\n\t/ on () (1 - grafana_slo_objective{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget Burn Rate",
   "type": "timeseries",
   "description": "The burn rate is the rate that this SLO is spending its error budget over last 5 min [0, 1.0]. A 1x burn rate will consume the entire error budget allotted for that period.",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg without(__grafana_origin) (1 - avg_over_time((grafana_slo_sli_5m{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"} < 1e308)[$__interval:]))\n/ on(grafana_slo_uuid) group_left() avg without(__grafana_origin) (1 - avg_over_time((grafana_slo_objective{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"} < 1e308)[$__interval:]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "((1 - ((sum(rate(app_frontend_requests{status=\"200\",target=\"/api/data\"}[$__rate_interval] offset 2m)) or 0 * sum(rate(app_frontend_requests{target=\"/api/data\"}[$__rate_interval] offset 2m))) / sum(rate(app_frontend_requests{target=\"/api/data\"}[$__rate_interval] offset 2m)))) / (1 - 0.8)) AND timestamp(sum(rate(app_frontend_requests{target=\"/api/data\"}[$__rate_interval] offset 2m))) < 1715357796",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Burn Rate",
   "type": "stat",
   "description": "The burn rate is the rate that this SLO is spending its error budget over last 5 min [0, 1.0]. A 1x burn rate will consume the entire error budget allotted for that period.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(__grafana_origin) (1 - avg_over_time((grafana_slo_sli_5m{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"} < 1e308)[$__interval:]))\n/ on(grafana_slo_uuid) group_left() avg without(__grafana_origin) (1 - avg_over_time((grafana_slo_objective{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"} < 1e308)[$__interval:]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sift Investigations", "type": "grafana-sift-panel", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 22 } },
  {
   "title": "Event Rate",
   "type": "timeseries",
   "description": "Total Rate (for SLIs that compare rate of successful events to rate of total events, this is the latter)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (grafana_slo_uuid) (grafana_slo_total_rate_5m{grafana_slo_uuid=\"qdofmxzsvh9xh9adq2baf\"})"
    },
    {
     "expr": "(sum(rate(app_frontend_requests{target=\"/api/data\"}[$__rate_interval] offset 2m))) AND timestamp(sum(rate(app_frontend_requests{target=\"/api/data\"}[$__rate_interval] offset 2m))) < 1715357796"
    }
   ]
  }
 ]
}