{
 "title": "RED Services",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_count,job)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_count{job=\"$job\"},service)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_count{job=\"$job\"},service_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\".*\"} [$__rate_interval])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\".*\", status_code=\"STATUS_CODE_ERROR\"} [$__rate_interval])) by (job) OR sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\".*\"} [$__rate_interval])) by (job) * 0) / sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\".*\"} [$__rate_interval])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\".*\"} [$__rate_interval])) by (le,job))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "nodeGraph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "limit": 20,
     "serviceMapQuery": "{client=\"$service\",client_service_namespace=\"$namespace\",client_deployment_environment=~\".*\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "count_over_time({job=\"$job\", container!~\"istio-proxy|vault-agent\"} [$__auto])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "{job=\"$job\"}"
    }
   ]
  },
  { "title": "Downstream & Databases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_service_graph_request_total{client=\"$service\", client_deployment_environment=~\".*\", client_service_namespace=\"$namespace\"} [$__rate_interval])) by (server, server_service_namespace)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(traces_service_graph_request_failed_total{client=\"$service\", client_deployment_environment=~\".*\", client_service_namespace=\"$namespace\"} [$__rate_interval])) by (server, server_service_namespace) OR sum(rate(traces_service_graph_request_total{client=\"$service\", client_deployment_environment=~\".*\", client_service_namespace=\"$namespace\"} [$__rate_interval])) by (server, server_service_namespace) * 0) / sum(rate(traces_service_graph_request_total{client=\"$service\", client_deployment_environment=~\".*\", client_service_namespace=\"$namespace\"} [$__rate_interval])) by (server, server_service_namespace)"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_service_graph_request_client_seconds_bucket{client=\"$service\", client_deployment_environment=~\".*\", client_service_namespace=\"$namespace\"} [$__rate_interval] offset 2m)) by (le, server, server_service_namespace))"
    }
   ]
  }
 ]
}