{
 "title": "Service Latency SLO v5da6fs9y5h94hq236d04",
 "tags": [ "slo" ],
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(grafana_slo_sli_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 0 },
   "options": {
    "content": "# Service Latency SLO SLO\nLatency SLO grouped by service. The SLI is a percentage of requests with latency under 1 second. If 100% SLI then all requests are under 1 second. Target is to maintain 95% requests under 1 second across all services"
   }
  },
  {
   "title": "Time Window",
   "type": "stat",
   "description": "The time window over which the service level objective is being measured over",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(vector(1), \"time_period\", \"28d\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "stat",
   "description": "The SLO's Objective value. Always between 0 and 100%",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(0.95)", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\", grafana_slo_severity=\"critical\"}) OR on() vector(0)",
     "legendFormat": "Critical alert"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "description": "Service level indicator",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(avg_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\",service=~\"$service\"} < 1e308)[$__interval:]))\n/ sum(avg_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\",service=~\"$service\"} < 1e308)[$__interval:]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "((sum(rate(traces_spanmetrics_latency_bucket{le=\"1\",service!=\"test-case-server\",service=~\"$service\"}[$__rate_interval] offset 2m)) or 0 * sum(rate(traces_spanmetrics_latency_bucket{le=\"+Inf\",service!=\"test-case-server\",service=~\"$service\"}[$__rate_interval] offset 2m))) / sum(rate(traces_spanmetrics_latency_bucket{le=\"+Inf\",service!=\"test-case-server\",service=~\"$service\"}[$__rate_interval] offset 2m))) AND timestamp(sum(rate(traces_spanmetrics_latency_bucket{le=\"+Inf\",service!=\"test-case-server\",service=~\"$service\"}[$__rate_interval] offset 2m))) < 1715359843",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI (last 28d)",
   "type": "stat",
   "description": "Service level indicator's value over the last 28d",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# omit NaN by comparing to Infinity\nsum(sum_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\",service=~\"$service\"} < 1e308)[28d:5m]))\n/ sum(sum_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\",service=~\"$service\"} < 1e308)[28d:5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\", grafana_slo_severity=\"warning\"}) OR on() vector(0)",
     "legendFormat": "Warning alert"
    }
   ]
  },
  { "title": "Burn Rate Alerts", "type": "alertlist", "description": "All active alerts for this SLO", "gridPos": { "h": 10, "w": 5, "x": 0, "y": 8 } },
  {
   "title": "Error Budget Trend",
   "type": "timeseries",
   "description": "If error budget is decreasing over time, it means that your service is spending its error budget faster than it's earning it back.\n\nIf error budget is increasing over time, you're not spending too much of your error budget.",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n\t\t# omit NaN by comparing to Infinity\n\t\tsum(sum_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\",service=~\"$service\"} < 1e308)[28d:5m]))\n\t\t/ sum(sum_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\",service=~\"$service\"} < 1e308)[28d:5m]))\n\t\t- on() grafana_slo_objective{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\"}\n\t)\n\t/ on () (1 - grafana_slo_objective{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Error Budget",
   "type": "stat",
   "description": "The unspent error budget over the last {0.95 28d} Window",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\t\t# omit NaN by comparing to Infinity\n\t\tsum(sum_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\",service=~\"$service\"} < 1e308)[28d:5m]))\n\t\t/ sum(sum_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\",service=~\"$service\"} < 1e308)[28d:5m]))\n\t\t- on() grafana_slo_objective{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\"}\n\t)\n\t/ on () (1 - grafana_slo_objective{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget Burn Rate",
   "type": "timeseries",
   "description": "The burn rate is the rate that this SLO is spending its error budget over last 5 min [0, 1.0]. A 1x burn rate will consume the entire error budget allotted for that period.",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n\t1 - (sum(avg_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\",service=~\"$service\"} < 1e308)[$__interval:]))\n\t/ sum(avg_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\",service=~\"$service\"} < 1e308)[$__interval:])))\n)\n/ on() (1 - grafana_slo_objective{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\"})\n# omit NaN by comparing to Infinity\n < 1e+308",
     "legendFormat": "__auto"
    },
    {
     "expr": "((1 - ((sum(rate(traces_spanmetrics_latency_bucket{le=\"1\",service!=\"test-case-server\",service=~\"$service\"}[$__rate_interval] offset 2m)) or 0 * sum(rate(traces_spanmetrics_latency_bucket{le=\"+Inf\",service!=\"test-case-server\",service=~\"$service\"}[$__rate_interval] offset 2m))) / sum(rate(traces_spanmetrics_latency_bucket{le=\"+Inf\",service!=\"test-case-server\",service=~\"$service\"}[$__rate_interval] offset 2m)))) / (1 - 0.95)) AND timestamp(sum(rate(traces_spanmetrics_latency_bucket{le=\"+Inf\",service!=\"test-case-server\",service=~\"$service\"}[$__rate_interval] offset 2m))) < 1715359843",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Burn Rate",
   "type": "stat",
   "description": "The burn rate is the rate that this SLO is spending its error budget over last 5 min [0, 1.0]. A 1x burn rate will consume the entire error budget allotted for that period.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\t1 - (sum(avg_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\",service=~\"$service\"} < 1e308)[$__interval:]))\n\t/ sum(avg_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\",service=~\"$service\"} < 1e308)[$__interval:])))\n)\n/ on() (1 - grafana_slo_objective{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\"})\n# omit NaN by comparing to Infinity\n < 1e+308",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sift Investigations", "type": "grafana-sift-panel", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 22 } },
  {
   "title": "Comparing across 'service' (filtered view based on selected variables at top of dashboard)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "description": "Service level indicator",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (grafana_slo_uuid, service) (avg_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\",service=~\"$service\"} < 1e308)[$__interval:]))\n/ sum by (grafana_slo_uuid, service) (avg_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\",service=~\"$service\"} < 1e308)[$__interval:]))",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "((sum by (service) (rate(traces_spanmetrics_latency_bucket{le=\"1\",service!=\"test-case-server\",service=~\"$service\"}[$__rate_interval] offset 2m)) or 0 * sum by (service) (rate(traces_spanmetrics_latency_bucket{le=\"+Inf\",service!=\"test-case-server\",service=~\"$service\"}[$__rate_interval] offset 2m))) / sum by (service) (rate(traces_spanmetrics_latency_bucket{le=\"+Inf\",service!=\"test-case-server\",service=~\"$service\"}[$__rate_interval] offset 2m))) AND timestamp(sum by (service) (rate(traces_spanmetrics_latency_bucket{le=\"+Inf\",service!=\"test-case-server\",service=~\"$service\"}[$__rate_interval] offset 2m))) < 1715359843",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Rate",
   "type": "timeseries",
   "description": "Total Rate (for SLIs that compare rate of successful events to rate of total events, this is the latter)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (grafana_slo_uuid, service) (grafana_slo_total_rate_5m{grafana_slo_uuid=\"v5da6fs9y5h94hq236d04\",service=~\"$service\"})",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "(sum by (service) (rate(traces_spanmetrics_latency_bucket{le=\"+Inf\",service!=\"test-case-server\",service=~\"$service\"}[$__rate_interval] offset 2m))) AND timestamp(sum by (service) (rate(traces_spanmetrics_latency_bucket{le=\"+Inf\",service!=\"test-case-server\",service=~\"$service\"}[$__rate_interval] offset 2m))) < 1715359843",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}