{
 "title": "Channel Status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Channel Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ibmmq_channel_status_squash+0" },
    { "expr": "ibmmq_channel_status+0" }
   ]
  },
  {
   "title": "Channel Activity",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "ibmmq_channel_time_since_msg", "legendFormat": "{{channel}} [{{type}}]" },
    {
     "expr": "count by (channel, qmgr)(ibmmq_channel_status)",
     "legendFormat": "Count: {{channel}}@{{qmgr}}"
    }
   ]
  },
  {
   "title": "Channel Bytes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibmmq_channel_bytes_sent{type!=\"SVRCONN\"}",
     "legendFormat": "Byte Sent: {{channel}}[{{type}}]"
    },
    {
     "expr": "ibmmq_channel_bytes_rcvd{type!=\"SVRCONN\"}",
     "legendFormat": "Byte Rcvd: {{channel}}[{{type}}]"
    }
   ]
  },
  {
   "title": "Channel Messages",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibmmq_channel_messages{type!=\"SVRCONN\"}",
     "legendFormat": "Msg: {{channel}} [{{type}}]"
    },
    {
     "expr": "ibmmq_channel_buffers_sent{type!=\"SVRCONN\"}",
     "legendFormat": "Buf Sent: {{channel}}[{{type}}]"
    },
    {
     "expr": "ibmmq_channel_buffers_rcvd{type!=\"SVRCONN\"}",
     "legendFormat": "Buf Rcvd: {{channel}}[{{type}}]"
    }
   ]
  },
  {
   "title": "Network Transfer Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "ibmmq_channel_nettime_short", "legendFormat": "Short: {{channel}}" },
    { "expr": "ibmmq_channel_nettime_long", "legendFormat": "Long: {{channel}}" }
   ]
  },
  {
   "title": "Channel Batches",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibmmq_channel_batches{type!=\"SVRCONN\"}",
     "legendFormat": "Batches: {{channel}}"
    },
    { "expr": "ibmmq_channel_batchsz_short", "legendFormat": "BatchSz (short): {{channel}}" },
    { "expr": "ibmmq_channel_batchsz_long", "legendFormat": "BatchSz (long): {{channel}}" }
   ]
  },
  {
   "title": "Transmission Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "ibmmq_channel_xmitq_time_short{type=\"SENDER\"}",
     "legendFormat": "Short: {{channel}}"
    },
    {
     "expr": "ibmmq_channel_xmitq_time_long{type=\"SENDER\"}",
     "legendFormat": "Long: {{channel}}"
    }
   ]
  },
  {
   "title": "Channel Status Table Merged",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "ibmmq_channel_attribute_max_inst{type=\"SVRCONN\"} + 0",
     "legendFormat": "{{channel}}"
    },
    {
     "expr": "ibmmq_channel_attribute_max_instc{type=\"SVRCONN\"} + 0",
     "legendFormat": "{{channel}}"
    },
    {
     "expr": "ibmmq_channel_cur_inst{type=\"SVRCONN\"} + 0",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Channel Attributes table",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "ibmmq_channel_attribute_max_inst{type=\"SVRCONN\"} + 0",
     "legendFormat": "{{channel}}"
    },
    {
     "expr": "ibmmq_channel_attribute_max_instc{type=\"SVRCONN\"} + 0",
     "legendFormat": "{{channel}}"
    },
    {
     "expr": "ibmmq_channel_cur_inst{type=\"SVRCONN\"} + 0",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Total Active Channels",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": " count(ibmmq_channel_status_squash == 2) by (qmgr)"
    }
   ]
  },
  {
   "title": "Active Channels",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " count by (qmgr) (ibmmq_channel_status_squash==2) ",
     "legendFormat": "Channels:  {{qmgr}}"
    }
   ]
  }
 ]
}