{
 "title": "Synthetic Health Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "kansas-prod" }
  ]
 },
 "panels": [
  {
   "title": "All Checks",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(\r\n  sum by (instance, job, check_name)\r\n          (\r\n            rate(probe_all_success_sum{probe=~\".*\"}[$__rate_interval])\r\n            *\r\n            on (instance, job, probe, config_version)\r\n            group_left(check_name)\r\n            max by (instance, job, probe, config_version, check_name) (sm_check_info{check_name=~\".*\", region=~\".*\", label_deployment_environment=\"$env\" })\r\n          )\r\n  /\r\n  sum by (instance, check_name, job)\r\n          (\r\n            rate(probe_all_success_count{probe=~\".*\"}[$__rate_interval])\r\n            *\r\n            on (instance, job, probe, config_version) group_left(check_name) max by (instance, job, probe, config_version, check_name) (sm_check_info{check_name=~\".*\", region=~\".*\",  label_deployment_environment=\"$env\"})\r\n          )\r\n) * 100 or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n  sum by (instance, job, check_name)\r\n          (\r\n            rate(probe_all_duration_seconds_sum{probe=~\".*\"}[$__rate_interval])\r\n            *\r\n            on (instance, job, probe, config_version) group_left(check_name) max by (instance, job, probe, config_version, check_name) (sm_check_info{check_name=~\".*\", region=~\".*\",  label_deployment_environment=\"$env\"})\r\n          )\r\n  /\r\n   sum by (instance, job, check_name)\r\n          (\r\n            rate(probe_all_duration_seconds_count{probe=~\".*\"}[$__rate_interval])\r\n            *\r\n            on (instance, job, probe, config_version) group_left(check_name) max by (instance, job, probe, config_version, check_name) (sm_check_info{check_name=~\".*\", region=~\".*\",  label_deployment_environment=\"$env\"})\r\n          )\r\n) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "ceil(\r\n        sum by (instance, job, check_name)\r\n                (\r\n                  rate(probe_all_success_sum{probe=~\".*\"}[5m])\r\n                  *\r\n                  on (instance, job, probe, config_version) group_left(check_name) max by (instance, job, probe, config_version, check_name) (sm_check_info{check_name=~\".*\", region=~\".*\",  label_deployment_environment=\"$env\"})\r\n                )\r\n        /\r\n        sum by (instance, check_name, job)\r\n                (\r\n                  rate(probe_all_success_count{probe=~\".*\"}[5m])\r\n                  *\r\n                  on (instance, job, probe, config_version) group_left(check_name) max by (instance, job, probe, config_version, check_name) (sm_check_info{check_name=~\".*\", region=~\".*\",  label_deployment_environment=\"$env\"})\r\n                )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health Status History",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "\n    1 - (\n       sum by (job)\n          (\n            rate(probe_all_success_sum{probe=~\".*\"}[$__rate_interval])\n            *\n            on (instance, job, probe, config_version) group_left(check_name) max by (instance, job, probe, config_version, check_name) (sm_check_info{check_name=~\".*\", region=~\".*\", label_deployment_environment=\"$env\" })\n          )\n      /\n      sum by (job)\n          (\n            rate(probe_all_success_count{probe=~\".*\"}[$__rate_interval])\n            *\n            on (instance, job, probe, config_version) group_left(check_name) max by (instance, job, probe, config_version, check_name) (sm_check_info{check_name=~\".*\", region=~\".*\", label_deployment_environment=\"$env\" })\n          )\n    )\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Error Rate By Location",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (probe, geohash)\r\n      (\r\n        rate(probe_all_success_sum{probe=~\".*\"}[$__rate_interval])\r\n        *\r\n        on (instance, job, probe, config_version)\r\n        group_left(geohash)\r\n        max by (instance, job, probe, config_version, geohash)\r\n        (\r\n          (sm_check_info{check_name=~\".*\", region=~\".*\", label_deployment_environment=\"$env\"})  \r\n        )\r\n      )",
     "legendFormat": "numerator"
    },
    {
     "expr": "sum by (probe, geohash)\r\n      (\r\n        rate(probe_all_success_count{probe=~\".*\"}[$__rate_interval])\r\n          *\r\n        on (instance, job, probe, config_version)\r\n        group_left(geohash)\r\n        max by (instance, job, probe, config_version, geohash)\r\n        (sm_check_info{check_name=~\".*\", region=~\".*\", label_deployment_environment=\"$env\"})\r\n      )",
     "legendFormat": "denominator"
    }
   ]
  },
  {
   "title": "All Check Error Percentage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(\r\n      rate(probe_all_success_sum{probe=~\".*\"}[$__rate_interval])\r\n      * \r\n      on (\r\n        instance, job, probe, config_version\r\n      ) \r\n      group_left\r\n      max(\r\n        sm_check_info{check_name=~\".*\", region=~\".*\", label_deployment_environment=\"$env\" }\r\n      ) \r\n      by (instance, job, probe, config_version)\r\n    ) \r\n    by (job, instance) \r\n    / \r\n    sum(\r\n      rate(\r\n        probe_all_success_count{probe=~\".*\"}[$__rate_interval])\r\n        * \r\n        on (\r\n          instance, job, probe, config_version\r\n        ) \r\n        group_left \r\n        max(\r\n          sm_check_info{check_name=~\".*\", region=~\".*\", label_deployment_environment=\"$env\" }\r\n        ) \r\n        by (\r\n          instance, job, probe, config_version\r\n        )\r\n      ) \r\n    by (job, instance)",
     "legendFormat": "{{job}}/{{instance}}"
    }
   ]
  },
  {
   "title": "All Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "\r\n(\r\n  sum(\r\n    rate(probe_all_duration_seconds_sum{probe=~\".*\"}[$__rate_interval])\r\n    * on (instance, job, probe, config_version) group_left max(sm_check_info{check_name=~\".*\", region=~\".*\", label_deployment_environment=\"$env\"})\r\n    by (instance, job, probe, config_version)\r\n  )\r\n  by (job, instance)\r\n)\r\n/\r\n(\r\n  sum(\r\n    rate(probe_all_duration_seconds_count{probe=~\".*\"}[$__rate_interval])\r\n    * on (instance, job, probe, config_version) group_left max(sm_check_info{check_name=~\".*\", region=~\".*\", label_deployment_environment=\"$env\"})\r\n    by (instance, job, probe, config_version)\r\n  )\r\n  by (job, instance)\r\n)\r\n        ",
     "legendFormat": "{{job}}/{{instance}}"
    }
   ]
  }
 ]
}