{
 "title": "Synthetic Health Drilldown",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "PGP Gateway" },
   { "name": "env", "label": "Environment", "query": "kansas-prod" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 \r\n  style=\"color: white; font-weight: bold; font-size: 70px; font-family: 'Poppins', sans-serif;\">\r\n  ${job}\r\n</h1>\r\n"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# the inner query is going to produce a non-zero value if there was at least one successful check during the 5 minute window\r\n        # so make it a 1 if there was at least one success and a 0 otherwise\r\n        ceil(\r\n          # the number of successes across all probes\r\n          sum by (instance, job) (increase(probe_all_success_sum{job=`${job}`}[$__rate_interval]))\r\n          /\r\n          # the total number of times we checked across all probes\r\n          (sum by (instance, job) (increase(probe_all_success_count{job=`${job}`}[$__rate_interval])) + 1) # + 1 because we want to make sure it goes to 1, not 2\r\n        )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reachability",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(probe_all_success_sum{job=\"${job}\", probe=~\".*\"}[$__rate_interval]))\r\n  /\r\n  sum(rate(probe_all_success_count{job=\"${job}\", probe=~\".*\"}[$__rate_interval]))\r\n) * 100 or vector(0)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(probe_all_duration_seconds_sum{probe=~\".*\", job=`${job}`}[$__rate_interval])) / sum(rate(probe_all_duration_seconds_count{probe=~\".*\", job=`${job}`}[$__rate_interval]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(min(probe_ssl_earliest_cert_expiry{probe=~\".*\", job=`${job}`}) - time()) / (86400)"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (frequency) (\r\n          topk(\r\n              1,\r\n              sm_check_info{job=`${job}`, probe=~\".*\"}\r\n          )\r\n        )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate by probe",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (probe, geohash)\r\n      (\r\n        rate(probe_all_success_sum{job=`${job}`, probe=~\".*\"}[$__rate_interval])\r\n        *\r\n        on (instance, job, probe, config_version)\r\n        group_left(geohash)\r\n        max by (instance, job, probe, config_version, geohash)\r\n        (\r\n          sm_check_info{job=`${job}`}\r\n        )\r\n      )",
     "legendFormat": "numerator"
    },
    {
     "expr": "sum by (probe, geohash)\r\n      (\r\n        rate(probe_all_success_count{job=`${job}`, probe=~\".*\"}[$__rate_interval])\r\n          *\r\n        on (instance, job, probe, config_version)\r\n        group_left(geohash)\r\n        max by (instance, job, probe, config_version, geohash)\r\n        (\r\n          sm_check_info{job=`${job}`}\r\n        )\r\n      )",
     "legendFormat": "denominator"
    }
   ]
  },
  {
   "title": "Error Rate: $job",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 17, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "\r\n    1 - (\r\n      sum by (probe) (\r\n        rate(probe_all_success_sum{probe=~\".*\", job=`${job}`}[$__rate_interval])\r\n      )\r\n      /\r\n      sum by (probe) (\r\n        rate(probe_all_success_count{probe=~\".*\", job=`${job}`}[$__rate_interval])\r\n      )\r\n    )\r\n",
     "legendFormat": "{{probe}}"
    }
   ]
  },
  {
   "title": "Response latency by phase",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(probe_http_duration_seconds{probe=~\".*\", job=`${job}`}) by (phase)",
     "legendFormat": "{{probe}}"
    }
   ]
  },
  {
   "title": "Response latency by probe",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{probe=~\".*\", job=`${job}`} * on (instance, job,probe,config_version) group_left probe_success{probe=~\".*\", job=`${job}`} > 0) by (probe)",
     "legendFormat": "{{probe}}"
    }
   ]
  },
  {
   "title": "Logs for failed checks: $job",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{probe=~\".*\", job=`${job}`, probe_success=\"0\"}"
    }
   ]
  }
 ]
}