{
 "title": "IBM MQ cluster overview",
 "tags": [ "ibm-mq-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ibmmq_qmgr_commit_count,job)"
   },
   {
    "name": "mq_cluster",
    "label": "MQ cluster",
    "query": "label_values(ibmmq_qmgr_commit_count,mq_cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Clusters",
   "type": "stat",
   "description": "The unique number of clusters being reported.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ibmmq_qmgr_commit_count{job=~\"$job\"}) by (mq_cluster))",
     "legendFormat": "{{job}} - {{mq_cluster}}"
    }
   ]
  },
  {
   "title": "Queue managers",
   "type": "stat",
   "description": "The unique number of queue managers in the cluster being reported.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ibmmq_qmgr_commit_count{job=~\"$job\"}) by (qmgr, mq_cluster))"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "description": "The unique number of topics in the cluster.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ibmmq_topic_messages_received{job=~\"$job\"}) by (topic, mq_cluster))",
     "legendFormat": "{{job}} - {{mq_cluster}}"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "stat",
   "description": "The unique number of queues in the cluster.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ibmmq_queue_depth{job=~\"$job\"}) by (queue, mq_cluster))"
    }
   ]
  },
  {
   "title": "Queue operations",
   "type": "piechart",
   "description": "The number of queue operations of the cluster. ",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "operations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqset_count{mq_cluster=~\"$mq_cluster\", job=~\"$job\"})",
     "legendFormat": "MQSET"
    },
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqinq_count{mq_cluster=~\"$mq_cluster\", job=~\"$job\"})",
     "legendFormat": "MQINQ"
    },
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqget_count{mq_cluster=~\"$mq_cluster\", job=~\"$job\"})",
     "legendFormat": "MQGET"
    },
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqopen_count{mq_cluster=~\"$mq_cluster\", job=~\"$job\"})",
     "legendFormat": "MQOPEN"
    },
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqclose_count{mq_cluster=~\"$mq_cluster\", job=~\"$job\"})",
     "legendFormat": "MQCLOSE"
    },
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqput_mqput1_count{mq_cluster=~\"$mq_cluster\", job=~\"$job\"})",
     "legendFormat": "MQPUT/MQPUT1"
    }
   ]
  },
  {
   "title": "Cluster status",
   "type": "table",
   "description": "The status of the cluster.",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "ibmmq_cluster_suspend{mq_cluster=~\"$mq_cluster\", job=~\"$job\"}",
     "legendFormat": "{{job}} - {{mq_cluster}}"
    }
   ]
  },
  {
   "title": "Queue manager status",
   "type": "table",
   "description": "The queue managers of the cluster displayed in a table.",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "ibmmq_qmgr_status{mq_cluster=~\"$mq_cluster\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Transmission queue time",
   "type": "timeseries",
   "description": "The time it takes for the messages to get through the transmission queue. (Long) - total time taken for messages to be transmitted over the channel, (Short) - an average, minimum, or maximum time taken to transmit messages over the channel in recent intervals.  ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "ibmmq_channel_xmitq_time_short{type=\"SENDER\",job=~\"$job\", mq_cluster=~\"$mq_cluster\"}",
     "legendFormat": "{{channel}} - short"
    },
    {
     "expr": "ibmmq_channel_xmitq_time_long{type=~\"SENDER\", job=~\"$job\", mq_cluster=~\"$mq_cluster\"}",
     "legendFormat": "{{channel}} - long"
    }
   ]
  }
 ]
}