{
 "title": "Health",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_count{deployment_environment=\"$env\"},job)"
    }
   },
   { "name": "env", "query": "kansas-prod" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_count{service_namespace!=\"mgmt\"},service_namespace)"
    }
   },
   {
    "name": "ILP_Cluster",
    "label": "ILP Cluster",
    "query": {
     "query": "label_values(kube_node_status_capacity{deployment_environment=\"$env\", cluster=~\".*-ilp-.*\"},cluster)"
    }
   },
   {
    "name": "CGS_Cluster",
    "label": "CGS Cluster",
    "query": {
     "query": "label_values(kube_node_status_capacity{deployment_environment=\"$env\", cluster=~\".*-cgs-.*\"},cluster)"
    }
   },
   {
    "name": "PMV_Cluster",
    "label": "PMV Cluster",
    "query": {
     "query": "label_values(kube_node_status_capacity{deployment_environment=\"$env\", cluster=~\".*-pmv-.*\"},cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace: $namespace",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "repeat": "namespace",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job, service_namespace) (rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", service_namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", service_namespace=\"$namespace\", status_code=\"STATUS_CODE_ERROR\"} [$__rate_interval])) by (job, service_namespace) OR sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\",  service_namespace=\"$namespace\"} [$__rate_interval])) by (job, service_namespace) * 0) / sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\",  service_namespace=\"$namespace\"} [$__rate_interval])) by (job, service_namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", service_namespace=\"$namespace\"} [$__rate_interval])) by (le,job, service_namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "<h1><p style=\"text-align:center;\">3rd Party Synthetics</p></h1>\n\n"
   }
  },
  {
   "title": "Reachability",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (instance, job, check_name)\r\n          (\r\n            rate(probe_all_success_sum{probe=~\".*\"}[$__rate_interval])\r\n            *\r\n            on (instance, job, probe, config_version)\r\n            group_left(check_name)\r\n            max by (instance, job, probe, config_version, check_name) (sm_check_info{check_name=~\".*\", region=~\".*\", label_deployment_environment=\"$env\" })\r\n          )\r\n  /\r\n  sum by (instance, check_name, job)\r\n          (\r\n            rate(probe_all_success_count{probe=~\".*\"}[$__rate_interval])\r\n            *\r\n            on (instance, job, probe, config_version) group_left(check_name) max by (instance, job, probe, config_version, check_name) (sm_check_info{check_name=~\".*\", region=~\".*\",  label_deployment_environment=\"$env\"})\r\n          )\r\n) * 100 or vector(0)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
     "options": {
      "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n     <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \">\n       <span style=\"font-size:25px\"><b><a href=\"/d/e1RXnCbVzprod/kubernetes-dashboard?${__url_time_range}\" target=\"_blank\">Kubernetes Dashboard</a></b></span><br \\>\n     </td>\n</table>"
     }
    },
    {
     "title": "My-Cluster Alerts Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "count by(labels_alertname) (rate({instance_id=\"793527\"} | json | current = `Alerting` | labels_alertname =~ `Kube.*` [$__auto]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
     "options": {
      "content": "<div style=\"display: flex;\">\n  <div style=\"width: 50%; padding: 20px; text-align: center;\">\n    <table style=\"width: 100%; border-collapse: collapse;\">\n      <tr>\n        <th style=\"border: 1px solid #ddd; padding: 10px;\">Number of Alerts</th>\n        <td style=\"border: 1px solid #ddd; padding: 10px;\">Greater than 5</td>\n        <td style=\"border: 1px solid #ddd; padding: 10px;\">Between 2 to 5</td>\n        <td style=\"border: 1px solid #ddd; padding: 10px;\">Between 1 to 2</td>\n        <td style=\"border: 1px solid #ddd; padding: 10px;\">Less than 1</td>\n      </tr>\n      <tr>\n        <th style=\"border: 1px solid #ddd; padding: 10px;\">Color</th>\n        <td style=\"border: 1px solid #ddd; padding: 10px; background-color: rgb(242, 73, 92); color: black;\">Red</td>\n        <td style=\"border: 1px solid #ddd; padding: 10px; background-color: rgb(255, 152, 48); color: black;\">Orange</td>\n        <td style=\"border: 1px solid #ddd; padding: 10px; background-color: rgb(250, 222, 42); color: black;\">Yellow</td>\n        <td style=\"border: 1px solid #ddd; padding: 10px; background-color: rgb(115, 191, 105); color: black;\">Green</td>\n      </tr>\n    </table>\n  </div>\n</div>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "count by(labels_alertname, ruleUID) (rate({instance_id=\"793527\"} | json | current = `Alerting` | labels_service != `` [$__auto]))"
      }
     ]
    }
   ]
  },
  {
   "title": "SLO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 25 PROD Internal Service Availability SLI",
     "type": "gauge",
     "description": "Error budgets allow for a certain amount of failure when measuring the performance of a service. It is a measurement of the difference between actual and desired performance.\n\nLink to Documentation on SLO in Grafana:\nhttps://grafana.com/docs/grafana-cloud/alerting-and-irm/slo/introduction/#error-budget",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "frame": {
        "fields": [
         {
          "config": {},
          "name": "Cart",
          "type": "number",
          "values": [
           0.99
          ]
         }
        ],
        "meta": {},
        "name": "SLO"
       }
      }
     ]
    },
    {
     "title": "Top 25 PROD Internal Service 95th Percentile Latency SLI",
     "type": "gauge",
     "description": "Error budgets allow for a certain amount of failure when measuring the performance of a service. It is a measurement of the difference between actual and desired performance.\n\nLink to Documentation on SLO in Grafana:\nhttps://grafana.com/docs/grafana-cloud/alerting-and-irm/slo/introduction/#error-budget",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "frame": {
        "fields": [
         {
          "config": {},
          "name": "SLI",
          "type": "number",
          "values": [
           0.99
          ]
         }
        ],
        "meta": {},
        "name": "SLO"
       }
      }
     ]
    }
   ]
  }
 ]
}