{
 "title": "Citrix Cloud Status",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_citrix_status_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Affected",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_citrix_status_affected", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_citrix_status_down", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Available Regions For Citrix Cloud Services",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "probe_citrix_status{group=\"Citrix Cloud Services\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Regions For Platform Services",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "probe_citrix_status{group=\"Platform Services\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "marcusolsson-calendar-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "events",
     "source": "url",
     "type": "json",
     "url": " https://status.cloud.com/api/calendar?date=2024-07-16T05:00:00.000Z&all_statuses=true",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}