{
 "title": "IGM Overview",
 "panels": [
  { "title": "ServiceNow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Incidents - Grouped",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "displayValue": "all",
     "fields": [
      { "aggregates": [ "count" ], "name": "state" }
     ],
     "filters": [
      {
       "conjunction": "and",
       "field": "active",
       "op": "=",
       "type": "unknown",
       "value": "true"
      },
      {}
     ],
     "groupBy": [ "priority" ],
     "limit": 25,
     "sort": [
      {}
     ],
     "stats": [ "count" ],
     "table": "incident",
     "timeField": "ignore_time"
    }
   ]
  },
  {
   "title": "Active Changes - Grouped",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "displayValue": "all",
     "fields": [
      { "aggregates": [ "count" ], "name": "state" }
     ],
     "filters": [
      {
       "conjunction": "and",
       "field": "active",
       "fieldDesc": {
        "choice": "0",
        "choice_field": "",
        "choice_table": "",
        "description": "Task",
        "element": "active",
        "internal_type": {
         "link": "https://optimizincdemo1.service-now.com/api/now/v2/table/sys_glide_object?name=boolean",
         "value": "boolean"
        },
        "label": "Active",
        "name": "task",
        "reference": { "display_value": "", "link": "", "value": "" },
        "sys_name": "Active",
        "table": "task",
        "value": "active"
       },
       "op": "=",
       "type": "boolean",
       "value": "True"
      },
      {}
     ],
     "groupBy": [ "state" ],
     "limit": 25,
     "sort": [
      {}
     ],
     "stats": [ "count" ],
     "table": "change_request",
     "timeField": "ignore_time"
    }
   ]
  },
  { "title": "Citrix Cloud Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Available Regions For Citrix Cloud Services",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "probe_citrix_status{group=\"Citrix Cloud Services\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Regions For Platform Services",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "probe_citrix_status{group=\"Platform Services\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Citrix Workspace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total Machines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} | json machineId = \"machineId\" | machineId != \"\""
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json userId = \"userId\" | userId != \"\""
    }
   ]
  },
  {
   "title": "Total Sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json sessionKey = \"sessionKey\" | sessionKey != \"\""
    }
   ]
  },
  {
   "title": "Session count by state",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json sessionKey = \"sessionKey\", sessionState = \"sessionState\" | sessionKey != \"\" | label_format state=`\r\n    {{ if eq .sessionState \"1\"}} Connected\r\n    {{ else if eq .sessionState \"2\"}} Disconnected\r\n    {{ else if eq .sessionState \"3\"}} Terminated\r\n    {{ else if eq .sessionState \"5\"}} Active\r\n    {{ else if eq .sessionState \"6\"}} Reconnecting\r\n    {{ else }} Other\r\n    {{end}}`"
    }
   ]
  },
  {
   "title": "Machine count by state",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} | json machineId = \"machineId\", machineName=\"machineName\", machinePowerState = \"machinePowerState\", machineActualStatus=\"machineActualStatus\", status=\"status\", isMaintenanceMode=\"isMaintenanceMode\", isUnregistered=\"isUnregistered\", activeSessionCount=\"activeSessionCount\" | machineId != \"\"\r\n| label_format \r\n    finalState = `\r\n      {{ if eq .status \"1\" }} Unregistered\r\n      {{ else if eq .status \"4\" }} Failed\r\n      {{ else if or (eq .status \"3\") (and (eq .status \"5\") (gt .isMaintenanceMode \"0\")) }} Maintenance\r\n      {{ else if and (eq .status \"2\") (gt .activeSessionCount \"0\") }} Active\r\n      {{ else if or (and (eq .status \"5\") (eq .isMaintenanceMode \"0\")) (and (eq .status \"2\") (eq .activeSessionCount \"0\")) }} Ready for Use\r\n      {{ else }} Other\r\n      {{end}}`"
    }
   ]
  },
  {
   "title": "Users and Sessions (HDX only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 27 },
   "targets": [
    {
     "expr": "sum(count by (userId) (count_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json userId = \"userId\" | userId != \"\" [5m])))",
     "legendFormat": "Users"
    },
    {
     "expr": "sum(count by (sessionKey) (count_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json sessionKey = \"sessionKey\" | sessionKey != \"\" [5m])))",
     "legendFormat": "Sessions"
    }
   ]
  }
 ]
}