{
 "title": "Performance Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "KafkaJob",
    "label": "Job Name",
    "query": {}
   },
   {
    "name": "SiteName",
    "label": "Site",
    "query": {}
   },
   {
    "name": "DeliveryGroup",
    "label": "Delivery Group",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "ServiceNow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incidents",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "displayValue": "all",
     "fields": [
      {
       "aggregates": [],
       "name": "number"
      },
      {
       "aggregates": [],
       "name": "short_description"
      },
      {
       "aggregates": [],
       "name": "priority"
      },
      {
       "aggregates": [],
       "name": "state"
      }
     ],
     "filters": [
      { "conjunction": "and" }
     ],
     "limit": 25,
     "sort": [
      { "field": "number", "order": "desc" },
      {}
     ],
     "table": "incident",
     "timeField": "ignore_time"
    }
   ]
  },
  {
   "title": "Changes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "displayValue": "all",
     "fields": [
      {
       "aggregates": [],
       "name": "number"
      },
      {
       "aggregates": [],
       "name": "short_description"
      },
      {
       "aggregates": [],
       "name": "priority"
      },
      {
       "aggregates": [],
       "name": "state"
      }
     ],
     "filters": [
      { "conjunction": "and" }
     ],
     "limit": 25,
     "sort": [
      { "field": "number", "order": "desc" },
      {}
     ],
     "table": "change_request",
     "timeField": "ignore_time"
    }
   ]
  },
  {
   "title": "Open Changes - Grouped",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "displayValue": "all",
     "fields": [
      { "aggregates": [ "count" ], "name": "state" }
     ],
     "filters": [
      {
       "conjunction": "and",
       "field": "active",
       "op": "=",
       "type": "unknown",
       "value": "true"
      },
      {}
     ],
     "groupBy": [ "priority" ],
     "limit": 25,
     "sort": [
      {}
     ],
     "stats": [ "count" ],
     "table": "change_request",
     "timeField": "ignore_time"
    }
   ]
  },
  {
   "title": "Open Incidents - Grouped",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [ "state" ],
     "filter": [
      { "field": "active", "op": "=", "value": "true" }
     ],
     "groupBy": [ "priority" ],
     "limit": 25,
     "method": "AggregateAPI",
     "stats": [ "count" ],
     "timeField": "ignore_time",
     "type": "inc"
    }
   ]
  },
  { "title": "Citrix Workspace Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json userId = \"userId\" | userId != \"\""
    }
   ]
  },
  {
   "title": "Total Sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json sessionKey = \"sessionKey\" | sessionKey != \"\""
    }
   ]
  },
  {
   "title": "Session count by state",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json sessionKey = \"sessionKey\", sessionState = \"sessionState\" | sessionKey != \"\" | label_format state=`\r\n    {{ if eq .sessionState \"1\"}} Connected\r\n    {{ else if eq .sessionState \"2\"}} Disconnected\r\n    {{ else if eq .sessionState \"3\"}} Terminated\r\n    {{ else if eq .sessionState \"5\"}} Active\r\n    {{ else if eq .sessionState \"6\"}} Reconnecting\r\n    {{ else }} Other\r\n    {{end}}`"
    }
   ]
  },
  {
   "title": "Session count by protocol",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json sessionKey = \"sessionKey\" | sessionKey != \"\""
    }
   ]
  },
  {
   "title": "Users and Sessions (HDX only)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(count by (userId) (count_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json userId = \"userId\" | userId != \"\" [5m])))",
     "legendFormat": "Users"
    },
    {
     "expr": "sum(count by (sessionKey) (count_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json sessionKey = \"sessionKey\" | sessionKey != \"\" [5m])))",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "Session count by delivery group",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json sessionKey = \"sessionKey\", deliveryGroupName = \"deliveryGroupName\" | deliveryGroupName != \"\""
    }
   ]
  },
  {
   "title": "Session count by country",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json sessionKey = \"sessionKey\", endpointLocationCountry = \"endpointLocationCountry\" | sessionKey != \"\" | label_format country=`\r\n    {{ if eq .endpointLocationCountry \"\"}} Unknown\r\n    {{ else }} {{.endpointLocationCountry}}\r\n    {{end}}`"
    }
   ]
  },
  {
   "title": "Session count by Endpoint OS",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json sessionKey = \"sessionKey\", endpointOS = \"endpointOS\" | sessionKey != \"\" | label_format os=`\r\n    {{ if eq .endpointOS \"\"}} Unknown\r\n    {{ else }} {{.endpointOS}}\r\n    {{end}}`"
    }
   ]
  },
  {
   "title": "Session failures by failure code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "count by (failureCodeString) (count_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} \r\n| json failureCode = \"failureCode\", failureCodeString=\"failureCodeString\" \r\n| failureCode != \"\" [5m]))",
     "legendFormat": "{{experience}}"
    }
   ]
  },
  {
   "title": "Session failures by failure code and reason",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} \r\n| json failureCode = \"failureCode\", failureCodeString=\"failureCodeString\", failureReasonString=\"failureReasonString\", sessionKey=\"sessionKey\"\r\n| failureCode != \"\"",
     "legendFormat": "{{experience}}"
    }
   ]
  },
  {
   "title": "Session failures by failure code and delivery group",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 42 },
   "targets": [
    {
     "expr": "{eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} \r\n| json failureCode = \"failureCode\", failureCodeString=\"failureCodeString\", failureReasonString=\"failureReasonString\", sessionKey=\"sessionKey\"\r\n| failureCode != \"\"",
     "legendFormat": "{{experience}}"
    }
   ]
  },
  {
   "title": "Max / Avg Session Logon Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(quantile_over_time(0.95, {eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json logonDuration = \"logonDuration\", sessionLaunchStatus=\"sessionLaunchStatus\" | logonDuration > 0 and sessionLaunchStatus = 0 | unwrap logonDuration [5m]))",
     "legendFormat": "Max Logon Duration"
    },
    {
     "expr": "avg(avg_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json logonDuration = \"logonDuration\", sessionLaunchStatus=\"sessionLaunchStatus\" | logonDuration > 0 and sessionLaunchStatus = 0 | unwrap logonDuration [5m]))",
     "legendFormat": "Average Logon Duration"
    }
   ]
  },
  {
   "title": "Max / Avg Session Responsiveness (ICARTT)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(max_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json icaRtt = \"icaRtt\", sessionLaunchStatus=\"sessionLaunchStatus\" | icaRtt > 0 and sessionLaunchStatus = 0 | unwrap icaRtt [5m]))",
     "legendFormat": "Max ICARTT"
    },
    {
     "expr": "avg(avg_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} | json icaRtt = \"icaRtt\", sessionLaunchStatus=\"sessionLaunchStatus\" | icaRtt > 0 and sessionLaunchStatus = 0 | unwrap icaRtt [5m]))",
     "legendFormat": "Average ICARTT"
    }
   ]
  },
  {
   "title": "Avg Session Logon Duration breakdown",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(avg_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} \r\n| json authenticationDuration = \"authenticationDuration\", sessionLaunchStatus=\"sessionLaunchStatus\" \r\n| authenticationDuration > 0 and sessionLaunchStatus = 0 \r\n| unwrap authenticationDuration [5m]))",
     "legendFormat": "Authentication"
    },
    {
     "expr": "avg(avg_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} \r\n| json brokeringDuration = \"brokeringDuration\", sessionLaunchStatus=\"sessionLaunchStatus\" \r\n| brokeringDuration > 0 and sessionLaunchStatus = 0 \r\n| unwrap brokeringDuration [5m]))",
     "legendFormat": "Brokering"
    },
    {
     "expr": "avg(avg_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} \r\n| json vmStartDuration = \"vmStartDuration\", sessionLaunchStatus=\"sessionLaunchStatus\" \r\n| vmStartDuration > 0 and sessionLaunchStatus = 0\r\n| unwrap vmStartDuration [5m]))",
     "legendFormat": "VM Start"
    },
    {
     "expr": "avg(avg_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} \r\n| json profileLoadDuration = \"profileLoadDuration\", sessionLaunchStatus=\"sessionLaunchStatus\" \r\n| profileLoadDuration > 0 and sessionLaunchStatus = 0\r\n| unwrap profileLoadDuration [5m]))",
     "legendFormat": "Profile Load"
    },
    {
     "expr": "avg(avg_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} \r\n| json hdxConnectionDuration = \"hdxConnectionDuration\", sessionLaunchStatus=\"sessionLaunchStatus\" \r\n| hdxConnectionDuration > 0 and sessionLaunchStatus = 0\r\n| unwrap hdxConnectionDuration [5m]))",
     "legendFormat": "HDX Connection"
    },
    {
     "expr": "avg(avg_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} \r\n| json interactiveSessionsDuration = \"interactiveSessionsDuration\", sessionLaunchStatus=\"sessionLaunchStatus\" \r\n| interactiveSessionsDuration > 0 and sessionLaunchStatus = 0\r\n| unwrap interactiveSessionsDuration [5m]))",
     "legendFormat": "Interactive Sessions"
    },
    {
     "expr": "avg(avg_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} \r\n| json gpoDuration = \"gpoDuration\", sessionLaunchStatus=\"sessionLaunchStatus\" \r\n| gpoDuration > 0 and sessionLaunchStatus = 0\r\n| unwrap gpoDuration [5m]))",
     "legendFormat": "GPO"
    },
    {
     "expr": "avg(avg_over_time({eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"} \r\n| json logonScriptsDuration = \"logonScriptsDuration\", sessionLaunchStatus=\"sessionLaunchStatus\" \r\n| logonScriptsDuration > 0 and sessionLaunchStatus = 0\r\n| unwrap logonScriptsDuration [5m]))",
     "legendFormat": "Logon Scripts"
    }
   ]
  },
  {
   "title": "Avg Logon Duration by Delivery Group",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "{eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"}\r\n| json sessionKey = \"sessionKey\", logonDuration=\"logonDuration\", sessionLaunchStatus = \"sessionLaunchStatus\"\r\n| logonDuration != \"\" and sessionLaunchStatus = 0",
     "legendFormat": "{{deliveryGroupName}}"
    }
   ]
  },
  {
   "title": "Avg Session Responsiveness by Delivery Group",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{eventType=\"Session\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\"}\r\n| json sessionKey = \"sessionKey\", icaRtt=\"icaRtt\", sessionLaunchStatus = \"sessionLaunchStatus\"\r\n| icaRtt != \"\" and sessionLaunchStatus = 0",
     "legendFormat": "{{deliveryGroupName}}"
    }
   ]
  }
 ]
}