{
 "title": "Solace brokers",
 "description": "Analyse solace PubSub+ VPNs",
 "tags": [
  "solace",
  "broker"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "stage",
    "label": "Stage",
    "query": "label_values(up{group=\"Solace\"}, stage)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(solace_up,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "status $instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "solace_up{instance=~\"$instance\",job=~\".*solace[0-9]*_std.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "client connections",
   "type": "bargauge",
   "description": "Clients simultaneously connected to a given Message VPN through all supported services",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "solace_vpn_connections{instance=~\"$instance.*\",vpn_name!~\"#.*\",group=\"Solace\"}",
     "legendFormat": " {{vpn_name}}"
    }
   ]
  },
  {
   "title": "mate link latency",
   "type": "bargauge",
   "description": "measured latency on message HA replication",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_system_mate_link_latency_avg_seconds{instance=~\"$instance.*\",vpn_name!~\"#.*\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "disk latency",
   "type": "bargauge",
   "description": "measured latency on persistence for guaranteed messages",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_system_disk_latency_avg_seconds{instance=~\"$instance.*\",vpn_name!~\"#.*\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "compute latency",
   "type": "bargauge",
   "description": "measured latency for CPU instructions ",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_system_compute_latency_avg_seconds{instance=~\"$instance.*\",vpn_name!~\"#.*\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "Transfer volume IN",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(solace_vpn_rx_bytes_total{instance=~\"$instance.*\",vpn_name!~\"^#.+\"}[5m])",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "Transfer volume OUT",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(irate(solace_vpn_tx_bytes_total{instance=~\"$instance.*\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  }
 ]
}