{
 "title": "Solace brokers Copy",
 "description": "Analyse solace PubSub+ VPNs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "stage",
    "label": "Stage",
    "query": "label_values(up{group=\"Solace\"}, stage)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(solace_up,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Brokers Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "status $instance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "solace_up{instance=~\"$instance\",job=~\".*solace[0-9]*_std.*\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  { "title": "Solace Broker Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 } },
  { "title": "Event Brokers Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "$instance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "solace_up{instance=~\"$instance\",job=~\".*solace[0-9]*_std.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Critical Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 19 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(solace_not_up{instance=\"$instance\"} == 1)",
     "legendFormat": "Solace Not Up"
    },
    {
     "expr": "count(solace_spool_msg_usg_critical{instance=\"$instance\"} == 1)",
     "legendFormat": "Spooled Message Usage"
    }
   ]
  },
  {
   "title": "Warning Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 19 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(solace_spool_msg_usg_warning{instance=\"$instance\"} == 1)",
     "legendFormat": "Solace Not Up"
    },
    {
     "expr": "count(solace_spool_msg_usg_critical{instance=\"$instance\"} == 1)",
     "legendFormat": "Spooled Message Usage"
    }
   ]
  },
  {
   "title": "Connections Count",
   "type": "stat",
   "description": "Client Connections Count, per Vpn. Drill down into Vpn available",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 19 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solace_vpn_connections{instance=\"$instance\"}",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "disk latency",
   "type": "gauge",
   "description": "latency for disk read/write operations",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 19 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solace_system_disk_latency_avg_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "compute latency",
   "type": "gauge",
   "description": "latency for CPU instructions  on the broker",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 19 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solace_system_compute_latency_cur_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spool Messages",
   "type": "timeseries",
   "description": "Number of spooled messages on the broker, against max. quota of spool available",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 19 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solace_vpn_spool_usage_msgs{instance=\"$instance\"}",
     "legendFormat": "Spool msgs usage"
    },
    {
     "expr": "solace_system_spool_quota_msgs{instance=\"$instance\"}",
     "legendFormat": "Spool msgs quota"
    }
   ]
  }
 ]
}