{
 "title": "Solace bridges",
 "tags": [
  "solace",
  "bridge"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{group=\"Solace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bridge Admin Status",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(solace_bridge_admin_state{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "Bridge Admin Status History",
   "type": "flant-statusmap-panel",
   "description": "Bridge Status: <<listing name of bridge - vpn name>> where the bridge is deployed to.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "label_replace(solace_bridge_admin_state{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{bridge_name}} - {{vpn_name}}"
    }
   ]
  },
  { "title": "Operational State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Inbound",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "label_replace(solace_bridge_inbound_operational_state{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{bridge_name}} - {{vpn_name}}"
    }
   ]
  },
  {
   "title": "Outbound",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "label_replace(solace_bridge_outbound_operational_state{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{bridge_name}} - {{vpn_name}}"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "label_replace(solace_bridge_queue_operational_state{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{bridge_name}} - {{vpn_name}}"
    }
   ]
  },
  { "title": "Bridges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_bridges_num_total_bridges{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_bridges_num_local_bridges{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_bridges_num_remote_bridges{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "Total Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(solace_bridges_num_total_remote_bridge_subscriptions{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "Current"
    },
    {
     "expr": "label_replace(solace_bridges_max_num_total_remote_bridge_subscriptions{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "Max "
    }
   ]
  }
 ]
}