{
 "title": "Solace bridge",
 "tags": [
  "solace",
  "bridge"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(solace_up{group=\"Solace\"}, instance)"
    }
   },
   {
    "name": "vpn_name",
    "label": "VPN",
    "query": {
     "query": "label_values(solace_bridge_admin_state{instance=\"$instance\"}, vpn_name)"
    }
   },
   {
    "name": "bridge_name",
    "label": "Bridge",
    "query": {
     "query": "label_values(solace_bridge_admin_state{instance=\"$instance\",vpn_name=\"$vpn_name\"}, bridge_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Operational State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Admin State",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(solace_bridge_admin_state{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}, \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Connection up time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_bridge_connection_uptime_in_seconds{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}, \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "Connection Establisher",
   "type": "stat",
   "description": "which side is initiating the bridge connection",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_bridge_connection_establisher{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}, \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "Connection Establisher"
    }
   ]
  },
  {
   "title": "Redundancy Connection",
   "type": "stat",
   "description": "connection setup when connecting to redundancy pair",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_bridge_redundancy{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}, \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "Connection Establisher"
    }
   ]
  },
  {
   "title": "Inbound Operational Failure Reason",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_bridge_inbound_operational_failure_reason{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}, \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "Connection Establisher"
    }
   ]
  },
  {
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "label_replace(solace_bridge_inbound_operational_state{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}, \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")\r\n",
     "legendFormat": "Inbound"
    },
    {
     "expr": "label_replace(solace_bridge_outbound_operational_state{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}, \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")\r\n",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "label_replace(solace_bridge_queue_operational_state{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}, \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")\r\n",
     "legendFormat": "Queue"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Subscribers: Count / Slow",
   "type": "timeseries",
   "description": "Number of subscribers and percentage slow subscribers",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(solace_bridge_client_num_subscriptions{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}, \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")\r\n",
     "legendFormat": "Subscriber"
    },
    {
     "expr": "label_replace(solace_bridge_client_slow_subscriber{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}, \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")\r",
     "legendFormat": "Is Slow Subscriber"
    }
   ]
  },
  {
   "title": "Transfer Messages / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(irate(solace_bridge_total_client_messages_received{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}[5m]), \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")\r",
     "legendFormat": "Ingress"
    },
    {
     "expr": "label_replace(irate(solace_bridge_total_client_messages_sent{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}[5m]), \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")\r",
     "legendFormat": "Egress"
    }
   ]
  },
  {
   "title": "Transfer Volume / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(irate(solace_bridge_total_client_bytes_received{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}[5m]), \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")\r",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "label_replace(irate(solace_bridge_total_client_bytess_sent{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}[5m]), \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")\r",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Discards",
   "type": "timeseries",
   "description": "Discarded messages on ingress and egress",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(irate(solace_bridge_total_ingress_discards{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}[5m]), \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")\r",
     "legendFormat": "Ingress discards"
    },
    {
     "expr": "label_replace(irate(solace_bridge_total_egress_discards{instance=\"$instance\",vpn_name=\"$vpn_name\",bridge_name=\"$bridge_name\"}[5m]), \"bridge_short\", \"$1\", \"bridge_name\", \"([\\\\w\\\\-]+).*\")\r",
     "legendFormat": "Egress discards"
    }
   ]
  }
 ]
}