{
 "title": "osama_L2/3 Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "Move Money,Signon,SSO,,Accounts,OTVC,Preferences,Database,Profiles"
   },
   { "name": "transaction_id", "label": "Transaction ID" },
   { "name": "card_number", "label": "Card Number" },
   { "name": "splunk_search", "label": "Splunk Search" }
  ]
 },
 "panels": [
  {
   "title": "Dynatrace Problems (ServiceNow - incidents and change) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dynatrace Problems",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "active": "problem",
       "metric": {
        "aggregations": [],
        "alias": "",
        "cleanSelector": "",
        "displayName": "",
        "filters": {
         "conjunction": "AND",
         "filters": []
        },
        "name": "Select...",
        "selector": "",
        "transformations": [
         {
          "name": "names",
          "params": []
         }
        ],
        "zones": []
       },
       "mode": "builder",
       "problem": {
        "expandDetails": true,
        "impact": "",
        "severity": "",
        "status": "OPEN",
        "tags": []
       },
       "version": "3.11.3"
      }
     ]
    },
    {
     "title": "ServiceNow Incidents",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "spreadsheet": "1Bzi2V-0KWkJPXooeARAKSyF_1Rw-2_E-5-BnJQJ1o4s"
      }
     ]
    },
    {
     "title": "ServiceNow Change Records (last 3 days)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "spreadsheet": "1Bzi2V-0KWkJPXooeARAKSyF_1Rw-2_E-5-BnJQJ1o4s"
      }
     ]
    }
   ]
  },
  { "title": "KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Client Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Response Error Rate (Splunk)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gateway Error Rate (Splunk)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response Time (Dynatrace)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service Level Availability (Dynatrce) ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status Codes from Splunk  (Pie charts)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Splunk Audit Index",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "displayMode": "detect",
       "index": "select index",
       "metricAggs": [
        { "alias": "", "field": "select field", "func": "avg" }
       ],
       "options": {
        "cont": true,
        "partial": true
       },
       "query": "index=\"ebnk_audit\"| top limit=20 status",
       "sourcetype": "select sourcetype",
       "tcOptions": {
        "nullstr": "",
        "otherstr": "",
        "span": "auto",
        "usenull": false,
        "useother": true
       },
       "whereClause": { "value": "" }
      }
     ]
    },
    {
     "title": "Splunk Gateway Index",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 6, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "displayMode": "detect",
       "index": "select index",
       "metricAggs": [
        { "alias": "", "field": "select field", "func": "avg" }
       ],
       "options": {
        "cont": true,
        "partial": true
       },
       "query": "index=\"ebnk_gateway\"| top limit=20 statuscode",
       "sourcetype": "select sourcetype",
       "tcOptions": {
        "nullstr": "",
        "otherstr": "",
        "span": "auto",
        "usenull": false,
        "useother": true
       },
       "whereClause": { "value": "" }
      }
     ]
    },
    {
     "title": "Splunk Module Request Response Index",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 11, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "displayMode": "detect",
       "index": "select index",
       "metricAggs": [
        { "alias": "", "field": "select field", "func": "avg" }
       ],
       "options": {
        "cont": true,
        "partial": true
       },
       "query": "index=\"ebnk_module_request_response\"| top limit=20 status",
       "sourcetype": "select sourcetype",
       "tcOptions": {
        "nullstr": "",
        "otherstr": "",
        "span": "auto",
        "usenull": false,
        "useother": true
       },
       "whereClause": { "value": "" }
      }
     ]
    },
    {
     "title": "Splunk Module Request Response Index",
     "type": "piechart",
     "description": "Custom Codes",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "displayMode": "detect",
       "index": "select index",
       "metricAggs": [
        { "alias": "", "field": "select field", "func": "avg" }
       ],
       "options": {
        "cont": true,
        "partial": true
       },
       "query": "index=\"ebnk_module_request_response\"| top limit=20 customstatus",
       "sourcetype": "select sourcetype",
       "tcOptions": {
        "nullstr": "",
        "otherstr": "",
        "span": "auto",
        "usenull": false,
        "useother": true
       },
       "whereClause": { "value": "" }
      },
      {
       "frame": {
        "fields": [
         {
          "config": {},
          "name": "customstatus",
          "type": "number",
          "values": [
           123,
           345,
           567
          ]
         },
         {
          "config": {},
          "name": "message",
          "type": "string",
          "values": [
           "Request Successful",
           "Fraud Activity Error",
           "User Submitted Incorrect OTVC"
          ]
         }
        ],
        "meta": {},
        "name": "Custom Codes Table"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Platform KPIs (Db response, JVM, F5,..etc)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "F5 Response Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database Response Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Splunk Logs (audit file, request/response. gateway)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "ebnk_audit",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "displayMode": "detect",
       "index": "select index",
       "metricAggs": [
        { "alias": "", "field": "select field", "func": "avg" }
       ],
       "options": {
        "cont": true,
        "partial": true
       },
       "query": "index=\"ebnk_audit\" \"$transaction_id\" \"$card_number\" \"$splunk_search\"",
       "sourcetype": "select sourcetype",
       "tcOptions": {
        "nullstr": "",
        "otherstr": "",
        "span": "auto",
        "usenull": false,
        "useother": true
       },
       "whereClause": { "value": "" }
      }
     ]
    },
    {
     "title": "ebnk_gateway",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "displayMode": "detect",
       "index": "select index",
       "metricAggs": [
        { "alias": "", "field": "select field", "func": "avg" }
       ],
       "options": {
        "cont": true,
        "partial": true
       },
       "query": "index=\"ebnk_gateway\" \"$transaction_id\" \"$card_number\" \"$splunk_search\"",
       "sourcetype": "select sourcetype",
       "tcOptions": {
        "nullstr": "",
        "otherstr": "",
        "span": "auto",
        "usenull": false,
        "useother": true
       },
       "whereClause": { "value": "" }
      }
     ]
    },
    {
     "title": "ebnk_module_request_response",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "displayMode": "detect",
       "index": "select index",
       "metricAggs": [
        { "alias": "", "field": "select field", "func": "avg" }
       ],
       "options": {
        "cont": true,
        "partial": true
       },
       "query": "index=\"ebnk_module_request_response\" \"$transaction_id\" \"$card_number\" \"$splunk_search\"",
       "sourcetype": "select sourcetype",
       "tcOptions": {
        "nullstr": "",
        "otherstr": "",
        "span": "auto",
        "usenull": false,
        "useother": true
       },
       "whereClause": { "value": "" }
      }
     ]
    }
   ]
  }
 ]
}