{
 "title": "OSAMA_IVR Synthetic Main Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Tags", "label": "Tag", "query": { "query": "label_values(tags)" } },
   {
    "name": "Statuses",
    "label": "Test Name",
    "query": {
     "query": "label_values(job_status{tags=~\".*$Tags.*\"},name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total Successful Tests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "job_status{tags=~\".*$Tags.*\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failed Tests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "job_status{tags=~\".*$Tags.*\"} == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Tests Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "job_status{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "job_status{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Call Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "job_duration{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Call Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "job_cost{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Call Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "job_duration{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Call Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "job_cost{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contact Center Test Availability",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "job_status{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "job_cost{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    },
    {
     "expr": "job_duration{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ServiceNow Incidents",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "displayValue": "all",
     "fields": [
      {
       "aggregates": [],
       "name": "number"
      },
      {
       "aggregates": [],
       "name": "cmdb_ci.name"
      },
      {
       "aggregates": [],
       "name": "priority"
      },
      {
       "aggregates": [],
       "name": "description"
      }
     ],
     "filters": [
      {
       "conjunction": "and",
       "field": "description",
       "fieldDesc": {
        "choice": "0",
        "choice_field": "",
        "choice_table": "",
        "description": "Task",
        "element": "description",
        "internal_type": {
         "link": "https://optimizincdemo1.service-now.com/api/now/v2/table/sys_glide_object?name=string",
         "value": "string"
        },
        "label": "Description",
        "name": "task",
        "reference": { "display_value": "", "link": "", "value": "" },
        "sys_name": "Description",
        "table": "task",
        "value": "description"
       },
       "op": "LIKE",
       "type": "string",
       "value": "job_status"
      },
      {}
     ],
     "limit": 25,
     "sort": [
      {}
     ],
     "table": "incident",
     "timeField": "sys_created_on"
    }
   ]
  },
  {
   "title": "Tests Health Overtime",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "job_status{tags=~\".*$Tags.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Call Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Call Logs",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{job=\"test-case-server\"} | json test=\"attributes.JOB_NAME\" | test =~ `$Statuses`"
    }
   ]
  },
  {
   "title": "Call Traces & Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Call Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "{job=\"test-case-server\"} | json test=\"attributes.JOB_NAME\" | test =~ `$Statuses`"
      }
     ]
    }
   ]
  }
 ]
}