{
 "title": "RBC_IVR Synthetic Main Dashboard - Elastic",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "Tags", "label": "Tag" },
   { "name": "Test_Name", "label": "Test Name" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Tests Availability",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "Total Tests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "Average Call Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "Average Call Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "Total Call Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "Total Call Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "Total Successful Tests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "status:SUCCESS",
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "Total Failed Tests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "status:FAILURE",
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "Tests Health Over Time",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "Contact Center Test Availability",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "Test Breakdown",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "start_time"
    }
   ]
  },
  { "title": "Call Traces & Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Elastic Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "Call Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "ServiceNow Incidents",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "displayValue": "all",
       "fields": [
        {
         "aggregates": [],
         "name": "number"
        },
        {
         "aggregates": [],
         "name": "cmdb_ci.name"
        },
        {
         "aggregates": [],
         "name": "priority"
        },
        {
         "aggregates": [],
         "name": "description"
        }
       ],
       "filters": [
        {
         "conjunction": "and",
         "field": "description",
         "fieldDesc": {
          "choice": "0",
          "choice_field": "",
          "choice_table": "",
          "description": "Task",
          "element": "description",
          "internal_type": {
           "link": "https://optimizincdemo1.service-now.com/api/now/v2/table/sys_glide_object?name=string",
           "value": "string"
          },
          "label": "Description",
          "name": "task",
          "reference": { "display_value": "", "link": "", "value": "" },
          "sys_name": "Description",
          "table": "task",
          "value": "description"
         },
         "op": "LIKE",
         "type": "string",
         "value": "job_status"
        },
        {}
       ],
       "limit": 25,
       "sort": [
        {}
       ],
       "table": "incident",
       "timeField": "sys_created_on"
      }
     ]
    },
    {
     "title": "Call Logs",
     "type": "table",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "{job=\"test-case-server\"} | json test=\"attributes.JOB_NAME\" | test =~ `$Statuses`"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "timeField": "start_time"
      }
     ]
    }
   ]
  }
 ]
}