{
 "title": "Logs",
 "time": { "from": "2024-06-13T05:00:00.000Z", "to": "2024-06-28T04:59:59.000Z" },
 "panels": [
  {
   "title": "Investigation Cases Created Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"ibm_sp\" source=\"*audit_event_log*\" \"investigation_case\" \"created\"\n| rex field=_raw \"(?<date>\\d{4}-\\d{2}-\\d{2}_\\d{2}-\\d{2})\" \n| stats count by date",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "Logins per SP Instance",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"ibm_sp\" source=\"*audit_event_log*\" \"Login successful\"\n| stats count by host\n| rename count as \"Number of Logins\"\n| sort - \"Number of Logins\"",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "Investigation Cases Created per Day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"ibm_sp\" source=\"*audit_event_log*\" \"investigation_case\" \"created\"\n| rex field=_raw \"(?<date>\\d{4}-\\d{2}-\\d{2})\" \n| stats count by date",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "Logins by IP",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "partial": true
     },
     "query": "index=\"ibm_sp\" source=\"*audit_event_log*\" \"Login successful\"\n| rex field=_raw \"IP: (?<ip_address>\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})\"\n| stats count by ip_address\n| rename count as \"Number of Logins\"\n| sort - \"Number of Logins\"",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "Audit Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "limit": 500,
      "partial": true
     },
     "query": "index=\"ibm_sp\" source=\"*audit_event_log*\"",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "System Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "limit": 500,
      "partial": true
     },
     "query": "index=\"ibm_sp\" source=\"*system_event*\"",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  },
  {
   "title": "Back Traces",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "displayMode": "detect",
     "index": "select index",
     "metricAggs": [
      { "alias": "", "field": "select field", "func": "avg" }
     ],
     "options": {
      "cont": true,
      "limit": 500,
      "partial": true
     },
     "query": "index=\"ibm_sp\" source=\"*backtraces*\"",
     "sourcetype": "select sourcetype",
     "tcOptions": {
      "nullstr": "",
      "otherstr": "",
      "span": "auto",
      "usenull": false,
      "useother": true
     },
     "whereClause": { "value": "" }
    }
   ]
  }
 ]
}