{
 "title": "__RED Services",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_count{deployment_environment=\"$env\"},job)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_count{job=\"$job\"},service)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_count{job=\"$job\"},service_namespace)"
    }
   },
   { "name": "env", "label": "Environment", "query": "appd-migration" }
  ]
 },
 "panels": [
  { "title": "Main Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\"$env\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\"$env\", status_code=\"STATUS_CODE_ERROR\"} [$__rate_interval])) by (job) OR sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\"$env\"} [$__rate_interval])) by (job) * 0) / sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\"$env\"} [$__rate_interval])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\"$env\"} [$__rate_interval])) by (le,job))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "filters": [
      {
       "id": "3456a8ec",
       "operator": "=",
       "scope": "resource",
       "tag": "service.namespace",
       "value": [ "ilp" ],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "access" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"$service\" && resource.service.namespace=\"$namespace\" && status=error && resource.deployment.environment=\"$env\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "All Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "filters": [
      {
       "id": "3456a8ec",
       "operator": "=",
       "scope": "resource",
       "tag": "service.namespace",
       "value": [ "ilp" ],
       "valueType": "string"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "access" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"$service\" && resource.service.namespace=\"$namespace\" && resource.deployment.environment=\"$env\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "type": "nodeGraph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "limit": 20,
     "serviceMapQuery": "{client=\"$service\",client_service_namespace=\"$namespace\",client_deployment_environment=~\"kansas-staging\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Count: of ERROR",
     "type": "stat",
     "description": "Total Count: of $searchable_pattern in the specified time range",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({job=\"$job\",deployment_environment=\"$env\"} | json | __error__=`` | level = `ERROR` [$__interval]))"
      }
     ]
    },
    {
     "title": "Breakdown of ERROR Logs",
     "type": "table",
     "description": "Live logs is a like 'tail -f' in a real time",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 43 },
     "targets": [
      {
       "expr": "count by(message) (rate({job=\"$job\", deployment_environment=~\"$env\"} | json | level = `ERROR` | __error__=`` [$__auto]))"
      }
     ]
    },
    {
     "title": "Total Count: of WARN",
     "type": "stat",
     "description": "Total Count: of $searchable_pattern in the specified time range",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({job=\"$job\", deployment_environment=\"$env\"} | json | __error__=`` | level = `WARN` [$__interval]))"
      }
     ]
    },
    {
     "title": "Breakdown of WARN Logs",
     "type": "table",
     "description": "Live logs is a like 'tail -f' in a real time",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 82 },
     "targets": [
      {
       "expr": "count by(message) (rate({job=\"$job\", deployment_environment=\"$env\"} | json | level = `WARN` | __error__=`` [$__auto]))"
      }
     ]
    },
    {
     "title": "Total Count: of INFO",
     "type": "stat",
     "description": "Total Count: of $searchable_pattern in the specified time range",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({job=\"$job\", deployment_environment=\"$env\"} | json | level = `INFO` [$__interval]))"
      }
     ]
    },
    {
     "title": "Breakdown of INFO Logs",
     "type": "table",
     "description": "Live logs is a like 'tail -f' in a real time",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 89 },
     "targets": [
      {
       "expr": "count by(message) (rate({job=\"$job\", deployment_environment=\"$env\"} | json | level = `INFO` | __error__=`` [$__auto]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
     "targets": [
      {
       "expr": "{job=\"$job\", container!~\"vault-agent|istio-proxy\", deployment_environment=\"$env\"}"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 103 },
     "targets": [
      {
       "expr": "count(rate({job=\"$job\", container!~\"istio-proxy|vault-agent\", deployment_environment=\"$env\"} [$__auto]))",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Downstream & Databases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downstream",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "sum(rate(traces_service_graph_request_total{client=\"$service\", client_deployment_environment=~\"$env\", client_service_namespace=\"$namespace\"} [$__rate_interval])) by (server, server_service_namespace)",
       "legendFormat": "{{span_name}} Rate"
      },
      {
       "expr": "(sum(rate(traces_service_graph_request_failed_total{client=\"$service\", client_deployment_environment=~\"$env\", client_service_namespace=\"$namespace\"} [$__rate_interval])) by (server, server_service_namespace) OR sum(rate(traces_service_graph_request_total{client=\"$service\", client_deployment_environment=~\"$env\", client_service_namespace=\"$namespace\"} [$__rate_interval])) by (server, server_service_namespace) * 0) / sum(rate(traces_service_graph_request_total{client=\"$service\", client_deployment_environment=~\"$env\", client_service_namespace=\"$namespace\"} [$__rate_interval])) by (server, server_service_namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(traces_service_graph_request_client_seconds_bucket{client=\"$service\", client_deployment_environment=~\"$env\", client_service_namespace=\"$namespace\"} [$__rate_interval] offset 2m)) by (le, server, server_service_namespace))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(traces_service_graph_request_total{client=\"$service\", client_deployment_environment=~\"$env\", client_service_namespace=\"$namespace\"} [$__rate_interval])) by (server, server_service_namespace)"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(rate(traces_service_graph_request_failed_total{client=\"$service\", client_deployment_environment=~\"$env\", client_service_namespace=\"$namespace\"} [$__rate_interval])) by (server, server_service_namespace) OR sum(rate(traces_service_graph_request_total{client=\"$service\", client_deployment_environment=~\"$env\", client_service_namespace=\"$namespace\"} [$__rate_interval])) by (server, server_service_namespace) * 0) / sum(rate(traces_service_graph_request_total{client=\"$service\", client_deployment_environment=~\"$env\", client_service_namespace=\"$namespace\"} [$__rate_interval])) by (server, server_service_namespace)"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(traces_service_graph_request_client_seconds_bucket{client=\"$service\", client_deployment_environment=~\"$env\", client_service_namespace=\"$namespace\"} [$__rate_interval] offset 2m)) by (le, server, server_service_namespace))"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum(rate(traces_service_graph_request_total{server=\"$service\", server_deployment_environment=~\"$env\", server_service_namespace=\"$namespace\", client!=\"user\"} [$__rate_interval])) by (client, client_service_namespace)",
       "legendFormat": "{{span_name}} Rate"
      },
      {
       "expr": "(sum(rate(traces_service_graph_request_failed_total{server=\"$service\", server_deployment_environment=~\"$env\", server_service_namespace=\"$namespace\", client!=\"user\"} [$__rate_interval])) by (client, client_service_namespace) OR sum(rate(traces_service_graph_request_total{server=\"$service\", server_deployment_environment=~\"$env\", server_service_namespace=\"$namespace\", client!=\"user\"} [$__rate_interval])) by (client, client_service_namespace) * 0) / sum(rate(traces_service_graph_request_total{server=\"$service\", server_deployment_environment=~\"$env\", server_service_namespace=\"$namespace\", client!=\"user\"} [$__rate_interval])) by (client, client_service_namespace)",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(traces_service_graph_request_server_seconds_bucket{server=\"$service\", server_deployment_environment=~\"$env\", server_service_namespace=\"$namespace\", client!=\"user\"} [$__rate_interval])) by (le, client, client_service_namespace))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(traces_service_graph_request_total{server=\"$service\", server_deployment_environment=~\"$env\", server_service_namespace=\"$namespace\", client!=\"user\"} [$__rate_interval])) by (client, client_service_namespace)"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(rate(traces_service_graph_request_failed_total{server=\"$service\", server_deployment_environment=~\"$env\", server_service_namespace=\"$namespace\", client!=\"user\"} [$__rate_interval])) by (client, client_service_namespace) OR sum(rate(traces_service_graph_request_total{server=\"$service\", server_deployment_environment=~\"$env\", server_service_namespace=\"$namespace\", client!=\"user\"} [$__rate_interval])) by (client, client_service_namespace) * 0) / sum(rate(traces_service_graph_request_total{server=\"$service\", server_deployment_environment=~\"$env\", server_service_namespace=\"$namespace\", client!=\"user\"} [$__rate_interval])) by (client, client_service_namespace)"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(traces_service_graph_request_server_seconds_bucket{server=\"$service\", server_deployment_environment=~\"$env\", server_service_namespace=\"$namespace\", client!=\"user\"} [$__rate_interval])) by (le, client, client_service_namespace))"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\"$env\"} [$__rate_interval])) by (le,span_name))",
       "legendFormat": "{{span_name}} Duration"
      },
      {
       "expr": "(sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\"$env\", status_code=\"STATUS_CODE_ERROR\"} [$__rate_interval])) by (span_name) OR sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\"$env\"} [$__rate_interval])) by (span_name) * 0) / sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\"$env\"} [$__rate_interval])) by (span_name)",
       "legendFormat": "{{span_name}} Errors"
      },
      {
       "expr": "sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\"$env\"} [$__rate_interval])) by (span_name)",
       "legendFormat": "{{span_name}} Rate"
      }
     ]
    },
    {
     "title": "Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\"$env\"} [$__rate_interval])) by (span_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\"$env\", status_code=\"STATUS_CODE_ERROR\"} [$__rate_interval])) by (span_name) OR sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\"$env\"} [$__rate_interval])) by (span_name) * 0) / sum(rate(traces_spanmetrics_latency_count{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\"$env\"} [$__rate_interval])) by (span_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\", job=\"$job\", deployment_environment=~\"$env\"} [$__rate_interval])) by (le,span_name))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}