{
 "title": "AppDTools_Draft",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Severity",
    "label": "Severity",
    "query": "SELECT topSeverity FROM AppDSearchData"
   },
   {
    "name": "Application",
    "label": "Application Name",
    "query": "SELECT eventApplication FROM AppDSearchData"
   },
   {
    "name": "HealthRuleName",
    "label": "Health Rule Name",
    "query": "SELECT eventHealthRuleName FROM AppDSearchData"
   },
   {
    "name": "Source",
    "label": "Source",
    "query": "SELECT source FROM AppDSearchData"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AppDSearch",
     "rawSql": "SELECT\r\n  COUNT(topSeverity) AS error_count\r\nFROM [AppDSearch].dbo.AppDSearchData\r\n\r\n"
    }
   ]
  },
  {
   "title": "The Severity Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "AppDSearch",
     "rawSql": "SELECT \r\n    topSeverity, \r\n    COUNT(*) AS count\r\nFROM [AppDSearch].[dbo].[AppDSearchData]\r\nGROUP BY topSeverity;\r\n"
    }
   ]
  },
  {
   "title": "Severity Breakdown for Specific Application",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "AppDSearch",
     "rawSql": "SELECT \r\n    eventApplication, \r\n    topSeverity, \r\n    COUNT(*) AS severity_count\r\nFROM [AppDSearch].[dbo].[AppDSearchData]\r\nWHERE eventApplication in($Application) AND topSeverity IN($Severity) AND source IN ($Source)\r\nGROUP BY eventApplication, topSeverity\r\nORDER BY  severity_count DESC;\r\n"
    }
   ]
  },
  {
   "title": "5 Most Violated Health Rules",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "AppDSearch",
     "rawSql": "SELECT TOP(5) COUNT(*) AS \"Violation Count\", eventHealthRuleName FROM [AppDSearch].dbo.AppDSearchData GROUP BY eventHealthRuleName ORDER BY COUNT(*) DESC "
    }
   ]
  },
  {
   "title": "Error Distribution by Health Rule ",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "AppDSearch",
     "rawSql": "SELECT TOP(50) eventHealthRuleName, COUNT(*) as error_count\r\nFROM [AppDSearch].dbo.AppDSearchData\r\nWHERE topSeverity = 'ERROR' AND eventHealthRuleName IN ($HealthRuleName)  AND source IN ($Source)\r\nGROUP BY eventHealthRuleName\r\nORDER BY error_count DESC;"
    }
   ]
  },
  {
   "title": "Error Distribution by Source Type",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "AppDSearch",
     "rawSql": "SELECT TOP(50) source, COUNT(*) as error_count\r\nFROM [AppDSearch].dbo.AppDSearchData\r\nWHERE eventApplication in($Application) AND topSeverity IN($Severity) AND source IN ($Source)\r\nGROUP BY source\r\nORDER BY error_count DESC;"
    }
   ]
  },
  {
   "title": "Event Count By Severity",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "dataset": "AppDSearch",
     "rawSql": "SELECT TOP(50) COUNT(*) AS \"Event Count\", topSeverity FROM [AppDSearch].dbo.AppDSearchData GROUP BY topSeverity "
    }
   ]
  },
  {
   "title": "Top 5 Applications with most erros",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "dataset": "AppDSearch",
     "rawSql": "SELECT TOP 5\r\n    eventApplication,\r\n    topSeverity,\r\n    COUNT(*) AS error_count\r\nFROM [AppDSearch].[dbo].[AppDSearchData]\r\nWHERE topSeverity = 'ERROR'\r\nGROUP BY eventApplication, topSeverity\r\nORDER BY error_count DESC;\r\n"
    }
   ]
  },
  {
   "title": "Top 5 Health Rules with Most errors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "dataset": "AppDSearch",
     "rawSql": "SELECT TOP(5) COUNT(*) AS \"Error Count\", eventHealthRuleName FROM [AppDSearch].dbo.AppDSearchData WHERE topSeverity = 'Error' GROUP BY eventHealthRuleName ORDER BY COUNT(*) DESC "
    }
   ]
  }
 ]
}