{
 "title": "BIG-IP pool overview",
 "tags": [ "f5-bigip-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(bigip_pool_status_availability_state,job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bigip_pool_status_availability_state{job=~\"$job\"}, instance)"
   },
   {
    "name": "bigip_pool",
    "label": "BIG-IP pool",
    "query": "label_values(bigip_pool_status_availability_state{job=~\"$job\", instance=~\"$instance\"},pool)"
   },
   {
    "name": "bigip_partition",
    "label": "BIG-IP partition",
    "query": "label_values(bigip_pool_status_availability_state{job=~\"$job\", instance=~\"$instance\"},partition)"
   }
  ]
 },
 "panels": [
  {
   "title": "Availability status",
   "type": "table",
   "description": "The availability status of the pool.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bigip_pool_status_availability_state{job=~\"$job\", instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Requests / $__interval",
   "type": "timeseries",
   "description": "The number of requests made to the pool.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(bigip_pool_tot_requests{job=~\"$job\", instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}[$__interval:])",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Members",
   "type": "timeseries",
   "description": "The number of active and minimum required members within the pool.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bigip_pool_active_member_cnt{job=~\"$job\", instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{pool}} - {{instance}} - active"
    },
    {
     "expr": "bigip_pool_min_active_members{job=~\"$job\", instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{pool}} - {{instance}} - minimum"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "The current and maximum number of node connections within the pool.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bigip_pool_serverside_cur_conns{job=~\"$job\", instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{pool}} - {{instance}} - current"
    },
    {
     "expr": "bigip_pool_serverside_max_conns{job=~\"$job\", instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{pool}} - {{instance}} - maximum"
    }
   ]
  },
  {
   "title": "Connection queue depth",
   "type": "timeseries",
   "description": "The depth of connection queues within the pool, including the current depth.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bigip_pool_connq_depth{job=~\"$job\", instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Connection queue serviced / $__interval",
   "type": "timeseries",
   "description": "The number of connections that have been serviced within the pool.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(bigip_pool_connq_serviced{job=~\"$job\", instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}[$__interval:])",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Traffic inbound",
   "type": "timeseries",
   "description": "The rate of date received from virtual servers by the pool.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bigip_pool_serverside_bytes_in{job=~\"$job\", instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}[$__rate_interval])",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Traffic outbound",
   "type": "timeseries",
   "description": "The rate of date sent from virtual servers by the pool.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bigip_pool_serverside_bytes_out{job=~\"$job\", instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}[$__rate_interval])",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Packets inbound / $__interval",
   "type": "timeseries",
   "description": "The number of packets received from virtual servers by the pool.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(bigip_pool_serverside_pkts_out{job=~\"$job\", instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}[$__interval:])",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Packets outbound / $__interval",
   "type": "timeseries",
   "description": "The number of packets sent from virtual servers by the pool.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(bigip_pool_serverside_pkts_out{job=~\"$job\", instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}[$__interval:])",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  }
 ]
}