{
 "title": "BIG-IP cluster overview",
 "tags": [ "f5-bigip-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(bigip_node_status_availability_state,job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bigip_node_status_availability_state{job=~\"$job\"}, instance)"
   },
   { "name": "k", "label": "Top node count", "query": "5,10,20,50" },
   {
    "name": "bigip_partition",
    "label": "BIG-IP partition",
    "query": "label_values(bigip_node_status_availability_state{job=~\"$job\", instance=~\"$instance\", partition=~\"$bigip_partition\"},partition)"
   }
  ]
 },
 "panels": [
  { "title": "Integration Status", "type": "row", "gridPos": { "y": 0 } },
  {
   "title": "Metrics",
   "type": "stat",
   "description": "Shows if metrics are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$job\"}\n"
    }
   ]
  },
  {
   "title": "Latest metrics received",
   "type": "stat",
   "description": "Shows the timestamp of the latest metrics received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$job\"}\n"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "stat",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } }
  },
  {
   "title": "Node availability",
   "type": "gauge",
   "description": "The percentage of nodes available.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by(partition, instance, job) (bigip_node_status_availability_state{job=~\"$job\", instance=~\"$instance\", partition=~\"$bigip_partition\"})  / clamp_min(count by(partition, instance, job) (bigip_node_status_availability_state{job=~\"$job\", instance=~\"$instance\", partition=~\"$bigip_partition\"}),1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pool availability",
   "type": "gauge",
   "description": "The percentage of pools available.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by(partition, instance, job) (bigip_pool_status_availability_state{job=~\"$job\", instance=~\"$instance\", partition=~\"$bigip_partition\"}) / clamp_min(count by(partition, instance, job)  (bigip_pool_status_availability_state{job=~\"$job\", instance=~\"$instance\", partition=~\"$bigip_partition\"}),1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Virtual server availability",
   "type": "gauge",
   "description": "The percentage of virtual servers available.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by(partition, instance, job) (bigip_vs_status_availability_state{job=~\"$job\", instance=~\"$instance\", partition=~\"$bigip_partition\"}) / clamp_min(count by(partition, instance, job) (bigip_vs_status_availability_state{job=~\"$job\", instance=~\"$instance\", partition=~\"$bigip_partition\"}),1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top active server-side nodes",
   "type": "bargauge",
   "description": "Nodes with the highest number of active server-side connections.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($k, bigip_node_serverside_cur_conns{job=~\"$job\", instance=~\"$instance\", partition=~\"$bigip_partition\"})",
     "legendFormat": "{{node}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top outbound traffic nodes / $__interval",
   "type": "bargauge",
   "description": "Nodes with the highest outbound traffic.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($k, increase(bigip_node_serverside_bytes_out{job=~\"$job\", instance=~\"$instance\", partition=~\"$bigip_partition\"}[$__interval:]))",
     "legendFormat": "{{node}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top active members in pools",
   "type": "bargauge",
   "description": "Pools with the highest number of active members.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($k, bigip_pool_active_member_cnt{job=~\"$job\", instance=~\"$instance\", partition=~\"$bigip_partition\"})",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top requested pools / $__interval",
   "type": "bargauge",
   "description": "Pools with the highest number of requests.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($k, increase(bigip_pool_tot_requests{job=~\"$job\", instance=~\"$instance\", partition=~\"$bigip_partition\"}[$__interval:]))",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top queue depth",
   "type": "bargauge",
   "description": "Pools with the largest connection queues.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($k, bigip_pool_connq_depth{job=~\"$job\", instance=~\"$instance\", partition=~\"$bigip_partition\"})",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top utilized virtual servers / $__interval",
   "type": "bargauge",
   "description": "Virtual servers with the highest traffic (inbound and outbound).",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($k, increase(bigip_vs_clientside_bytes_in{job=~\"$job\", instance=~\"$instance\", partition=~\"$bigip_partition\"}[$__interval:])) + topk(5, increase(bigip_vs_clientside_bytes_out{job=~\"$job\", instance=~\"$instance\", partition=~\"$bigip_partition\"}[$__interval:]))",
     "legendFormat": "{{vs}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top latency virtual servers",
   "type": "bargauge",
   "description": "Virtual servers with the highest response times.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($k, bigip_vs_cs_mean_conn_dur{job=~\"$job\", instance=~\"$instance\", partition=~\"$bigip_partition\"})",
     "legendFormat": "{{vs}} - {{instance}}"
    }
   ]
  }
 ]
}