{
 "title": "IVR Synthetic Main Dashboard Copy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Tags", "label": "Tag", "query": { "query": "label_values(tags)" } },
   {
    "name": "Statuses",
    "label": "Test Name",
    "query": {
     "query": "label_values({job=\"test-case-server\"},name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total Successful Tests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "job_status{tags=~\".*$Tags.*\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failed Tests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "job_status{tags=~\".*$Tags.*\"} == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Tests Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "job_status{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "job_status{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Call Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "job_duration{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Call Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "job_cost{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Call Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "job_duration{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Call Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "job_cost{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contact Center Test Availability",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "job_status{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "job_cost{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    },
    {
     "expr": "job_duration{tags=~\".*$Tags.*\"} != -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tests Health Overtime",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "job_status{tags=~\".*$Tags.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$Tags Health Overtime",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "job_status{tags=~\".*$Tags.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Call Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{job=\"test-case-server\"} | json test=\"attributes.JOB_NAME\" | test =~ `$Statuses`"
    }
   ]
  }
 ]
}