{
 "title": "AppDynamics Overview",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "query": "Applications" }
  ]
 },
 "panels": [
  {
   "title": "App Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Value",
     "application": "$application",
     "delimiter": "|",
     "metric": "Overall Application Performance|Average Response Time (ms)",
     "transformLegend": "Full Path",
     "transformLegendText": "1"
    }
   ]
  },
  {
   "title": "App Response Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Value",
     "application": "$application",
     "delimiter": "|",
     "metric": "Overall Application Performance|Average Response Time (ms)",
     "transformLegend": "Full Path",
     "transformLegendText": "1"
    }
   ]
  },
  {
   "title": "Calls Per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Value",
     "application": "$application",
     "delimiter": "|",
     "metric": "Overall Application Performance|Calls per Minute",
     "transformLegend": "Full Path",
     "transformLegendText": "1"
    }
   ]
  },
  {
   "title": "Calls Per Minute",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Value",
     "application": "$application",
     "delimiter": "|",
     "metric": "Overall Application Performance|Calls per Minute",
     "transformLegend": "Full Path",
     "transformLegendText": "1"
    }
   ]
  },
  {
   "title": "Num Slow Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Value",
     "application": "$application",
     "delimiter": "|",
     "metric": "Overall Application Performance|Number of Slow Calls",
     "transformLegend": "Full Path",
     "transformLegendText": "1"
    }
   ]
  },
  {
   "title": "Num Slow Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Value",
     "application": "$application",
     "delimiter": "|",
     "metric": "Overall Application Performance|Number of Slow Calls",
     "transformLegend": "Full Path",
     "transformLegendText": "1"
    }
   ]
  },
  {
   "title": "Slow Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Value",
     "application": "$application",
     "delimiter": "|",
     "metric": "Overall Application Performance|Number of Very Slow Calls",
     "transformLegend": "Full Path",
     "transformLegendText": "1"
    }
   ]
  },
  {
   "title": "Slow Calls",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Value",
     "application": "$application",
     "delimiter": "|",
     "metric": "Overall Application Performance|Number of Very Slow Calls",
     "transformLegend": "Full Path",
     "transformLegendText": "1"
    }
   ]
  },
  {
   "title": "Stall Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Value",
     "application": "$application",
     "delimiter": "|",
     "metric": "Overall Application Performance|Stall Count",
     "transformLegend": "Full Path",
     "transformLegendText": "1"
    }
   ]
  },
  {
   "title": "Stall Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Value",
     "application": "$application",
     "delimiter": "|",
     "metric": "Overall Application Performance|Stall Count",
     "transformLegend": "Full Path",
     "transformLegendText": "1"
    }
   ]
  }
 ]
}