{
 "title": "Azure / Infrastructure / Compute Monitoring",
 "description": "This dashboard displays traffic-light indicators to show the health of your Azure infrastructure resources based on key performance indicators and thresholds defined for each infrastructure resource type.  The KPIs and thresholds come from Azure Monitor Baseline Alerts (https://azure.github.io/azure-monitor-baseline-alerts/).  \n\nPrerequisites:\nThe queries used in the dashboard require that you have resource metrics being sent to a Log Analytics Workspace. The InsightsMetrics table is required.  Enable VM Insights by following the instructions provided here:  https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-enable-overview\n\nInstallation and Configuration:\nThis dashboard requires the JSON API Grafana plugin and a configured data source for Azure Monitor Baseline Alerts.  Follow these steps to install and configure the JSON API plugin:\n\n1.  Navigate to Connections->Connect Data.\n2.  Search for “JSON API” and then select the JSON API data source.\n3.  Install the plugin if it is not already installed.\n4.  On the JSON API plugin page, click “Create a JSON API data source\".\n5.  On the create JSON API page, give it the name “AMBA” and for the URL, give it the value:  https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/main/visualizations/grafana/infra-monitoring-amba-thresholds.json \n6.  Click the Save & test button. You should see a green checkbox and Success message if configured correctly.\n\nThis is one of a collection of dashboards linked together via dashboard links and the \"azure-infra-monitor\" tag.  Other dashboards in the collection include:\nAzure / Infrastructure / Network Monitoring\nAzure / Infrastructure / Storage and Key Vaults Monitoring\nAzure / Infrastructure / Apps Monitoring\nAzure / Infrastructure / Data Monitoring\n\nThe other dashboards in this collection can be found in the Azure Monitor Team Grafana library here:  https://grafana.com/orgs/azuremonitorteam/dashboards.  Once imported, you will be able to access these dashboards using the Azure Infra Monitoring Dashboards tab.  ",
 "tags": [ "azure-infra-monitor" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "amba", "label": "Azure Monitor Baseline Alerts", "query": "marcusolsson-json-datasource" },
   {
    "name": "subsWSScope",
    "label": "Workspace Scope",
    "query": {}
   },
   {
    "name": "laws",
    "label": "Workspaces",
    "query": {}
   },
   {
    "name": "subsRESScope",
    "label": "Resource Scope",
    "query": {}
   },
   {
    "name": "healthy_color",
    "query": "\"rgb(45\\,161\\,55)\""
   },
   {
    "name": "warning_color",
    "query": "\"rgb(222\\,210\\,38)\""
   },
   {
    "name": "unhealthy_color",
    "query": "\"rgb(255\\,31\\,46)\""
   },
   {
    "name": "amba_vm_AvailableMB",
    "query": {}
   },
   {
    "name": "amba_vm_UtilizationPercentage",
    "query": {}
   },
   {
    "name": "amba_vm_ReadBytesPerSecond",
    "query": {}
   },
   {
    "name": "amba_vm_WriteBytesPerSecond",
    "query": {}
   },
   {
    "name": "amba_vmss_AvailableMB",
    "query": {}
   },
   {
    "name": "amba_vmss_UtilizationPercentage",
    "query": {}
   },
   {
    "name": "amba_vmss_ReadBytesPerSecond",
    "query": {}
   },
   {
    "name": "amba_vmss_WriteBytesPerSecond",
    "query": {}
   },
   {
    "name": "amba_disk_FreeSpacePercentage",
    "query": {}
   },
   {
    "name": "amba_disk_ReadLatencyMs",
    "query": {}
   },
   {
    "name": "amba_disk_WriteLatencyMs",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"font-size:24px;color:rgb(87, 148, 242);\">Azure Infrastructure Monitoring Dashboard (Compute)</p>\r\n\r\nSelect a data source, workspace scope, workspace(s) and resource scope.   \r\nExamine the key performance indicators for your resources by expanding the row for a resource type.  \r\nRecommended KPIs and thresholds used in this dashboard come from [Azure Monitor Baseline Alerts](https://azure.github.io/azure-monitor-baseline-alerts/).  \r\nSee dashboard description for more details on linking to other Infrastructure Monitor dashboards.\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<br>\r\n\r\nKey:\r\n- Green\\Healthy &nbsp;- None of the resources of that resource type have KPIs that are exceeding thresholds.\r\n- Yellow\\Warning - At least one resource of that resource type has one KPI exceeding a threshold.\r\n- Red\\Unhealthy &nbsp;- At least one resource of that resource type has two or more KPIs exceeding a threshold."
   }
  },
  {
   "title": "Virtual Machines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "InsightsMetrics\r\n| where _ResourceId has '/microsoft.compute/virtualmachines/'\r\n| where _ResourceId has_any ($subsRESScope)\r\n| where Origin == \"vm.azm.ms\"\r\n| where Namespace in (\"Processor\", \"Memory\", \"Network\") and Name in (\"UtilizationPercentage\", \"AvailableMB\", \"ReadBytesPerSecond\", \"WriteBytesPerSecond\")\r\n| extend Resource = toupper(tostring(split(_ResourceId,'/')[8]))\r\n| summarize\r\n  kpi1 = avgif((toreal(Val) / (toreal(todynamic(Tags)[\"vm.azm.ms/memorySizeMB\"]))) * 100.0, Name == \"AvailableMB\"),\r\n  kpi2 = avgif(Val, Name == \"UtilizationPercentage\"),\r\n  kpi3 = avgif(Val, Name == \"ReadBytesPerSecond\"),\r\n  kpi4 = avgif(Val, Name == \"WriteBytesPerSecond\") by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3) \r\n|extend kpi4 = iff(isnan(kpi4), 0.0, kpi4) \r\n|extend health1 = iff(kpi1<$amba_vm_AvailableMB, 1, 0)\r\n|extend health2 = iff(kpi2>$amba_vm_UtilizationPercentage, 1, 0)\r\n|extend health3 = iff(kpi3>$amba_vm_ReadBytesPerSecond, 1, 0)\r\n|extend health4 = iff(kpi4>$amba_vm_WriteBytesPerSecond, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend h4color = iff(tobool(health4), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3 + health4\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Virtual Machine Scale Sets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "InsightsMetrics\r\n| where _ResourceId has '/microsoft.compute/virtualmachinescalesets/'\r\n| where _ResourceId has_any ($subsRESScope)\r\n| where Origin == \"vm.azm.ms\"\r\n| where Namespace in (\"Processor\", \"Memory\", \"Network\") and Name in (\"UtilizationPercentage\", \"AvailableMB\", \"ReadBytesPerSecond\", \"WriteBytesPerSecond\")\r\n| extend Resource = strcat(toupper(tostring(split(_ResourceId,'/')[8])), \"-\", toupper(tostring(split(_ResourceId,'/')[10])))\r\n| summarize\r\n  kpi1 = avgif((toreal(Val) / (toreal(todynamic(Tags)[\"vm.azm.ms/memorySizeMB\"]))) * 100.0, Name == \"AvailableMB\"),\r\n  kpi2 = avgif(Val, Name == \"UtilizationPercentage\"),\r\n  kpi3 = avgif(Val, Name == \"ReadBytesPerSecond\"),\r\n  kpi4 = avgif(Val, Name == \"WriteBytesPerSecond\") by _ResourceId, Resource\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3) \r\n|extend kpi4 = iff(isnan(kpi4), 0.0, kpi4) \r\n|extend health1 = iff(kpi1<$amba_vmss_AvailableMB, 1, 0)\r\n|extend health2 = iff(kpi2>$amba_vmss_UtilizationPercentage, 1, 0)\r\n|extend health3 = iff(kpi3>$amba_vmss_ReadBytesPerSecond, 1, 0)\r\n|extend health4 = iff(kpi4>$amba_vmss_WriteBytesPerSecond, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend h4color = iff(tobool(health4), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3 + health4\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "InsightsMetrics\r\n| where _ResourceId has '/microsoft.compute/virtualmachines/'\r\n| where _ResourceId has_any ($subsRESScope)\r\n| where Origin == \"vm.azm.ms\"\r\n| where Namespace == \"LogicalDisk\"\r\n| extend Resource = toupper(tostring(split(_ResourceId,'/')[8]))\r\n| extend Disk=tostring(todynamic(Tags)[\"vm.azm.ms/mountId\"])\r\n| summarize\r\n  kpi1 = avgif(Val, Name == \"FreeSpacePercentage\"),\r\n  kpi2 = avgif(Val, Name == \"ReadLatencyMs\"),\r\n  kpi3 = avgif(Val, Name == \"WriteLatencyMs\") by Computer, _ResourceId, Disk\r\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\r\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \r\n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3) \r\n|extend health1 = iff(kpi1<$amba_disk_FreeSpacePercentage, 1, 0)\r\n|extend health2 = iff(kpi2>$amba_disk_ReadLatencyMs, 1, 0)\r\n|extend health3 = iff(kpi3>$amba_disk_WriteLatencyMs, 1, 0)\r\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\r\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\r\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\r\n|extend health = health1 + health2 + health3\r\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\r\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Virtual Machines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Machine Available Memory Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 2 }
     ]
    },
    {
     "title": "Virtual Machine Processor Utilization Percentage ",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 2 }
     ]
    },
    {
     "title": "Virtual Machine Network Read (bytes/sec)",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 2 }
     ]
    },
    {
     "title": "Virtual Machine Network Write (bytes/sec)",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 2 }
     ]
    }
   ]
  },
  {
   "title": "Virtual Machine Scale Set Uniform Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "VMSS Available Memory Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 26 }
     ]
    },
    {
     "title": "VMSS Processor Utilization Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 26 }
     ]
    },
    {
     "title": "VMSS Network Read (bytes/sec)",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 26 }
     ]
    },
    {
     "title": "VMSS Network Write (bytes/sec)",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 26 }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Free Space",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 94 }
     ]
    },
    {
     "title": "Disk Read Latency (ms)",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 94 }
     ]
    },
    {
     "title": "Disk Write Latency (ms)",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 94 }
     ]
    }
   ]
  }
 ]
}