{
 "title": "IVR Synthetic Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "statuses", "query": { "query": "label_values(__name__)" } }
  ]
 },
 "panels": [
  {
   "title": "Application Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"test-case-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Tests",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otel_tests_success_successfully_ran_test_cases_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Tests",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "otel_tests_failure_unsuccessfully_ran_test_cases_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ran Test Cases",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{__name__=~\"otel_+..+_status_state\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Run Test Durations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "operation": "/tests/run/{test}", "service": "test-case-server" }
   ]
  },
  { "title": "Test Cases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "FPL ABP Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "targets": [
    { "expr": "otel_FPL_ABP_status_state{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "FPL Binq Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "targets": [
    { "expr": "otel_FPL_Binq_status_state{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "FPL PayByPhone Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "otel_FPL_PayByPhone_status_state{}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "GET Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "operation": "GET", "service": "test-case-server" }
   ]
  },
  {
   "title": "POST Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "operation": "POST", "service": "test-case-server" }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Client Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "otel_http_client_duration_milliseconds_count{job=\"test-case-service\"}",
     "legendFormat": "{{http_method}} {{job}} {{instance}} Code: {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "otel_http_server_duration_milliseconds_count{job=\"test-case-service\"}",
     "legendFormat": "{{http_method}} {{job}} {{instance}} Code: {{http_status_code}}"
    }
   ]
  }
 ]
}