{
 "title": "Level 2/3 -SHL",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "service_name", "label": "Service", "query": "AdServiceTier" },
   { "name": "splunk_search", "label": "Splunk Search" },
   { "name": "uuid", "label": "UUID" }
  ]
 },
 "panels": [
  {
   "title": "ServiceNow Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "ServiceNow Incidents",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "displayValue": "all",
       "fields": [
        {
         "aggregates": [],
         "name": "number"
        },
        {
         "aggregates": [],
         "name": "state"
        },
        {
         "aggregates": [],
         "name": "severity"
        },
        {
         "aggregates": [],
         "name": "description"
        },
        {
         "aggregates": [],
         "name": "business_impact"
        },
        {
         "aggregates": [],
         "name": "caller_id.name"
        },
        {
         "aggregates": [],
         "name": "category"
        },
        {
         "aggregates": [],
         "name": "cause"
        },
        {
         "aggregates": [],
         "name": "child_incidents"
        },
        {
         "aggregates": [],
         "name": "close_code"
        },
        {
         "aggregates": [],
         "name": "hold_reason"
        },
        {
         "aggregates": [],
         "name": "incident_state"
        },
        {
         "aggregates": [],
         "name": "notify"
        },
        {
         "aggregates": [],
         "name": "origin_id"
        },
        {
         "aggregates": [],
         "name": "origin_table"
        },
        {
         "aggregates": [],
         "name": "parent_incident.number"
        }
       ],
       "filters": [
        {
         "conjunction": "and",
         "field": "incident_state",
         "fieldDesc": {
          "choice": "3",
          "choice_field": "state",
          "choice_table": "incident",
          "description": "Incident",
          "element": "incident_state",
          "internal_type": {
           "link": "https://optimizincdemo1.service-now.com/api/now/v2/table/sys_glide_object?name=integer",
           "value": "integer"
          },
          "label": "Incident state",
          "name": "incident",
          "reference": { "display_value": "", "link": "", "value": "" },
          "sys_name": "Incident state",
          "table": "incident",
          "value": "incident_state"
         },
         "op": "=",
         "type": "integer",
         "value": "1"
        },
        {
         "conjunction": "and",
         "field": "priority",
         "fieldDesc": {
          "choice": "1",
          "choice_field": "",
          "choice_table": "",
          "description": "Task",
          "element": "priority",
          "internal_type": {
           "link": "https://optimizincdemo1.service-now.com/api/now/v2/table/sys_glide_object?name=integer",
           "value": "integer"
          },
          "label": "Priority",
          "name": "task",
          "reference": { "display_value": "", "link": "", "value": "" },
          "sys_name": "Priority",
          "table": "task",
          "value": "priority"
         },
         "op": "IN",
         "type": "integer",
         "value": "1,3,2"
        },
        {
         "conjunction": "and",
         "field": "contact_type",
         "fieldDesc": {
          "choice": "1",
          "choice_field": "",
          "choice_table": "",
          "description": "Task",
          "element": "contact_type",
          "internal_type": {
           "link": "https://optimizincdemo1.service-now.com/api/now/v2/table/sys_glide_object?name=string",
           "value": "string"
          },
          "label": "Contact type",
          "name": "task",
          "reference": { "display_value": "", "link": "", "value": "" },
          "sys_name": "Contact type",
          "table": "task",
          "value": "contact_type"
         },
         "op": "=",
         "type": "string",
         "value": "Alert"
        },
        {
         "conjunction": "and",
         "field": "cmdb_ci.name",
         "fieldDesc": {
          "choice": "0",
          "choice_field": "",
          "choice_table": "",
          "description": "Cmdb_ci",
          "element": "name",
          "internal_type": {
           "link": "https://optimizincdemo1.service-now.com/api/now/v2/table/sys_glide_object?name=string",
           "value": "string"
          },
          "label": "Configuration item -> name",
          "name": "cmdb_ci",
          "reference": { "display_value": "", "link": "", "value": "" },
          "sys_name": "",
          "table": "cmdb_ci",
          "value": "cmdb_ci.name"
         },
         "op": "=",
         "type": "string",
         "value": "$service_name"
        },
        {}
       ],
       "limit": 2000,
       "sort": [
        {}
       ],
       "table": "incident",
       "timeField": "ignore_time"
      }
     ]
    },
    {
     "title": "Source Alerts",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "displayValue": "all",
       "fields": [
        {
         "aggregates": [],
         "name": "number"
        },
        {
         "aggregates": [],
         "name": "severity"
        },
        {
         "aggregates": [],
         "name": "cmdb_ci.name"
        },
        {
         "aggregates": [],
         "name": "description"
        },
        {
         "aggregates": [],
         "name": "event_count"
        },
        {
         "aggregates": [],
         "name": "state"
        },
        {
         "aggregates": [],
         "name": "source"
        },
        {
         "aggregates": [],
         "name": "node"
        },
        {
         "aggregates": [],
         "name": "sys_id"
        }
       ],
       "filters": [
        {
         "conjunction": "and",
         "field": "state",
         "fieldDesc": {
          "choice": "1",
          "choice_field": "",
          "choice_table": "",
          "description": "Em_alert",
          "element": "state",
          "internal_type": {
           "link": "https://optimizincdemo1.service-now.com/api/now/v2/table/sys_glide_object?name=choice",
           "value": "choice"
          },
          "label": "State",
          "name": "em_alert",
          "reference": { "display_value": "", "link": "", "value": "" },
          "sys_name": "State",
          "table": "em_alert",
          "value": "state"
         },
         "op": "!=",
         "type": "choice",
         "value": "Closed"
        },
        {
         "conjunction": "and",
         "field": "source",
         "fieldDesc": {
          "choice": "0",
          "choice_field": "",
          "choice_table": "",
          "description": "Em_alert",
          "element": "source",
          "internal_type": {
           "link": "https://optimizincdemo1.service-now.com/api/now/v2/table/sys_glide_object?name=string",
           "value": "string"
          },
          "label": "Source",
          "name": "em_alert",
          "reference": { "display_value": "", "link": "", "value": "" },
          "sys_name": "Source",
          "table": "em_alert",
          "value": "source"
         },
         "op": "IN",
         "type": "string",
         "value": "AppDynamics,Group Alert"
        },
        { "conjunction": "and", "field": "cmdb_ci.name", "op": "=", "value": "$service_name" },
        {}
       ],
       "limit": 2000,
       "sort": [
        {}
       ],
       "table": "em_alert",
       "timeField": "ignore_time"
      }
     ]
    },
    {
     "title": "Change Requests",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "displayValue": "all",
       "fields": [
        {
         "aggregates": [],
         "name": "number"
        },
        {
         "aggregates": [],
         "name": "description"
        },
        {
         "aggregates": [],
         "name": "type"
        },
        {
         "aggregates": [],
         "name": "start_date"
        },
        {
         "aggregates": [],
         "name": "end_date"
        },
        {
         "aggregates": [],
         "name": "priority"
        },
        {
         "aggregates": [],
         "name": "urgency"
        },
        {
         "aggregates": [],
         "name": "risk"
        },
        {
         "aggregates": [],
         "name": "state"
        },
        {
         "aggregates": [],
         "name": "escalation"
        },
        {
         "aggregates": [],
         "name": "impact"
        }
       ],
       "filters": [
        {
         "conjunction": "and",
         "field": "requested_by.name",
         "fieldDesc": {
          "choice": "0",
          "choice_field": "",
          "choice_table": "",
          "description": "Sys_user",
          "element": "name",
          "internal_type": {
           "link": "https://optimizincdemo1.service-now.com/api/now/v2/table/sys_glide_object?name=string",
           "value": "string"
          },
          "label": "Requested by -> Name",
          "name": "sys_user",
          "reference": { "display_value": "", "link": "", "value": "" },
          "sys_name": "Name",
          "table": "sys_user",
          "value": "requested_by.name"
         },
         "op": "=",
         "type": "string",
         "value": "Braden Still-Routley"
        },
        {
         "conjunction": "and",
         "field": "cmdb_ci.name",
         "fieldDesc": {
          "choice": "0",
          "choice_field": "",
          "choice_table": "",
          "description": "Cmdb_ci",
          "element": "name",
          "internal_type": {
           "link": "https://optimizincdemo1.service-now.com/api/now/v2/table/sys_glide_object?name=string",
           "value": "string"
          },
          "label": "Configuration item -> name",
          "name": "cmdb_ci",
          "reference": { "display_value": "", "link": "", "value": "" },
          "sys_name": "",
          "table": "cmdb_ci",
          "value": "cmdb_ci.name"
         },
         "op": "=",
         "type": "string",
         "value": "$service_name"
        },
        {}
       ],
       "limit": 25,
       "sort": [
        { "field": "number", "order": "asc" },
        {}
       ],
       "table": "change_request",
       "timeField": "ignore_time"
      }
     ]
    }
   ]
  },
  { "title": "KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "App Availability",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregation": "Value",
     "application": "OpenTelemetryDemo",
     "delimiter": "|",
     "metric": "Application Infrastructure Performance|$service_name|Agent|App|Availability",
     "schemaVersion": "3.5.0",
     "transformLegend": "Full Path"
    }
   ]
  },
  {
   "title": "Calls Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregation": "Value",
     "application": "OpenTelemetryDemo",
     "delimiter": "|",
     "metric": "Overall Application Performance|$service_name|Calls per Minute",
     "schemaVersion": "3.5.0",
     "transformLegend": "Full Path"
    }
   ]
  },
  {
   "title": "Error per Minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregation": "Value",
     "application": "OpenTelemetryDemo",
     "delimiter": "|",
     "metric": "Overall Application Performance|$service_name|Errors per Minute",
     "schemaVersion": "3.5.0",
     "transformLegend": "Full Path"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "aggregation": "Value",
     "application": "OpenTelemetryDemo",
     "delimiter": "|",
     "metric": "Overall Application Performance|$service_name|Average Response Time (ms)",
     "schemaVersion": "3.5.0",
     "transformLegend": "Full Path"
    }
   ]
  },
  {
   "title": "JVM Heap Used %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "aggregation": "Value",
     "application": "OpenTelemetryDemo",
     "delimiter": "|",
     "metric": "Application Infrastructure Performance|$service_name|JVM|Memory|Heap|Used %",
     "schemaVersion": "3.5.0",
     "transformLegend": "Full Path"
    }
   ]
  },
  {
   "title": "JVM Heap in MB",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "aggregation": "Value",
     "application": "OpenTelemetryDemo",
     "delimiter": "|",
     "metric": "Application Infrastructure Performance|$service_name|JVM|Memory|Heap|Current Usage (MB)",
     "schemaVersion": "3.5.0",
     "transformLegend": "Full Path"
    },
    {
     "aggregation": "Value",
     "application": "OpenTelemetryDemo",
     "delimiter": "|",
     "metric": "Application Infrastructure Performance|$service_name|JVM|Memory|Heap|Committed (MB)",
     "schemaVersion": "3.5.0",
     "transformLegend": "Full Path"
    },
    {
     "aggregation": "Value",
     "application": "OpenTelemetryDemo",
     "delimiter": "|",
     "metric": "Application Infrastructure Performance|$service_name|JVM|Memory|Heap|Max Available (MB)",
     "schemaVersion": "3.5.0",
     "transformLegend": "Full Path"
    }
   ]
  },
  {
   "title": "# of Major/Minor GC",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregation": "Value",
     "application": "OpenTelemetryDemo",
     "delimiter": "|",
     "metric": "Application Infrastructure Performance|$service_name|JVM|Garbage Collection|Number of Minor Collections Per Min",
     "schemaVersion": "3.5.0",
     "transformLegend": "Full Path"
    },
    {
     "aggregation": "Value",
     "application": "OpenTelemetryDemo",
     "delimiter": "|",
     "metric": "Application Infrastructure Performance|$service_name|JVM|Garbage Collection|Number of Major Collections Per Min",
     "schemaVersion": "3.5.0",
     "transformLegend": "Full Path"
    }
   ]
  },
  {
   "title": "Time spent on Major/Minor GC",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "aggregation": "Value",
     "application": "OpenTelemetryDemo",
     "delimiter": "|",
     "metric": "Application Infrastructure Performance|$service_name|JVM|Garbage Collection|Minor Collection Time Spent Per Min (ms)",
     "schemaVersion": "3.5.0",
     "transformLegend": "Full Path"
    },
    {
     "aggregation": "Value",
     "application": "OpenTelemetryDemo",
     "delimiter": "|",
     "metric": "Application Infrastructure Performance|$service_name|JVM|Garbage Collection|Major Collection Time Spent Per Min (ms)",
     "schemaVersion": "3.5.0",
     "transformLegend": "Full Path"
    }
   ]
  },
  {
   "title": "Status Codes from AppDynamics (Pie charts)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "AppDynamics Error Codes",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregation": "Value",
       "application": "OpenTelemetryDemo",
       "delimiter": "|",
       "metric": "Errors|$service_name|*|Number of Errors",
       "schemaVersion": "3.5.0",
       "transformLegend": "Full Path"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs/Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Splunk Docker Logs",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "displayMode": "detect",
       "index": "select index",
       "metricAggs": [
        { "alias": "", "field": "select field", "func": "avg" }
       ],
       "options": {
        "cont": true,
        "partial": true
       },
       "query": "source=\"http:Docker\"| spath tag | search tag=9750bebcd761",
       "sourcetype": "select sourcetype",
       "tcOptions": {
        "nullstr": "",
        "otherstr": "",
        "span": "auto",
        "usenull": false,
        "useother": true
       },
       "whereClause": { "value": "" }
      }
     ]
    },
    {
     "title": "AppDynamics Transaction Analytics",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "query": "SELECT segments.tier, segments.node, transactionName, requestGUID, segments.errorList.errorCode FROM transactions WHERE userExperience = \"ERROR\" AND application = \"ECommerce\""
      }
     ]
    }
   ]
  }
 ]
}