{
 "title": "CVP Dashboard",
 "tags": [ "IVR" ],
 "time": { "from": "2024-09-24T09:17:22.913Z", "to": "2024-10-31T20:58:58.995Z" },
 "panels": [
  {
   "title": "Average Time in Queue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Time In Queue",
        "type": "number",
        "values": [
         95
        ]
       }
      ],
      "meta": {},
      "name": "name"
     }
    }
   ]
  },
  {
   "title": "Application Duration Gauge (Seconds)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Application",
        "type": "string",
        "values": [
         "LinkAssist",
         "Call Guardian",
         "CallHandler",
         "SignalRouter",
         "VoiceLink",
         "VoiceAssistant",
         "VoiceControl"
        ]
       },
       {
        "config": {},
        "name": "Duration",
        "type": "number",
        "values": [
         238,
         120,
         175,
         234,
         100,
         127,
         62
        ]
       }
      ],
      "meta": {},
      "name": "name"
     }
    }
   ]
  },
  {
   "title": "All Applications With Errors",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "application",
        "type": "string",
        "values": [
         "LinkAssist",
         "Call Guardian",
         "CallHandler",
         "SignalRouter",
         "VoiceLink",
         "VoiceAssistant",
         "VoiceControl"
        ]
       },
       {
        "config": {},
        "name": "error count",
        "type": "number",
        "values": [
         98,
         120,
         175,
         85,
         100,
         110,
         150
        ]
       }
      ],
      "meta": {},
      "name": "name"
     }
    }
   ]
  },
  {
   "title": "Average IVR Response Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Time In Queue",
        "type": "number",
        "values": [
         1200
        ]
       }
      ],
      "meta": {},
      "name": "name"
     }
    }
   ]
  },
  {
   "title": "Call Completion Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Time In Queue",
        "type": "number",
        "values": [
         15
        ]
       }
      ],
      "meta": {},
      "name": "name"
     }
    }
   ]
  },
  {
   "title": "Call Logger Counts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "spreadsheet": "1vUCexPLdLKHF5XJ__9G7hoO0KYRM512ndkP_5HPiibY"
    }
   ]
  },
  {
   "title": "(IIS Beat) Invalid WAV Files Found By Host",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "spreadsheet": "13Gl0WXe_1Qq1nWjt3A3KIlZwIbDx2qoLUt21SOTqV2U"
    }
   ]
  },
  {
   "title": "Application Hard Failures ErrorLog",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Application",
        "type": "string",
        "values": [
         "LinkAssist",
         "Call Guardian",
         "CallHandler",
         "SignalRouter",
         "VoiceLink",
         "VoiceAssistant",
         "VoiceControl"
        ]
       },
       {
        "config": {},
        "name": "Error Count",
        "type": "number",
        "values": [
         98,
         120,
         175,
         85,
         100,
         110,
         150
        ]
       }
      ],
      "meta": {},
      "name": "name"
     }
    }
   ]
  },
  {
   "title": "Activity Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "{filename=\"C:\\\\Users\\\\monta\\\\Downloads\\\\Logs\\\\activity_log.txt\"} | pattern `<ip>,<phone>,<id>,<app>,<date>,<status>,<duration>`"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "{filename=\"C:\\\\Users\\\\monta\\\\Downloads\\\\Logs\\\\error_log_v6.txt\"} | pattern `<ip>,<phone>,<id>,<app>,<date>,<error>`"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Duration Gauge (Seconds)",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "{filename=\"C:\\\\Users\\\\monta\\\\Downloads\\\\Logs\\\\activity_log_format.txt\"} | pattern `<ip>,<phone>,<id>,<app>,<date>,<status>,<duration>`"
      }
     ]
    },
    {
     "title": "All Applications With Errors",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{filename=\"C:\\\\Users\\\\monta\\\\Downloads\\\\Logs\\\\error_log_v6.txt\"} | pattern `<ip>,<phone>,<id>,<app>,<date>,<message>`"
      }
     ]
    },
    {
     "title": "Call Logger Counts",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "{filename=\"C:\\\\Users\\\\monta\\\\Downloads\\\\Logs\\\\activity_log_format.txt\"} | pattern `<ip>,<phone>,<id>,<app>,<date>,<status>,<duration>`"
      }
     ]
    },
    {
     "title": "(IIS Beat) Invalid WAV Files Found By Host",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "frame": {
        "fields": [
         {
          "config": {},
          "name": "host.hostname",
          "type": "string",
          "values": [
           "db01",
           "db02",
           "db02",
           "cache01\t",
           "cache01\t",
           "cache02\t",
           "api01",
           "api02",
           "web01",
           "web02"
          ]
         },
         {
          "config": {},
          "name": "url.path",
          "type": "string",
          "values": [
           "/",
           "/api/v1/address\t",
           "/user/settings\t",
           "/login",
           "/api/v1/logout",
           "/2015/users/2/shipping_addresses",
           "/contact/form.jsp",
           "/random-php-script.php",
           "/address/update",
           "/login.jsp"
          ]
         },
         {
          "config": {},
          "name": "filters",
          "type": "string",
          "values": [
           "http.responses.status_code: 404",
           "http.responses.status_code: 500",
           "http.responses.status_code: 403",
           "http.responses.status_code: 404",
           "http.responses.status_code: 404",
           "http.responses.status_code: 403",
           "http.responses.status_code: 404",
           "http.responses.status_code: 403",
           "http.responses.status_code: 403",
           "http.responses.status_code: 404"
          ]
         },
         {
          "config": {},
          "name": "Count",
          "type": "number",
          "values": [
           0,
           67,
           67,
           100,
           100,
           34,
           87,
           46,
           23,
           43
          ]
         }
        ],
        "meta": {},
        "name": "Simulated Data"
       }
      }
     ]
    },
    {
     "title": "Application Hard Failures ErrorLog",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "{filename=\"C:\\\\Users\\\\monta\\\\Downloads\\\\Logs\\\\error_log_v6.txt\"} | pattern `<ip>,<phone>,<id>,<app>,<date>,<message>`"
      }
     ]
    },
    {
     "title": "Activity Logs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
     "targets": [
      {
       "expr": "{filename=\"C:\\\\Users\\\\monta\\\\Downloads\\\\Logs\\\\activity_log.txt\"} | pattern `<ip>,<phone>,<id>,<app>,<date>,<status>,<duration>`"
      }
     ]
    },
    {
     "title": "Error Logs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 31 },
     "targets": [
      {
       "expr": "{filename=\"C:\\\\Users\\\\monta\\\\Downloads\\\\Logs\\\\error_log_v6.txt\"} | pattern `<ip>,<phone>,<id>,<app>,<date>,<error>`"
      }
     ]
    }
   ]
  }
 ]
}