{
 "title": "Access Service Insights",
 "tags": [
  "Service Insights",
  "Team: Skadi's Squad",
  "For Review"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {}
   },
   {
    "name": "namespace",
    "query": {}
   },
   { "name": "env", "label": "Environment", "query": "kansas-prod" }
  ]
 },
 "panels": [
  {
   "title": "Business Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Player Login",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=player` |~ `(?i)login` | json | __error__=`` [$__auto]))"
      }
     ]
    },
    {
     "title": "Player Login",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=player` |~ `(?i)login` | json | __error__=`` [$__auto]))"
      }
     ]
    },
    {
     "title": "Admin Login",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=admin` |~ `(?i)login` | json | __error__=`` [$__auto]))"
      }
     ]
    },
    {
     "title": "Admin Login",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=admin` |~ `(?i)login` | json | __error__=`` [$__auto]))"
      }
     ]
    },
    {
     "title": "Player Login Logs",
     "type": "logs",
     "gridPos": { "h": 1, "w": 4, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "{cluster=\"kansas-ilp-prod\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=player` |~ `(?i)login` | json | __error__=``"
      }
     ]
    },
    {
     "title": "Admin Login Logs",
     "type": "logs",
     "gridPos": { "h": 1, "w": 4, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "{cluster=\"kansas-ilp-prod\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=admin` |~ `(?i)login` | json | __error__=``"
      }
     ]
    },
    {
     "title": "Player Login Failed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=player` |~ `(?i)loginFailed` | json | __error__=`` [$__auto]))"
      }
     ]
    },
    {
     "title": "Player Login Failed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 7 },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=player` |~ `(?i)loginFailed` | json | __error__=`` [$__auto]))"
      }
     ]
    },
    {
     "title": "Admin Login Failed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=admin` |~ `(?i)loginFailed` | json | __error__=`` [$__auto]))"
      }
     ]
    },
    {
     "title": "Admin Login Failed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=admin` |~ `(?i)loginFailed` | json | __error__=`` [$__auto]))"
      }
     ]
    },
    {
     "title": "Player Login Failed Logs",
     "type": "logs",
     "gridPos": { "h": 1, "w": 4, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "{cluster=\"kansas-ilp-prod\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=player` |~ `(?i)loginFailed` | json | __error__=``"
      }
     ]
    },
    {
     "title": "Admin Login Failed Logs",
     "type": "logs",
     "gridPos": { "h": 1, "w": 4, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=admin` |~ `(?i)loginFailed` | json | __error__=``"
      }
     ]
    },
    {
     "title": "Player Logout",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=player` |~ `(?i)logout` | json | __error__=`` [$__auto]))"
      }
     ]
    },
    {
     "title": "Player Logout",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 13 },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=player` |~ `(?i)logout` | json | __error__=`` [$__auto]))"
      }
     ]
    },
    {
     "title": "Admin Logout",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=admin` |~ `(?i)logout` | json | __error__=`` [$__auto]))"
      }
     ]
    },
    {
     "title": "Admin Logout",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
     "targets": [
      {
       "expr": "sum(count_over_time({namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=admin` |~ `(?i)logout` | json | __error__=`` [$__auto]))"
      }
     ]
    },
    {
     "title": "Player Logout Logs",
     "type": "logs",
     "gridPos": { "h": 1, "w": 4, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=player` |~ `(?i)logout` | json | __error__=``"
      }
     ]
    },
    {
     "title": "Admin Logout Logs",
     "type": "logs",
     "gridPos": { "h": 1, "w": 4, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Authentication event message received` |~ `(?i)messageId=admin` |~ `(?i)logout` | json | __error__=``"
      }
     ]
    }
   ]
  },
  { "title": "Exception Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "The feature set doesn't exist",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)FEATURE_SET_NOT_FOUND` |~ `(?i)Feature set does not exist` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "The feature set doesn't exist",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 2 },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Allow access attributes update unsuccessful for admin",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)The specified access attribute is invalid` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "No access attributes exists with the specified id",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "targets": [
    { "panelId": 76 }
   ]
  },
  {
   "title": "The feature set doesn't exist",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)FEATURE_SET_NOT_FOUND` |~ `(?i)Feature set does not exist` | json | __error__=``"
    }
   ]
  },
  {
   "title": "Allow access attributes update unsuccessful for admin logs",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)The specified access attribute is invalid` | json | __error__=``"
    }
   ]
  },
  {
   "title": "Access group doesn't exist",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)attempted to update group member` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Access group doesn't exist",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 8 },
   "targets": [
    { "panelId": 7 }
   ]
  },
  {
   "title": "The group member was not added",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)GROUP_NOT_FOUND` |~ `(?i)Group does not exist` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "The group member was not added",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Access group doesn't exist",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)attempted to update group member` | json | __error__=``"
    }
   ]
  },
  {
   "title": "The group member was not added",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)GROUP_NOT_FOUND` | json | __error__=``"
    }
   ]
  },
  {
   "title": "Role doesn't exist",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)ROLE_NOT_FOUND` |~ `(?i)Role does not exist` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Role doesn't exist",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 14 },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Group member was not found",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)GROUPMEMBER_NOT_FOUND` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Group member was not found",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "targets": [
    { "panelId": 8 }
   ]
  },
  {
   "title": "Role doesn't exist",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)ROLE_NOT_FOUND` | json | __error__=``"
    }
   ]
  },
  {
   "title": "Group member was not found",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)GROUPMEMBER_NOT_FOUND` | json | __error__=``"
    }
   ]
  },
  {
   "title": "Unable to connect to Time Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {namespace=\"$namespace\", deployment_environment=\"$env\", container=\"$container\"} \n    |~ `javax.ws.rs.ServiceUnavailableException: HTTP 503 Service Unavailable`\n    |~ `com.betware.util.time.BwSystemTime.getTime`\n    | json \n    | __error__=`` \n    [$__auto]\n  )\n)"
    }
   ]
  },
  {
   "title": "Unable to connect to Time Service",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 20 },
   "targets": [
    { "panelId": 16 }
   ]
  },
  {
   "title": "The specified admin role doesn't exist",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)ROLE_NOT_FOUND` |~ `(?i)The specified admin role` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "The specified admin role doesn't exist",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Unable to connect to Time Service",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"}\n|~ `javax.ws.rs.ServiceUnavailableException: HTTP 503 Service Unavailable`\n|~ `com.betware.util.time.BwSystemTime.getTime`"
    }
   ]
  },
  {
   "title": "The specified admin role doesn't exist",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)ROLE_NOT_FOUND` | json | __error__=``"
    }
   ]
  },
  {
   "title": "Could not get a connection to AMQP broker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", deployment_environment=\"$env\", container=\"$container\"} \n|~ `Could not get a connection to AMQP broker`\n| json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Could not get a connection to AMQP broker",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 26 },
   "targets": [
    { "panelId": 85 }
   ]
  },
  {
   "title": "Could not get a connection to AMQP broker",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"}\n|~ `Could not get a connection to AMQP broker` "
    }
   ]
  }
 ]
}