{
 "title": "Activity Service Insights",
 "tags": [
  "Service Insights",
  "Team: Bond",
  "For Review"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {}
   },
   {
    "name": "namespace",
    "query": {}
   },
   { "name": "env", "label": "Environment", "query": "kansas-prod" }
  ]
 },
 "panels": [
  { "title": "Exception Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fails to retrieve activities",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Handling method argument not valid exception` or `(?i)Handling illegal argument exception` or `(?i)Handling general exception` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fails to retrieve activities",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Handling method argument not valid exception` or `(?i)Handling illegal argument exception` or `(?i)Handling general exception` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fails to get geo-device information from Geo Device Service",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not retrieve geo-device data` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fails to get geo-device information from Geo Device Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not retrieve geo-device data` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fails to retrieve activities",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Handling method argument not valid exception` or `(?i)Handling illegal argument exception` or `(?i)Handling general exception` | json | __error__=``"
    }
   ]
  },
  {
   "title": "Fails to get geo-device information from Geo Device Service",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not retrieve geo-device data` | json"
    }
   ]
  },
  {
   "title": "Fails to get session information from idp Extension Service",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not retrieve session info data` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fails to get session information from idp Extension Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not retrieve session info data` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fails to get audit information",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not retrieve audit history data` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fails to get audit information",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not retrieve audit history data` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fails to get session information from idp Extension Service",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not retrieve session info data` | json"
    }
   ]
  },
  {
   "title": "Fails to get audit information",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not retrieve audit history data` | json"
    }
   ]
  },
  {
   "title": "Fails to upload file to AWS S3",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Failed to upload file` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fails to upload file to AWS S3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Failed to upload file` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fails to add csv file to a case",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not add file to a case` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fails to add csv file to a case",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not add file to a case` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fails to upload file to AWS S3",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Failed to upload file` | json"
    }
   ]
  },
  {
   "title": "Fails to add csv file to a case",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not add file to a case` | json"
    }
   ]
  },
  {
   "title": "Fails to export csv file",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Exporting activity log entries to CSV failed with error` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fails to export csv file",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Exporting activity log entries to CSV failed with error` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Fails to export csv file",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Exporting activity log entries to CSV failed with error` | json"
    }
   ]
  }
 ]
}