{
 "title": "Bonus Service Insights",
 "tags": [
  "Service Insights",
  "For Review",
  "Team: Porcupines",
  "NeedsPromotion"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {}
   },
   {
    "name": "namespace",
    "query": {}
   },
   { "name": "env", "label": "Environment", "query": "kansas-prod" }
  ]
 },
 "panels": [
  {
   "title": "Business & Operational Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Bonus achieved",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count by(bonusId) (rate({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)status=ACHIEVED` |~ `(?i)Tracking event successfully processed` | json | pattern `<_> bonusObjectIds=[<bonusId>]` | path = `/api/bonus/rest/v1/tracking-events` [$__auto]))"
    }
   ]
  },
  {
   "title": "Bonus achieved",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "targets": [
    { "panelId": 7 }
   ]
  },
  {
   "title": "Bonus offered",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)status=OFFER` |~ `(?i)Tracking event successfully processed` | json | path = `/api/bonus/rest/v1/tracking-events` | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Bonus offered",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)status=OFFER` |~ `(?i)Tracking event successfully processed` | json | path = `/api/bonus/rest/v1/tracking-events` | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Bonus achieved",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{deployment_environment=\"$env\"} \n|~ `(?i)status=ACHIEVED` \n|~ `(?i)Tracking event successfully processed` \n| json \n| pattern `<_> bonusObjectIds=[<bonusId>]` \n| path = `/api/bonus/rest/v1/tracking-events`"
    }
   ]
  },
  {
   "title": "Bonus offered",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)status=OFFER` |~ `(?i)Tracking event successfully processed` | json | path = `/api/bonus/rest/v1/tracking-events`"
    }
   ]
  },
  {
   "title": "Unused bonus expired",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Performing call to wallet to purge account for userId` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Unused bonus expired",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 7 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Performing call to wallet to purge account for userId` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Manually assigned bonuses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traces_spanmetrics_calls_total{service=\"$container\",service_namespace=\"$namespace\",span_name=\"PUT /api/bonus/rest/v1/player-bonuses/payout\",status_code!=\"STATUS_CODE_ERROR\", deployment_environment=\"$env\"}"
    }
   ]
  },
  {
   "title": "Manually assigned bonuses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "traces_spanmetrics_calls_total{service=\"$container\",service_namespace=\"$namespace\",span_name=\"PUT /api/bonus/rest/v1/player-bonuses/payout\",status_code!=\"STATUS_CODE_ERROR\", deployment_environment=\"$env\"}"
    }
   ]
  },
  {
   "title": "Unused bonus expired",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Performing call to wallet to purge account for userId` | json"
    }
   ]
  },
  {
   "title": "Manually assigned bonuses",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "traces_spanmetrics_calls_total{service=\"$container\",service_namespace=\"$namespace\",span_name=\"PUT /api/bonus/rest/v1/player-bonuses/payout\",status_code!=\"STATUS_CODE_ERROR\"}"
    }
   ]
  },
  {
   "title": "Bonus prize ID validation fails",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |= `(?i)Bonus not found` or `(?i)Bonus not in correct priority order` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Bonus prize ID validation fails",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |= `(?i)Bonus not found` or `(?i)Bonus not in correct priority order` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Bonus prize ID validation fails",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |= `(?i)Bonus not found` or `(?i)Bonus not in correct priority order` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  { "title": "Exception Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Can’t get campaign from Bloomreach/Exponea",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not get campaign from exponea integration service` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Can’t get campaign from Bloomreach/Exponea",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 20 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Can’t find campaign on Bloomreach/Exponea",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Received null response from 3rd party system, hence creating dummy campaign for externalCampaignId` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Can’t find campaign on Bloomreach/Exponea",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Received null response from 3rd party system, hence creating dummy campaign for external CampaignId` | json"
    }
   ]
  },
  {
   "title": "Can’t get campaign from Bloomreach/Exponea",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not get campaign from exponea integration service` | json"
    }
   ]
  },
  {
   "title": "Can’t find campaign on Bloomreach/Exponea",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 25 },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Purge account on wallet fails",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not purge account for a player` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Purge account on wallet fails",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 26 },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Bonus payout fails on wallet",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not perform a proxy funds call to wallet` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Bonus payout fails on wallet",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not perform a proxy funds call to wallet` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Purge account on wallet fails",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not purge account for a player` | json"
    }
   ]
  },
  {
   "title": "Bonus payout fails on wallet",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Could not perform a proxy funds call to wallet` | json"
    }
   ]
  },
  {
   "title": "Failed to process player bonus",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Bonus object Ids mismatch for Campaign with externalCampaignId` | json | __error__=`` [$__auto]))"
    }
   ]
  },
  {
   "title": "Failed to process player bonus",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 32 },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Failed to process player bonus",
   "type": "logs",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{container=\"$container\", namespace=\"$namespace\", deployment_environment=\"$env\"} |~ `(?i)Bonus object Ids mismatch for Campaign with externalCampaignId` | json"
    }
   ]
  }
 ]
}