{
 "title": "AWS Network Load Balancer (NLB)",
 "description": "Visualize AWS Network Load Balancer metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(aws_networkelb_info,scrape_job)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(aws_networkelb_info,region)"
    }
   },
   {
    "name": "loadbalancername",
    "label": "LoadBalancerName",
    "query": {
     "query": "label_values(aws_networkelb_healthy_host_count_average,dimension_LoadBalancer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Healthy / Unhealthy Hosts Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_networkelb_healthy_host_count_average{region=\"$region\", dimension_LoadBalancer=\"$loadbalancername\", dimension_TargetGroup=~\".*\", scrape_job=\"$env\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_networkelb_un_healthy_host_count_average{region=\"$region\", dimension_LoadBalancer=\"$loadbalancername\", dimension_TargetGroup=~\".*\", scrape_job=\"$env\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net / Active Flow Count *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_networkelb_active_flow_count_sum{region=\"$region\", dimension_LoadBalancer=\"$loadbalancername\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_networkelb_new_flow_count_average{region=\"$region\", dimension_LoadBalancer=\"$loadbalancername\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New / Active Flow Count TLS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "ConsumedLCUs / ProcessedBytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_networkelb_processed_bytes_average{region=\"$region\", dimension_LoadBalancer=\"$loadbalancername\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_networkelb_consumed_lcus_average{region=\"$region\", dimension_LoadBalancer=\"$loadbalancername\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLSNegotiationErrorCount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "TCP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_networkelb_tcp_client_reset_count_sum{region=\"$region\", dimension_LoadBalancer=\"$loadbalancername\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_networkelb_tcp_elb_reset_count_sum{region=\"$region\", dimension_LoadBalancer=\"$loadbalancername\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_networkelb_tcp_target_reset_count_sum{region=\"$region\", dimension_LoadBalancer=\"$loadbalancername\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 43 },
   "options": {
    "content": "<a href=\"http://verygoodsecurity.com\" target=\"_blank\" title=\"Dashboard maintained by Very Good Security\"><img src=\"https://www.verygoodsecurity.com/theme/img/meta-logo.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-cloudwatch-metrics.html\">AWS CloudWatch Network ELB documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/\">Installed from Grafana.com dashboards</a>"
   }
  }
 ]
}