{
 "title": "AWS Aurora DB",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": "kansas-prod" }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{scrape_job=\"$env\", dimension_EngineName!=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Free Memory in GB",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_average{scrape_job=\"$env\", dimension_EngineName!=\"postgres\"} / 1024000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Disk Usage (GB)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_average{scrape_job=\"$env\", dimension_DatabaseClass=\"db.m6g.large\"} / 1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "aws_rds_read_iops_average{scrape_job=\"$env\", dimension_EngineName!=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "aws_rds_write_iops_average{scrape_job=\"$env\", dimension_EngineName!=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database connections count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_rds_database_connections_sum{scrape_job=~\"kansas_staging|$env\", region=~\"us-east-1\", dimension_DBInstanceIdentifier=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Latency Average (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_rds_read_latency_average{scrape_job=~\"$env\", region=~\"us-east-1\", dimension_DBInstanceIdentifier=~\".+\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Latency Average (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_rds_write_latency_average{scrape_job=~\"$env\", region=~\"us-east-1\", dimension_DBInstanceIdentifier=~\".+\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Lag (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "aws_rds_aurora_replica_lag_average{scrape_job=\"$env\", dimension_Role=\"READER\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Throughput (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "aws_rds_read_throughput_average{scrape_job=\"$env\", dimension_EngineName!=\"postgres\"} / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Throughput (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "aws_rds_write_throughput_average{scrape_job=\"$env\", dimension_EngineName!=\"postgres\"} / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "aws_rds_deadlocks_average{scrape_job=\"$env\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 50 },
   "targets": [
    {
     "expr": "aws_rds_buffer_cache_hit_ratio_average{scrape_job=\"$env\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}