{
 "title": "AWS EC2",
 "description": "Create EC2 Dashboard with USE methodology - Different than the OOTB AWS provided EC2 dashboard as that one does not have memory metrics which are critical.\n\n",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "aws_region", "label": "AWS Region" },
   { "name": "tags", "label": "Tags" },
   { "name": "env", "label": "Environment", "query": "kansas-prod" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Count By Cluster",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without (cpu) (node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", mode=\"idle\",deployment_environment=\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    node_memory_SwapTotal_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\"$instance\", mode=\"idle\",deployment_environment=\"$env\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root Mount Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    node_filesystem_size_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", mountpoint=\"/\",deployment_environment=\"$env\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EC2 Instances",
   "type": "table",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "node_exporter_build_info{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 4 Average Memory Usage by Instance",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(4, avg by (instance) (\r\n    node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Avg Memory Swap Total Bytes by Instance",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(6, avg by (instance) (\r\n    node_memory_SwapTotal_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average CPU Usage Percentage Across All Instance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (instance) (\r\n  100 - (avg(irate(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", mode=\"idle\",deployment_environment=\"$env\"}[5m])) * 100)\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total CPU Usage Percentage Across All Instances",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (sum(irate(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", mode=\"idle\",deployment_environment=\"$env\"}[5m])) / sum(count(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", mode=\"idle\",deployment_environment=\"$env\"}) by (instance)) * 100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average CPU Usage Percentage by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - avg by (instance) (\r\n    irate(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}[5m])\r\n) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average CPU Usage by Mode and Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
     "targets": [
      {
       "expr": "avg by (instance, mode) (\r\n    rate(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}[5m])\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total CPU Usage by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum by (instance) (\r\n    rate(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}[5m])\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage Percentage by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (1 - avg by (instance) (\r\n    irate(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}[5m])\r\n))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU User Mode Usage by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum by (instance) (\r\n    rate(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", mode=\"user\",deployment_environment=\"$env\"}[5m])\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU System Mode Usage by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
     "targets": [
      {
       "expr": "avg by (instance) (\r\n    irate(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", mode=\"system\",deployment_environment=\"$env\"}[5m])\r\n) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Idle Percentage by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "avg by (instance) (\r\n    irate(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", mode=\"idle\",deployment_environment=\"$env\"}[5m])\r\n) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Core Count by Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
     "targets": [
      {
       "expr": "count by (instance) (\r\n    count(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}) by (cpu, instance)\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage Efficiency by Instances",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count by (instance) (count(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}) by (cpu, instance))) \r\n- \r\navg by (instance) (sum by (instance, mode)(irate(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", mode=\"idle\",deployment_environment=\"$env\"}[$__rate_interval])))) * 100) \r\n/ \r\ncount by(instance) (count(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}) by (cpu, instance))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total CPU Utilization in Seconds Across All Instances",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", mode=\"idle\",deployment_environment=\"$env\"}[5m])) by (mode, instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "references Braden's query dashboard",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 50 },
     "targets": [
      {
       "expr": "(\r\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", mode=~\"idle|iowait|steal\",deployment_environment=\"$env\"}[$__rate_interval])))\r\n/ ignoring(cpu) group_left\r\n  count without (cpu, mode) (node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", mode=\"idle\",deployment_environment=\"$env\"})\r\n) * 100\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average CPU Utilization Percentage by Instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 50 },
     "targets": [
      {
       "expr": "avg by (instance) (irate(node_cpu_seconds_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", mode=\"idle\",deployment_environment=\"$env\"}[5m])) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Memory Usage (in bytes) by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (instance) (node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"} - node_memory_MemAvailable_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Memory Usage (in bytes) across All Instances",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}) - sum(node_memory_MemAvailable_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage Percentage by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (instance) (\r\n    100 - (100 * (node_memory_MemAvailable_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"} / node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}))\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage Percentage (Average) across All Instances",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (100 * avg by (instance) (node_memory_MemAvailable_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"} / node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Swap Total Bytes by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (node_memory_SwapTotal_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Memory Usage (in bytes) by Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (instance) (node_memory_MemTotal_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"} - node_memory_MemAvailable_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Memory Swap Total Bytes across All Instances",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(node_memory_SwapTotal_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Memory Swap Total Bytes across All Instances",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(node_memory_SwapTotal_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free Disk Space (in bytes) by Instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (\r\n    node_filesystem_avail_bytes{fstype!=\"\", mountpoint!=\"\", job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Disk Space (in bytes) by Instance",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (\r\n    node_filesystem_size_bytes{fstype!=\"\", mountpoint!=\"\", job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Used Disk Space (in bytes) by Instance",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (\r\n    node_filesystem_used_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", fstype!=\"\", mountpoint!=\"\",deployment_environment=\"$env\"}\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Available Disk Space (in bytes) by Instance",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 9, "x": 7, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (\r\n    node_filesystem_avail_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", fstype!=\"\", mountpoint!=\"\",deployment_environment=\"$env\"}\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Space Usage Percentage by Instance",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (instance) (\r\n    100 * (1 - (node_filesystem_avail_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", fstype!=\"\", mountpoint!=\"\",deployment_environment=\"$env\"} / node_filesystem_size_bytes{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\", fstype!=\"\", mountpoint!=\"\",deployment_environment=\"$env\"}))\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}[5m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}[5m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (instance) (\r\n    rate(container_network_receive_bytes_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\"}[5m])\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (instance) (\r\n    rate(container_network_transmit_bytes_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\"}[5m])\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Errors & Dropped Packets",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 102 },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}[5m])) by (instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_dropped_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\",deployment_environment=\"$env\"}[5m])) by (instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\"}[5m])) by (instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(container_network_transmit_packets_dropped_total{job=~\"integrations/(node_exporter|unix)\", instance=~\".*ec2.*\"}[5m])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}