{
 "title": "AWS WAF",
 "description": "Visualize AWS WAF metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(aws_wafv2_info{scrape_job=\"$env\"},region)"
    }
   },
   {
    "name": "Region",
    "label": "WAF Region",
    "query": {
     "query": "label_values(aws_wafv2_allowed_requests_sum{scrape_job=\"$env\"},dimension_Region)"
    }
   },
   {
    "name": "WebACL",
    "label": "WebACL",
    "query": {
     "query": "label_values(aws_wafv2_allowed_requests_sum{scrape_job=\"$env\"},dimension_WebACL)"
    }
   },
   {
    "name": "Rule",
    "label": "Rule",
    "query": {
     "query": "label_values(aws_wafv2_allowed_requests_sum{scrape_job=\"$env\"},dimension_Rule)"
    }
   },
   {
    "name": "RuleGroup",
    "label": "RuleGroup",
    "query": {
     "query": "label_values(aws_wafv2_allowed_requests_sum{scrape_job=\"$env\"},dimension_ManagedRuleGroup)"
    }
   },
   { "name": "env", "query": "kansas-prod" }
  ]
 },
 "panels": [
  {
   "title": "AllowedRequests / BlockedRequests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(region) (aws_wafv2_allowed_requests_sum{dimension_Rule=~\"$Rule\", scrape_job=\"$env\"})",
     "legendFormat": "AllowedRequests"
    },
    {
     "expr": "count by(region) (aws_wafv2_blocked_requests_sum{dimension_Rule=~\"$Rule\", scrape_job=\"$env\"})",
     "legendFormat": "BlockedRequests"
    }
   ]
  },
  {
   "title": "CountedRequests / PassedRequests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(region) (aws_wafv2_counted_requests_sum{dimension_Rule=~\"$Rule\", scrape_job=\"$env\"})",
     "legendFormat": "CountedRequests"
    },
    {
     "expr": "count by(region) (aws_wafv2_passed_requests_sum{dimension_Rule=~\"$Rule\", scrape_job=\"$env\"})",
     "legendFormat": "PassedRequests"
    }
   ]
  },
  {
   "title": "CaptchaRequests / RequestsWithValidCaptchaToken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(region) (aws_wafv2_captcha_requests_sum{dimension_Rule=~\"$Rule\", scrape_job=\"$env\"})",
     "legendFormat": "CaptchaRequests"
    },
    {
     "expr": "count by(region) (aws_wafv2_requests_with_valid_captcha_token_sum{dimension_Rule=~\"$Rule\", scrape_job=\"$env\"})",
     "legendFormat": "RequestsWithValidCaptchaToken"
    }
   ]
  },
  {
   "title": "CaptchasAttempted / CaptchasSolved",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(region) (aws_wafv2_captchas_attempted_sum{dimension_Rule=~\"$Rule\", scrape_job=\"$env\"})",
     "legendFormat": "CaptchasAttempted"
    },
    {
     "expr": "count by(region) (aws_wafv2_captchas_solved_sum{dimension_Rule=~\"$Rule\", scrape_job=\"$env\"})",
     "legendFormat": "CaptchasSolved"
    }
   ]
  },
  {
   "title": "ChallengeRequests / RequestsWithValidChallengeToken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(region) (aws_wafv2_challenge_requests_sum{dimension_Rule=~\"$Rule\", scrape_job=\"$env\"})",
     "legendFormat": "ChallengeRequests"
    },
    {
     "expr": "count by(region) (aws_wafv2_requests_with_valid_challenge_token_sum{dimension_Rule=~\"$Rule\", scrape_job=\"$env\"})",
     "legendFormat": "RequestsWithValidChallengeToken"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 45 },
   "options": {
    "content": "<a href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/waf/latest/developerguide/monitoring-cloudwatch.html\">AWS CloudWatch WAF documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/????\">Installed from Grafana.com dashboards</a>\n"
   }
  }
 ]
}