{
 "title": "AWS ElastiCache Redis",
 "description": "Visualize AWS ElastiCache Redis metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(aws_elasticache_info,scrape_job)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(aws_elasticache_info,region)"
    }
   },
   {
    "name": "cachenodeid",
    "label": "Shard ID",
    "query": {
     "query": "label_values(aws_elasticache_cache_hits_average{dimension_CacheClusterId=\"$cacheclusterId\"},dimension_CacheNodeId)"
    }
   },
   {
    "name": "cacheclusterId",
    "label": "Node ID",
    "query": {
     "query": "label_values(aws_elasticache_active_defrag_hits_average,dimension_CacheClusterId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_elasticache_cache_hits_average{region=\"$region\", scrape_job=\"$env\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_elasticache_cache_misses_average{region=\"$region\", scrape_job=\"$env\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_elasticache_evictions_average{region=\"$region\", scrape_job=\"$env\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_elasticache_reclaimed_average{region=\"$region\", scrape_job=\"$env\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "aws_elasticache_cache_hit_rate_average{region=\"$region\", scrape_job=\"$env\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Evictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "aws_elasticache_evictions_sum{region=\"$region\", scrape_job=\"$env\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cmds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_elasticache_get_type_cmds_average{region=\"$region\", scrape_job=\"$env\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_elasticache_hash_based_cmds_average{region=\"$region\", scrape_job=\"$env\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_elasticache_list_based_cmds_average{region=\"$region\", scrape_job=\"$env\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_elasticache_set_based_cmds_average{region=\"$region\", scrape_job=\"$env\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_elasticache_set_type_cmds_average{region=\"$region\", scrape_job=\"$env\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_elasticache_set_based_cmds_average{region=\"$region\", scrape_job=\"$env\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_elasticache_string_based_cmds_average{region=\"$region\", scrape_job=\"$env\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_elasticache_new_connections_average{scrape_job=\"$env\", region=\"$region\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_elasticache_curr_connections_average{scrape_job=\"$env\", region=\"$region\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SaveInProgress / CurrItems",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_elasticache_save_in_progress_average{scrape_job=\"$env\", region=\"$region\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_elasticache_curr_items_average{scrape_job=\"$env\", region=\"$region\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BytesUsedForCache / ReplicationBytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_elasticache_bytes_used_for_cache_average{scrape_job=\"$env\", region=\"$region\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_elasticache_replication_bytes_average{scrape_job=\"$env\", region=\"$region\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HyperLogLogBasedCmds / ReplicationLag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_elasticache_replication_lag_average{scrape_job=\"$env\", region=\"$region\", dimension_CacheClusterId=\"$cacheclusterId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CacheNodeId $cachenodeid DatabaseMemoryUsagePercentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_elasticache_database_memory_usage_percentage_average{scrape_job=\"$env\", region=\"$region\", dimension_CacheClusterId=\"$cacheclusterId\", dimension_CacheNodeId=\"$cachenodeid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CacheNodeId $cachenodeid CPUUtilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_elasticache_cpuutilization_average{scrape_job=\"$env\", region=\"$region\", dimension_CacheClusterId=\"$cacheclusterId\", dimension_CacheNodeId=\"$cachenodeid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CacheNodeId $cachenodeid NetworkBytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_elasticache_network_bytes_in_average{scrape_job=\"$env\", region=\"$region\", dimension_CacheClusterId=\"$cacheclusterId\", dimension_CacheNodeId=\"$cachenodeid\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_elasticache_network_bytes_out_average{scrape_job=\"$env\", region=\"$region\", dimension_CacheClusterId=\"$cacheclusterId\", dimension_CacheNodeId=\"$cachenodeid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CacheNodeId $cachenodeid FreeableMemory / SwapUsage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_elasticache_swap_usage_average{scrape_job=\"$env\", region=\"$region\", dimension_CacheClusterId=\"$cacheclusterId\", dimension_CacheNodeId=\"$cachenodeid\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_elasticache_freeable_memory_average{scrape_job=\"$env\", region=\"$region\", dimension_CacheClusterId=\"$cacheclusterId\", dimension_CacheNodeId=\"$cachenodeid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 78 },
   "options": {
    "content": "<a href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheMetrics.html\">AWS CloudWatch ElastiCache documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/969\">Installed from Grafana.com dashboards</a>"
   }
  }
 ]
}