{
 "title": "Infrastructure Metrics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "KafkaJob",
    "label": "Job Name",
    "query": {}
   },
   {
    "name": "SiteName",
    "label": "Site",
    "query": {}
   },
   {
    "name": "DeliveryGroup",
    "label": "Delivery Group",
    "query": {}
   },
   {
    "name": "MachineName",
    "label": "Machine",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total Machines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} | json machineId = \"machineId\" | machineId != \"\""
    }
   ]
  },
  {
   "title": "Machine count by state",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} | json machineId = \"machineId\", machineName=\"machineName\", machinePowerState = \"machinePowerState\", machineActualStatus=\"machineActualStatus\", status=\"status\", isMaintenanceMode=\"isMaintenanceMode\", isUnregistered=\"isUnregistered\", activeSessionCount=\"activeSessionCount\" | machineId != \"\"\r\n| label_format \r\n    finalState = `\r\n      {{ if eq .status \"1\" }} Unregistered\r\n      {{ else if eq .status \"4\" }} Failed\r\n      {{ else if or (eq .status \"3\") (and (eq .status \"5\") (gt .isMaintenanceMode \"0\")) }} Maintenance\r\n      {{ else if and (eq .status \"2\") (gt .activeSessionCount \"0\") }} Active\r\n      {{ else if or (and (eq .status \"5\") (eq .isMaintenanceMode \"0\")) (and (eq .status \"2\") (eq .activeSessionCount \"0\")) }} Ready for Use\r\n      {{ else }} Other\r\n      {{end}}`"
    }
   ]
  },
  {
   "title": "Machine count by OS",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} | json machineId = \"machineId\", operatingSystem = \"operatingSystem\" | machineId != \"\" | label_format os=`\r\n    {{ if eq .operatingSystem \"\"}} Unknown\r\n    {{ else }} {{.operatingSystem}}\r\n    {{end}}`"
    }
   ]
  },
  {
   "title": "Machine count by Provisioning type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} | json machineId = \"machineId\", machineName=\"machineName\", machineProvisioningType = \"machineProvisioningType\" | machineId != \"\"\r\n| label_format \r\n    provType = `\r\n      {{ if eq .machineProvisioningType \"0\" }} Unknown\r\n      {{ else if eq .machineProvisioningType \"1\" }} MCS\r\n      {{ else if eq .machineProvisioningType \"2\" }} PVS\r\n      {{ else if eq .machineProvisioningType \"3\" }} Manual\r\n      {{ else }} Unknown\r\n      {{end}}`"
    }
   ]
  },
  {
   "title": "Machine count by state",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} | json machineId = \"machineId\", machineName=\"machineName\", machinePowerState = \"machinePowerState\", machineActualStatus=\"machineActualStatus\", status=\"status\", isMaintenanceMode=\"isMaintenanceMode\", isUnregistered=\"isUnregistered\", activeSessionCount=\"activeSessionCount\" | machineId != \"\"\r\n| label_format \r\n    finalState = `\r\n      {{ if eq .status \"1\" }} Unregistered\r\n      {{ else if eq .status \"4\" }} Failed\r\n      {{ else if or (eq .status \"3\") (and (eq .status \"5\") (gt .isMaintenanceMode \"0\")) }} Maintenance\r\n      {{ else if and (eq .status \"2\") (gt .activeSessionCount \"0\") }} Active\r\n      {{ else if or (and (eq .status \"5\") (eq .isMaintenanceMode \"0\")) (and (eq .status \"2\") (eq .activeSessionCount \"0\")) }} Ready for Use\r\n      {{ else }} Other\r\n      {{end}}`"
    }
   ]
  },
  {
   "title": "Machine count by Agent Version",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 6, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} | json machineId = \"machineId\", agentVersion = \"agentVersion\" | machineId != \"\" | label_format version=`\r\n    {{ if eq .agentVersion \"\"}} Unknown\r\n    {{ else }} {{.agentVersion}}\r\n    {{end}}`"
    }
   ]
  },
  {
   "title": "Machine states",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} | json machineId = \"machineId\", machineName=\"machineName\", machinePowerState = \"machinePowerState\", machineActualStatus=\"machineActualStatus\", status=\"status\", isMaintenanceMode=\"isMaintenanceMode\", isUnregistered=\"isUnregistered\", activeSessionCount=\"activeSessionCount\", operatingSystem=\"operatingSystem\", agentVersion=\"agentVersion\", activeSessionCount=\"activeSessionCount\" | machineId != \"\"\r\n| label_format \r\n    finalState = `\r\n      {{ if eq .status \"1\" }} Unregistered\r\n      {{ else if eq .status \"4\" }} Failed\r\n      {{ else if or (eq .status \"3\") (and (eq .status \"5\") (gt .isMaintenanceMode \"0\")) }} Maintenance\r\n      {{ else if and (eq .status \"2\") (gt .activeSessionCount \"0\") }} Active\r\n      {{ else if or (and (eq .status \"5\") (eq .isMaintenanceMode \"0\")) (and (eq .status \"2\") (eq .activeSessionCount \"0\")) }} Ready for Use\r\n      {{ else }} Other\r\n      {{end}}`"
    }
   ]
  },
  {
   "title": "Max / Avg CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(quantile_over_time(0.95, {eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} | json percentCpu = \"percentCpu\" | percentCpu > 0 | unwrap percentCpu [5m]))",
     "legendFormat": "Max CPU Utilization"
    },
    {
     "expr": "avg(avg_over_time({eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} | json percentCpu = \"percentCpu\" | percentCpu > 0 | unwrap percentCpu [5m]))",
     "legendFormat": "Average CPU Utilization"
    }
   ]
  },
  {
   "title": "Max / Avg CPU Utilization",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (deliveryGroupName) (quantile_over_time(0.95, {eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} | json percentCpu = \"percentCpu\" | percentCpu != \"\" | unwrap percentCpu [$__range]) by (deliveryGroupName))",
     "legendFormat": "{{deliveryGroupName}}"
    },
    {
     "expr": "avg by (deliveryGroupName) (avg_over_time({eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} | json percentCpu = \"percentCpu\" | percentCpu != \"\" | unwrap percentCpu [$__range]) by (deliveryGroupName))",
     "legendFormat": "{{deliveryGroupName}}"
    }
   ]
  },
  {
   "title": "Max / Avg Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(quantile_over_time(0.95, {eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} \r\n| json usedMemory = \"usedMemory\", totalMemory=\"totalMemory\" \r\n| usedMemory != \"\" and totalMemory!=\"\" and usedMemory != \"0.0\" and totalMemory!=\"0.0\"\r\n| label_format \r\nmemoryConsumption = `{{divf .usedMemory .totalMemory 0.01 }}`\r\n| unwrap memoryConsumption [5m]))",
     "legendFormat": "Max Memory Consumption"
    },
    {
     "expr": "avg(avg_over_time({eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} \r\n| json usedMemory = \"usedMemory\", totalMemory=\"totalMemory\" \r\n| usedMemory != \"\" and totalMemory!=\"\" and usedMemory != \"0.0\" and totalMemory!=\"0.0\"\r\n| label_format \r\nmemoryConsumption = `{{divf .usedMemory .totalMemory 0.01 }}`\r\n| unwrap memoryConsumption [5m]))",
     "legendFormat": "Avg  Memory Consumption"
    }
   ]
  },
  {
   "title": "Max / Avg Memory Consumption",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 11, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "{eventType=\"Machine\",job=~\"${KafkaJob}\",siteName=~\"${SiteName}\",deliveryGroupName=~\"${DeliveryGroup}\",machineName=~\"${MachineName}\"} | json usedMemory = \"usedMemory\", totalMemory=\"totalMemory\" | usedMemory != \"\" and totalMemory!=\"\"",
     "legendFormat": "Max CPU Utilization"
    }
   ]
  }
 ]
}